// What the Claude command row says. Copy lives in modules like this one, never inline in a component.
export const C = {
  title: 'The claude command',
  separate: 'Separate',
  wrapped: 'Wrapped',
  separateWhy: 'Splice leaves claude on your PATH alone. Its own command shares your ~/.claude setup and sessions by default.',
  wrappedWhy: 'Splice runs claude through itself. Wrapping rewrote two files in ~/.claude and shadowed the command; unwrapping puts them back.',
  onPath: 'claude on your PATH',
  notFound: 'Nothing named claude',
  shim: 'The splice shim',
  realBinary: 'It runs',
  unknown: 'Not read',
  logins: 'Claude logins',
  noLogins: 'None stored',
  selected: 'Launches with',
  noneSelected: 'None chosen',
  backups: 'Backed up to',
  wrap: 'Wrap',
  wrapTitle: 'Wrap the claude command?',
  wrapWhy: 'Splice rewrites two files in ~/.claude, backs each up first, and shadows the claude command with its own.',
  unwrap: 'Unwrap',
  unwrapTitle: 'Unwrap the claude command?',
  unwrapWhy: 'Splice puts back the two files and the claude command it replaced.',
  cancel: 'Cancel',
  reading: 'Reading the claude command.',
} as const;
