// What the Projects pages say. Copy lives in modules like this one, never inline in a component.
export const P = {
  back: 'Sessions',
  reading: 'Reading the project.',
  gone: 'No such project.',
  goneWhy: 'A project shows once a session runs in the repo or a team declares it.',
  openProject: 'Open the project',
  running: (n: number): string => `${n} ${n === 1 ? 'session is' : 'sessions are'} running`,
  noneRunning: 'Nothing is running',
  teams: (n: number): string => `and ${n} ${n === 1 ? 'team works' : 'teams work'} here`,
  noTurnsToday: 'No turns today.',
  turnsToday: (n: number): string => `${n.toLocaleString('en-US')} ${n === 1 ? 'turn' : 'turns'} today.`,
  costToday: (usd: string): string => `About ${usd} of API cost.`,
  costUnpriced: 'No turn here was priced today.',
  showFolder: 'Show the folder',
  showPath: 'Show the path',
  fileName: (kind: string): string => (kind === 'instructions' ? 'This project’s CLAUDE.md' : kind === 'memory' ? 'This project’s memory' : kind),
  sessionsTitle: 'Sessions here',
  sessionsNone: 'No session is running in this repo.',
  teamsTitle: 'Teams',
  compaction: 'Compaction rules',
  compactionWhy: 'The instructions a compaction here runs under; the most specific rule wins.',
  compactionNone: 'No rule applies, so Claude Code’s own instructions stand.',
  compactionUnwired: 'splice did not report its compaction rules.',
  standingTitle: 'Standing prompt and rule',
  standingWhy: 'This repo’s prompt and compaction rule, as splice.toml holds them. They apply after splice restarts, at each session’s next turn.',
  prompt: 'Standing prompt',
  rule: 'Compaction rule',
  fromFile: 'Read from a file',
  fromFileWhy: 'Edit the file, or clear it in Settings.',
  reaches: 'Reaches',
  reachesNone: 'No live sessions.',
  save: 'Save',
  saving: 'Saving…',
  saved: 'Saved. It applies after splice restarts.',
  failed: 'That did not save:',
  unavailable: 'This splice cannot edit its configuration file.',
  readingStanding: 'Reading the configuration file.',
  filesTitle: 'Files splice read',
  filesWhy: 'Instructions and memory, exactly as Claude Code would see them.',
  filesNone: 'No instruction or memory file was found.',
  filesLooked: 'Looked in',
  memoryOff: 'Claude Code’s automatic memory is off for this project.',
  statuslineTitle: 'Where each command looks for a branch',
  statuslineWhy: 'The trusted folder each command’s status line finds this repo under.',
  noBranch: 'None: no branch shown',
  trusted: { home: 'Home folder', tmp: 'Temp folder', statuslineGitRoots: 'A git folder you added' },
  activity: 'Last seen',
  never: 'No session has touched it.',
  noPlans: 'No commands yet.',
  head: 'Command',
} as const;
