// What the Usage page says. Copy lives in modules like this one, never inline in a component.
/** A window in hours as a person says it. */
export const spanWords = (hours: number): string => (hours === 24 ? 'the last 24 hours' : hours === 168 ? 'the last 7 days' : `the last ${Math.round(hours / 24)} days`);

export const U = {
  title: 'Usage',
  reading: 'Reading the usage.',
  readingMetric: 'Reading…',
  readingRequests: 'Reading requests…',
  requestsUnavailable: 'Request history unavailable',
  countNotReported: 'The request count was not reported.',
  historyUnreadable: 'The daemon returned an unreadable request history.',
  commandsReading: (names: string) => `Still reading requests for ${names}.`,
  window: 'Window',
  totalsTurns: 'Requests',
  totalsTurnsWhy: (commands: number, span: string, incomplete = false) => `${incomplete ? 'Across at least' : 'Across'} ${commands} ${commands === 1 ? 'command' : 'commands'} with requests in ${span}.`,
  totalsTurnsReading: 'Reading which commands had requests…',
  totalsIn: 'Tokens read in',
  totalsInWhy: (cached: string) => `${cached} came from the cache.`,
  totalsInPlain: 'Everything the models were asked to read.',
  totalsOut: 'Tokens written out',
  totalsOutWhy: 'Answers, tools and thinking.',
  totalsCost: 'API cost, estimated',
  totalsCostWhy: 'Equivalent API cost at the declared model prices, not a subscription bill.',
  totalsCostUnpriced: (n: number) => `${n} ${n === 1 ? 'turn' : 'turns'} left out: no price.`,
  totalsCostNone: 'No dollar estimate is available for this window.',
  plansTitle: 'Each command against its limit',
  plansWhy: 'The provider reports each limit. splice only marks a command out of quota when the provider refuses it.',
  plansNone: 'No command has reported its usage yet.',
  ofLimit: (pct: number, window?: string | null) => window == null ? `${pct}% of its reported limit` : `${pct}% of its ${window === '5h' ? '5-hour' : window === '7d' ? 'weekly' : window} limit`,
  noLimit: 'No limit reported',
  rateLimitReading: (age: string): string => `Last rate-limit reading ${age}`,
  refused: 'Out of quota',
  resets: (when: string) => `resets ${when}`,
  paceLess: 'less than an hour left at this pace',
  paceHours: (n: number) => `about ${n} ${n === 1 ? 'hour' : 'hours'} left at this pace`,
  paceDays: (n: number) => `about ${n} ${n === 1 ? 'day' : 'days'} left at this pace`,
  idle: 'idle in this window',
  idlePlans: (names: string, span: string) => `No requests in ${span} on ${names}.`,
  readIn: 'tokens read in',
  cached: (pct: string) => `${pct} cached`,
  noCache: 'Cache share not reported',
  sparkLabel: 'Tokens per hour, last 24 hours',
  budgetsTitle: 'Budgets',
  budgetsWhy: 'A budget is your own daily ceiling in dollars. splice tells you, or stops the turn, when a command reaches it.',
  budgetsPending: 'This splice does not serve budgets yet.',
  budgetsUnreadable: (why: string) => `Budgets could not be read, so every command runs with none: ${why}`,
  budgetSet: (usd: string, spent: string, action: 'warn' | 'block') => `${usd} a day. ${spent} spent in its daily budget window. ${action === 'block' ? 'splice stops turns once it is reached.' : 'splice tells you once it is reached.'}`,
  budgetNone: 'No command has a budget.',
  budgetAdd: 'Add a budget',
  budgetPlan: 'Command',
  budgetChange: 'Change',
  budgetDialog: (plan: string) => `Budget for ${plan}`,
  budgetDialogWhy: 'Dollars a day, at the model’s public prices.',
  budgetDollars: 'Dollars a day',
  budgetAction: 'When it is reached',
  budgetWarn: 'Tell me',
  budgetWarnHint: 'The turn still runs.',
  budgetBlock: 'Stop the turn',
  budgetBlockHint: 'New turns are refused until tomorrow.',
  budgetSave: 'Save',
  budgetRemove: 'Remove the budget',
  budgetCancel: 'Cancel',
  budgetFailed: 'That did not save:',
  alertsTitle: 'Alerts',
  alertsWhy: 'Where splice sends a message when a command nears a usage limit or reaches its budget.',
  alertsPending: 'This splice does not serve alerts yet.',
  alertWebhook: 'Webhook',
  alertWebhookWhy: 'A URL splice posts to.',
  alertWebhookNone: 'None set',
  alertWebhookSave: 'Save the webhook',
  alertTest: 'Send a test',
  alertTestWhy: 'Posts to the saved webhook and tells you what it said.',
  alertTestNeeds: 'Save a webhook first.',
  alertTestSent: 'Sent.',
  alertFailed: 'That did not work:',
  on: 'On',
  off: 'Off',
} as const;
