// What the "What splice keeps" block says. Copy lives in modules like this one, never inline in a component.
export const K = {
  title: 'What splice keeps',
  why: 'Each store, what is in it, how long it stays, and how to stop or clear it.',
  unknown: 'Not read yet.',
  none: 'Nothing is kept.',
  count: (days: number, entries: number): string => `${days} ${days === 1 ? 'day' : 'days'}, ${entries} ${entries === 1 ? 'entry' : 'entries'} kept.`,
  traceCount: (records: number, bytes: string): string => `${records} ${records === 1 ? 'record' : 'records'}, ${bytes} kept.`,
  agesOut: (date: string): string => `The last kept day ages out on ${date}.`,
  delete: 'Delete what is kept',
  deleteTitle: (store: string): string => `Delete ${store}?`,
  deleteAct: (days: number, entries: number): string => `Delete ${days} ${days === 1 ? 'day' : 'days'} and ${entries} ${entries === 1 ? 'entry' : 'entries'}`,
  cancel: 'Cancel',
  edges: { name: 'Message edges', holds: 'Who messaged whom and when, never the message itself. Whole UTC days, as Message history sets them.', switchWhy: 'Applies after splice restarts.' },
  labels: { name: 'Activity labels', holds: 'File names, commands and search patterns from tool activity. Today and yesterday; older days age out on the next sweep.', plansEvery: 'Every command', plansNone: 'No command', plansSome: (kept: number, total: number): string => `${kept} of ${total} commands`, choose: 'Choose commands', chooseLabel: (plan: string): string => `Keep activity labels for ${plan}` },
  trace: { name: 'Request capture', holds: 'Full requests and answers for commands with capture on. Whole UTC days, as Request history sets them. Turn capture on from a turn’s page.', plan: (label: string): string => `Capture on ${label}`, none: 'No command has a trace directory.' },
  wire: { name: 'Sent bodies', holds: 'The last few request bodies each command sent, kept in memory only; a restart clears them.' },
  transcripts: { name: 'Transcript view', holds: 'Claude Code’s own conversation files. Splice reads them and never deletes them; Claude Code decides when they go.', switchWhy: 'Applies at once.' },
  turns: {
    name: 'Turn statistics',
    holds: 'Finished turns: model, session, outcome, timing, tokens and cost. Current files never expire on their own.',
    deleteWhy: 'Every recorded turn goes. The Turns page and per-turn costs start again with the next turn, and open sessions count their cost from zero.',
    archive: 'Days to keep old files',
    archiveWhy: 'Zero stops archiving; current turns keep recording either way. Applies after splice restarts.',
  },
  deleteWhy: 'This cannot be undone.',
  switchLabel: (name: string): string => `Keep ${name.toLowerCase()}`,
} as const;
