// What the configuration-file editor says. Copy lives in modules like this one, never inline in a component.
export const CF = {
  title: 'Configuration file',
  why: 'splice backs it up before each write and writes it through its own writer. Changes apply after splice restarts.',
  showPath: 'Show the path',
  open: 'Open the file',
  close: 'Close the file',
  topLevel: 'Top level',
  groups: {
    daemon: 'splice',
    heads: 'Commands',
    providers: 'Providers',
    defaults: 'Defaults for every command',
    compaction: 'Compaction',
    projects: 'Projects',
    claude: 'Claude',
    auth: 'Sign-in',
  } as Readonly<Record<string, string>>,
  removeOverride: 'Remove this override',
  changes: (n: number): string => (n === 0 ? 'No changes yet.' : `${n} ${n === 1 ? 'change' : 'changes'} to write.`),
  from: 'was',
  unset: 'not set',
  write: 'Write the file',
  writing: 'Writing…',
  written: 'Written. It applies after splice restarts.',
  backup: 'The old file is kept at',
  failed: 'That was not written:',
  problems: 'splice’s own check found:',
  raw: 'The file as it will read',
  rawWhy: 'A view of the document as parsed. Comments and layout from your own file are kept on disk, not shown here.',
  unavailable: 'This splice cannot edit its configuration file.',
} as const;
