// What the Add-a-plan flow says, ported from the old console's add-backend and connect-plan strings.
export const PLAN_NAMES = { codex: 'ChatGPT', grok: 'Grok', kimi: 'Kimi', muse: 'Muse', openrouter: 'OpenRouter key', local: 'Local model' } as const;
export const PLAN_LABELS = { ...PLAN_NAMES, deepseek: 'DeepSeek', claude: 'Claude', 'api-key': 'API key' } as const;

export const PLAN_WHY = {
  codex: 'Sign in with your ChatGPT plan.',
  grok: 'Sign in with your Grok plan.',
  kimi: 'Connect your Kimi plan.',
  muse: 'Connect your Muse plan.',
  openrouter: 'Use an OpenRouter API key.',
  local: 'Connect a local OpenAI-compatible endpoint.',
} as const satisfies Record<keyof typeof PLAN_NAMES, string>;

export const AD = {
  title: 'Add a command',
  choose: 'Which command?',
  chooseWhy: 'Sign in with a subscription, paste an API key, or point at your own GPU.',
  loading: 'Reading the commands splice can add…',
  unavailable: 'Unavailable in this splice build.',
  others: 'Other providers',
  details: (plan: string): string => `About your ${plan}`,
  name: 'Command name',
  baseUrl: 'Provider address',
  models: 'Models',
  modelId: 'Model id',
  window: 'Context window (tokens)',
  addModel: 'Add a model',
  next: 'Continue',
  back: 'Back',
  cancel: 'Cancel',
  closed: 'Close',
  opening: 'Opening…',
  retryOpen: 'Try again',
  command: 'Terminal command',
  signsIn: 'Signs in with',
  signInBy: { login: 'A browser login', key: 'An API key', none: 'Your Claude login' } as const,
  forwarded: 'Your Claude login is forwarded at launch; nothing to sign in.',
  localNoKey: 'No key is needed for this local runtime.',
  key: (name: string): string => `Store the key it reads from ${name}; the checks read it next.`,
  keyField: 'Key',
  keySave: 'Store the key',
  keyStored: 'Key stored',
  signIn: 'Sign in',
  signingIn: 'Waiting for the sign-in…',
  login: 'Sign in in the browser; this follows the login.',
  openVerification: 'Open the sign-in page',
  openSignIn: 'Open the sign-in',
  copy: 'Copy',
  copied: 'Copied',
  check: 'Run the checks',
  checking: 'Checking…',
  checkLive: 'Also send one short turn',
  checksTitle: 'Checks',
  windowFitsDiagnostic: 'declared rows fit the window sizes the provider lists',
  windowFits: 'Every model’s context window fits what the provider serves.',
  passed: 'Passed',
  failed: 'Failed',
  save: 'Save and restart',
  saving: 'Saving…',
  retrySave: 'Try saving again',
  finishing: 'Saving your signed-in command and restarting splice.',
  discard: 'Discard',
  saved: (plan: string): string => `${plan} saved`,
  launch: 'Type this command in your terminal after the restart.',
  draining: 'splice is restarting; the command appears once it is back.',
  waiting: (count: number): string => `The restart waits for ${count} ${count === 1 ? 'compaction' : 'compactions'} to finish.`,
  restartManually: 'Run splice restart, then come back to the command.',
  written: 'Written to',
  notLinked: 'The command is not linked yet.',
  failedTo: 'That did not work:',
} as const;
