// What the Usage page says. Copy lives in modules like this one, never inline in a component.
/** A window in hours as a person says it. */
export const spanWords = (hours: number): string => (hours === 24 ? 'the last 24 hours' : hours === 168 ? 'the last 7 days' : `the last ${Math.round(hours / 24)} days`);

export const U = {
  title: 'Usage',
  reading: 'Reading the usage.',
  window: 'Window',
  totalsTurns: 'Turns',
  totalsTurnsWhy: (plans: number, span: string) => `Across ${plans} ${plans === 1 ? 'command' : 'commands'} in ${span}.`,
  totalsIn: 'Tokens read in',
  totalsInWhy: (cached: string) => `${cached} came from the cache.`,
  totalsInPlain: 'Everything the commands were asked to read.',
  totalsOut: 'Tokens written out',
  totalsOutWhy: 'Answers, tools and thinking.',
  totalsCost: 'API cost, estimated',
  totalsCostWhy: 'At each model’s public prices.',
  totalsCostUnpriced: (n: number) => `${n} ${n === 1 ? 'turn' : 'turns'} left out: no price.`,
  totalsCostNone: 'No turn in this window has a price.',
  plansTitle: 'Each command against its limit',
  plansWhy: 'The limit is the provider’s own. The pace is the last few hours’, so it moves when you do.',
  plansNone: 'No command has reported its usage yet.',
  ofLimit: (pct: number) => `${pct}% of its limit`,
  noLimit: 'No limit reported',
  resets: (when: string) => `resets ${when}`,
  paceLess: 'less than an hour left at this pace',
  paceHours: (n: number) => `about ${n} ${n === 1 ? 'hour' : 'hours'} left at this pace`,
  paceDays: (n: number) => `about ${n} ${n === 1 ? 'day' : 'days'} left at this pace`,
  idle: 'idle in this window',
  idlePlans: (names: string, span: string) => `No turns in ${span} on ${names}.`,
  readIn: 'tokens read in',
  cached: (pct: string) => `${pct} cached`,
  noCache: 'no cache',
  sparkLabel: 'Tokens per hour, last 24 hours',
  budgetsTitle: 'Budgets',
  budgetsWhy: 'A budget is your own daily ceiling in dollars. splice tells you, or stops the turn, when a command reaches it.',
  budgetsPending: 'This splice does not serve budgets yet.',
  budgetsUnreadable: (why: string) => `Budgets could not be read, so every command runs with none: ${why}`,
  budgetSet: (usd: string, spent: string, action: 'warn' | 'block') => `${usd} a day. ${spent} spent in the last 24 hours. ${action === 'block' ? 'splice stops turns once it is reached.' : 'splice tells you once it is reached.'}`,
  budgetNone: 'No command has a budget.',
  budgetAdd: 'Add a budget',
  budgetPlan: 'Command',
  budgetChange: 'Change',
  budgetDialog: (plan: string) => `Budget for ${plan}`,
  budgetDialogWhy: 'Dollars a day, at the model’s public prices.',
  budgetDollars: 'Dollars a day',
  budgetAction: 'When it is reached',
  budgetWarn: 'Tell me',
  budgetWarnHint: 'The turn still runs.',
  budgetBlock: 'Stop the turn',
  budgetBlockHint: 'New turns are refused until tomorrow.',
  budgetSave: 'Save',
  budgetRemove: 'Remove the budget',
  budgetCancel: 'Cancel',
  budgetFailed: 'That did not save:',
  alertsTitle: 'Alerts',
  alertsWhy: 'Where splice sends a message when a command nears a limit or a budget.',
  alertsPending: 'This splice does not serve alerts yet.',
  alertWebhook: 'Webhook',
  alertWebhookWhy: 'A URL splice posts to.',
  alertWebhookNone: 'None set',
  alertWebhookSave: 'Save the webhook',
  alertTest: 'Send a test',
  alertTestWhy: 'Posts to the saved webhook and tells you what it said.',
  alertTestNeeds: 'Save a webhook first.',
  alertTestSent: 'Sent.',
  alertFailed: 'That did not work:',
  on: 'On',
  off: 'Off',
} as const;
