// What the plan-card derivation says: each state's one line and its note. Copy lives in modules like this one, never inline in logic.
export const FL = {
  stopped: 'This command is not running.',
  unhealthy: 'Its health check is failing.',
  signedOut: 'Its next turn will fail until you sign in.',
  keyMissing: 'Its next turn will fail until its key is set.',
  loginExpired: 'Its login could not be refreshed, so its next turn will fail.',
  accountExcluded: 'The pool has set its selected account aside.',
  queueFull: 'Turns are waiting for a free slot.',
  restartNeeded: 'The configuration changed after this command started.',
  payPerToken: 'Pays per token; no window',
  noReading: 'No reading yet',
  rateLimitReading: (age: string): string => `Last rate-limit reading ${age}`,
  lastReading: (age: string, pct: number, window: string, resetPassed: boolean): string => `Last reading ${age}: ${pct}% of ${window}, ${resetPassed ? 'which has reset since' : 'not current'}`,
  plans: (label: string, groups: string): string => `${label}${groups === '' ? '' : `: ${groups}`}.`,
  onePlan: 'One command',
  manyPlans: 'commands',
  drag: 'Drag a card to put it where you want it; Sessions follows.',
  standing: { ready: 'ready', quota: 'out of quota', 'signed-out': 'needs a sign-in or a key', off: 'switched off', other: 'in need of a look' },
} as const;
