// What the Teams pages say. Copy lives in modules like this one, never inline in a component.
import { countWord, fmtInt } from './format';

export const M = {
  back: 'Teams',
  reading: 'Reading the team.',
  gone: 'No such team.',
  goneWhy: 'It may have been renamed, or this splice does not know it.',
  edit: 'Edit the team',
  newTeam: 'New team',
  openTeam: 'Open the team',
  archive: 'Archive',
  restore: 'Restore',
  archived: 'Archived',
  ledeSeats: (working: number, seats: number, open: number) => {
    if (open === seats) return seats === 1 ? 'The one seat is open.' : `All ${countWord(seats).toLowerCase()} seats are open.`;
    const set = working === 0
      ? 'No working session is listed'
      : `${countWord(working)} working ${working === 1 ? 'session is' : 'sessions are'} listed`;
    return open === 0 ? `${set}.` : `${set}; ${open === 1 ? 'one seat is' : `${countWord(open).toLowerCase()} seats are`} open.`;
  },
  noGoal: 'No goal written.',
  seatsTitle: 'Seats',
  seatsWhy: 'Each seat has a role, a command and standing instructions; a session sits in it.',
  lead: 'Lead',
  openSeat: 'Not listed',
  nobody: 'No session is listed for this seat',
  openSession: 'Open the session',
  noInstructions: 'No standing instructions.',
  noTurns: 'No turns are listed for this seat',
  turns: (n: number) => `${n} ${n === 1 ? 'turn' : 'turns'}`,
  lastFinished: 'last turn finished',
  lastFailed: 'last turn failed',
  cost: (usd: string): string => `API est. ${usd}`,
  costLowerBound: (usd: string): string => `API est. at least ${usd}`,
  unreportedUsage: (n: number) => `${fmtInt(n)} ${n === 1 ? 'turn has an incomplete or missing usage report' : 'turns have incomplete or missing usage reports'}, so these totals include only reported usage and are lower bounds.`,
  talkTitle: 'Message requests',
  talkWhy: 'Recorded message requests, newest first. Delivery is not confirmed here.',
  talkNone: 'No message requests are recorded for this day.',
  doneTitle: 'What they did',
  doneWhy: 'Recorded activity samples. Not every turn produces one.',
  doneNone: 'Nothing was sampled.',
  earlier: 'Earlier',
  later: 'Later',
  today: 'Today',
  dayLabel: 'Day',
  to: 'to',
  anotherSession: 'Another session',
  textMissing: 'The message text is not available.',
  economicsUnattributed: (n: number) => `${n} ${n === 1 ? 'turn' : 'turns'} on these commands carry no session and are counted apart.`,
  compose: {
    newTitle: 'New team',
    editTitle: (name: string) => `Edit ${name}`,
    why: 'A team is a goal and the seats that work on it. Archiving never deletes it.',
    name: 'Name',
    goal: 'Goal',
    features: 'Features',
    featuresHint: 'One per line.',
    repo: 'Repository',
    repoHint: 'The repository the team works in.',
    chooseRepo: 'Choose a repository',
    repoFolder: 'Show or change the folder',
    folderLocation: 'Folder location',
    seats: 'Seats',
    role: 'Role',
    plan: 'Command',
    choosePlan: 'Choose a command',
    instructions: 'Standing instructions',
    instructionsHint: 'Added to the seat’s system prompt.',
    session: 'Session',
    sessionNone: 'Open seat',
    leadSeat: 'Lead',
    makeLead: 'Make lead',
    removeSeat: 'Remove seat',
    addSeat: 'Add a seat',
    save: 'Save the team',
    saving: 'Saving…',
    cancel: 'Cancel',
    failed: 'That did not save:',
    noName: 'Give the team a name.',
    noRepo: 'Say which repository it works in.',
    noSeat: 'Add at least one seat.',
    oneLead: 'Exactly one seat leads.',
    noRole: 'needs a role',
    noPlan: 'needs a command',
    onTwo: 'is in two seats',
    seat: (n: number) => `Seat ${n}`,
  },
} as const;
