// What the version and upgrade rows say. Copy lives in modules like this one, never inline in a component.
import type { UpgradeRunState } from '../types/doctor';

export const U = {
  title: 'splice version',
  running: (installed: string): string => `Running ${installed}.`,
  newest: (latest: string): string => ` The newest release is ${latest}.`,
  nothingNewer: ' There is no newer release.',
  neverLooked: ' splice has not checked for a newer release.',
  verdict: { unknown: 'Not checked', current: 'Up to date', behind: 'Behind' },
  release: 'Release',
  latest: 'Latest',
  upgrade: 'Upgrade',
  upgradeNote: 'Leave the release blank for the latest one.',
  upgradeTitle: (release: string): string => `Upgrade to ${release}?`,
  upgradeWhy: 'splice downloads the release and restarts. Every command restarts with it, and a turn under way is cut and retried.',
  rollback: 'Roll back',
  rollbackTitle: (release: string): string => `Go back to ${release}?`,
  rollbackWhy: 'splice returns to the previous release and restarts. Every command restarts with it.',
  cancel: 'Cancel',
  none: 'None',
  run: 'The upgrade',
  output: 'What it printed',
  state: { running: 'Running', succeeded: 'Finished', failed: 'Failed', lost: 'Lost' } as Readonly<Record<UpgradeRunState, string>>,
  exit: (code: number): string => `Exit ${code}`,
  away: 'splice is restarting. The upgrade is read again once it answers.',
  reload: 'Reload this page to get the console the new release serves.',
  lost: 'The shell running it is gone, and it left no exit code.',
  quiet: 'It has printed nothing yet.',
  unserved: 'This splice cannot upgrade itself from here.',
} as const;
