// What the Teams pages say. Copy lives in modules like this one, never inline in a component.
export const M = {
  back: 'Sessions',
  reading: 'Reading the team.',
  gone: 'No such team.',
  goneWhy: 'It may have been renamed, or this splice does not know it.',
  edit: 'Edit the team',
  newTeam: 'New team',
  openTeam: 'Open the team',
  archive: 'Archive',
  restore: 'Restore',
  archived: 'Archived',
  ledeSeats: (working: number, seats: number, open: number) => {
    const set = `${working === seats ? 'All' : working === 0 ? 'None' : working} of ${seats} ${seats === 1 ? 'seat is' : 'seats are'} working`;
    return open === 0 ? `${set}.` : `${set}; ${open === 1 ? 'one seat is' : `${open} seats are`} open.`;
  },
  noGoal: 'No goal written.',
  seatsTitle: 'Seats',
  seatsWhy: 'Each seat has a role, a plan and standing instructions; a session sits in it.',
  lead: 'Lead',
  openSeat: 'Open seat',
  nobody: 'Nobody is in this seat',
  noInstructions: 'No standing instructions.',
  noTurns: 'No turns yet',
  turns: (n: number) => `${n} ${n === 1 ? 'turn' : 'turns'}`,
  checksPass: 'checks passing',
  checksFail: 'checks failing',
  talkTitle: 'Talked',
  talkWhy: 'What the seats sent each other, newest first.',
  talkNone: 'The seats sent each other nothing.',
  doneTitle: 'What they did',
  doneWhy: 'One line about every half minute while a seat works.',
  doneNone: 'Nothing was sampled.',
  earlier: 'Earlier',
  later: 'Later',
  today: 'Today',
  dayLabel: 'Day',
  to: 'to',
  textMissing: 'The message text is not available.',
  economicsUnattributed: (n: number) => `${n} ${n === 1 ? 'turn' : 'turns'} on these plans carry no session and are counted apart.`,
  compose: {
    newTitle: 'New team',
    editTitle: (name: string) => `Edit ${name}`,
    why: 'A team is a goal and the seats that work on it. Archiving never deletes it.',
    name: 'Name',
    goal: 'Goal',
    features: 'Features',
    featuresHint: 'One per line.',
    repo: 'Repository',
    repoHint: 'The git root the team works in.',
    seats: 'Seats',
    role: 'Role',
    plan: 'Plan',
    choosePlan: 'Choose a plan',
    instructions: 'Standing instructions',
    instructionsHint: 'Added to the seat’s system prompt.',
    session: 'Session',
    sessionNone: 'Open seat',
    leadSeat: 'Lead',
    makeLead: 'Make lead',
    removeSeat: 'Remove seat',
    addSeat: 'Add a seat',
    save: 'Save the team',
    saving: 'Saving…',
    cancel: 'Cancel',
    failed: 'That did not save:',
    noName: 'Give the team a name.',
    noRepo: 'Say which repository it works in.',
    noSeat: 'Add at least one seat.',
    oneLead: 'Exactly one seat leads.',
    noRole: 'needs a role',
    noPlan: 'needs a plan',
    onTwo: 'is in two seats',
    seat: (n: number) => `Seat ${n}`,
  },
} as const;
