// What the Claude command row says. Copy lives in modules like this one, never inline in a component.
export const C = {
  title: 'The claude command',
  separate: 'Separate',
  wrapped: 'Wrapped',
  separateWhy: 'splice leaves claude on your PATH alone. Its own command shares your ~/.claude setup and sessions by default.',
  wrappedWhy: 'splice runs claude through itself. The claude command on your PATH is its launcher, and your ~/.claude is left as it is; unwrapping puts the command back.',
  onPath: 'claude on your PATH',
  notFound: 'Nothing named claude',
  shim: 'The splice shim',
  realBinary: 'It runs',
  unknown: 'Not read',
  logins: 'Claude logins',
  noLogins: 'None stored',
  selected: 'Launches with',
  noneSelected: 'None chosen',
  backups: 'Backed up to',
  wrap: 'Wrap',
  wrapTitle: 'Wrap the claude command?',
  wrapWhy: 'splice puts its launcher in place of the claude command on your PATH and writes nothing into ~/.claude. When Claude Code updates itself, splice puts the launcher back.',
  unwrap: 'Unwrap',
  unwrapTitle: 'Unwrap the claude command?',
  unwrapWhy: 'splice puts back the claude command it replaced.',
  cancel: 'Cancel',
  reading: 'Reading the claude command.',
} as const;
