// What a session card's activity line says. Copy lives in modules like this one, never inline in logic.
export const SW = {
  waiting: 'Waiting for your answer',
  waitingFor: (span: string): string => `Waiting for your answer for ${span}`,
  stuck: 'Quiet for a while',
  stuckFor: (span: string): string => `Quiet for ${span}`,
  toolQuiet: (span: string): string => `Running a tool, quiet for ${span}`,
  working: 'Working',
  workingFor: (span: string): string => `Working for ${span}`,
  idle: 'Waiting for your next message',
  idleFor: (span: string): string => `Idle for ${span}, waiting for your next message`,
  gone: 'The session ended',
  you: 'You',
  inRepoOn: (repo: string, day: string): string => `${repo} · ${day}`,
  aSessionIn: (repo: string): string => `a session in ${repo}`,
  aSession: 'a session',
  anEndedSession: 'an ended session',
  waitingNote: (span: string): string => `Waiting ${span}`,
  stuckNote: (span: string): string => `Quiet ${span}`,
  workingNote: (span: string): string => `Working ${span}`,
  idleNote: (span: string): string => `Idle ${span}`,
} as const;
