// What the Turns pages say. Copy lives in modules like this one, never inline in a component.
import type { PerfWindowLabel } from '../types/perf';

/** What a turn's longest stage was doing, said as a phrase that ends a sentence. */
export const STAGE_PHRASE = {
  prepare: 'splice preparing the request',
  queue: 'waiting in line behind other turns',
  provider: 'the model thinking before its first word',
  stream: 'the answer arriving',
} as const;

export const T = {
  title: 'Turns',
  window: 'Window',
  windows: [['1h', '1 hour'], ['24h', '24 hours'], ['7d', '7 days']] as readonly (readonly [PerfWindowLabel, string])[],
  windowSpoken: { '1h': 'the last hour', '24h': 'the last 24 hours', '7d': 'the last 7 days' } as Record<PerfWindowLabel, string>,
  reading: 'Reading the turns.',
  runningTitle: 'Running now',
  working: 'Working',
  runningWhy: 'A turn stays here until its answer lands.',
  runningNone: 'Nothing is running.',
  runningQuiet: (n: number, quiet: string) => `${n === 1 ? 'One has' : `${n} have`} been quiet for ${quiet}.`,
  plansTitle: 'How each command is answering',
  plansWhy: 'The dark end of each bar is the typical first word; the pale end is the slowest twentieth.',
  plansNone: 'No command has answered a turn in this window.',
  colPlan: 'Command',
  colTurns: 'Turns',
  colFailed: 'Failed',
  colFirstWord: 'First word',
  typical: 'typical',
  slowest: 'slowest',
  cached: (pct: string) => `${pct} cached`,
  finishedTitle: 'Finished',
  finishedWhy: 'Open a turn to see where its time went, what was asked and what came back.',
  filterLabel: 'Show',
  filters: [['all', 'All'], ['failed', 'Failed'], ['compacted', 'Compacted']] as readonly (readonly ['all' | 'failed' | 'compacted', string])[],
  find: 'Find a turn',
  findHint: 'A session, command or model',
  none: 'No finished turn matches.',
  noneWhy: 'Turns land here as commands answer them.',
  servedLocallyLede: 'The model was not asked. splice answered this step itself, from a script the model had already written.',
  servedLocallyTag: 'Answered by splice',
  localLeftOut: (count: number) => `${count.toLocaleString('en-US')} ${count === 1 ? 'step' : 'steps'} splice answered itself, without asking the model, ${count === 1 ? 'is' : 'are'} left out of this list.`,
  shownOf: (shown: number, total: number) => `Showing the newest ${shown} of ${total}. Narrow the window or filter to see the rest.`,
  in: 'in',
  out: 'out',
  compacted: 'Compacted',
  notPriced: 'Not priced',
  runtimeRefused: (port: number) => `Couldn't reach its runtime on :${port}`,
  unreadTitle: 'Not read',
  unread: (head: string, why: string) => `${head}: ${why}`,
  clamped: (head: string) => `${head} has more turns in this window than the list holds; the oldest are cut.`,
  runningFor: (age: string) => `running ${age}`,
  quietFor: (quiet: string) => `No word from the model for ${quiet}; splice is keeping the turn open.`,
  connecting: 'Waiting for the model to answer',
  streaming: 'Streaming its answer',
  open: 'Open the turn',
} as const;

/** One turn's own page. */
export const P = {
  back: 'Turns',
  gone: 'This turn is no longer held.',
  goneWhy: 'The daemon keeps a window of turns; this one has aged out of it.',
  stagesTitle: 'Where the time went',
  stagesWhy: 'splice cannot say why the model was slow, only where the time sat.',
  stagesNone: 'This turn carries no timing.',
  stages: {
    prepare: ['Prepare', 'splice reading and shaping the request'],
    queue: ['Waiting in line', 'The command’s limit on turns at once'],
    provider: ['Model thinking', 'From sending to the first word back'],
    stream: ['Streaming', 'The answer arriving'],
  } as Record<'prepare' | 'queue' | 'provider' | 'stream', readonly [string, string]>,
  movedTitle: 'What it moved',
  readIn: 'Read in',
  readInWhy: (cached: string) => `${cached} of them came from the cache.`,
  readInPlain: 'Every token the model was asked to read.',
  writtenOut: 'Written out',
  writtenOutWhy: 'The answer, tools and thinking.',
  cost: 'API cost, estimated',
  costWhy: 'What this would cost at the model’s public prices.',
  costNone: 'This turn was not priced.',
  retries: 'Retries',
  retriesWhy: 'splice tried again before the first word came back.',
  openSession: 'Open the session',
  tabsLabel: 'What was kept of this turn',
  tabConversation: 'Conversation',
  tabRequest: 'Request and answer',
  tabSent: 'Sent to the model',
  readingConversation: 'Reading the conversation…',
  readingRequest: 'Reading the kept request and answer…',
  readingSent: 'Reading what was sent to the model…',
  conversationOff: 'The conversation is not shown.',
  conversationNoId: 'This turn carries no session, so its conversation cannot be found.',
  conversationEarlier: (n: number) => `${n} earlier ${n === 1 ? 'message' : 'messages'} not shown.`,
  asked: 'You asked',
  answered: (who: string) => `${who} answered`,
  system: 'splice',
  captureOff: (plan: string) => `Request capture is off for ${plan}, so this turn’s request and answer were not kept.`,
  captureSwitch: (plan: string, days: number | null): string => `Keep full requests and replies for ${plan} (${days === null ? '' : `${days} ${days === 1 ? 'day' : 'days'}, `}only you can read them)`,
  captureRecording: (plan: string) => `Recording bodies for ${plan}.`,
  captureWaits: (on: boolean) => `Restart to apply. Capture will be ${on ? 'on' : 'off'} after splice restarts.`,
  captureRefused: 'That did not work:',
  keptGone: 'This turn is no longer in the kept requests.',
  attempt: (n: number) => `Attempt ${n}`,
  sentRequest: 'Sent',
  received: 'Came back',
  truncated: 'Cut at the size limit.',
  bodyUnavailable: 'Body unavailable.',
  wireOff: 'Sent bodies are not kept for this command.',
  wireNone: 'No kept body matches this turn.',
  wireBody: 'What splice sent',
  close: 'Close',
} as const;

/** One word per tag the daemon can write, kept exhaustive against its Kotlin source by tests/outcome-words.test.ts. The reason in full is the
 *  turn page's failure sentence. */
export const OUTCOME_WORD: Readonly<Record<string, string>> = {
  client_abort: 'Stopped',
  empty_model: 'Empty answer',
  empty_compact: 'Empty answer',
  empty_message: 'Empty answer',
  'error:cancelled': 'Cancelled',
  'error:unexpected': 'Unexpected failure',
  'error:rate-limited': 'Rate limited',
  'error:plan-limit': 'Out of quota',
  'error:all-accounts-exhausted': 'Out of quota',
  'error:budget-blocked': 'Over budget',
  'error:auth-missing': 'Signed out',
  'error:upstream-failed': 'Provider failed',
  'error:upstream-frame-too-large': 'Answer too large',
  'error:conn-reset': 'Connection lost',
  'error:stopped': 'Stopped',
  'error:compaction-preflight-compactable': 'Too large to send',
  'error:compaction-preflight-first-exchange': 'First message too large',
  'error:compaction-preflight-compact-overflow': 'Too large to compact',
  'failure:invalid_request_error': 'Request rejected',
  'failure:authentication_error': 'Credentials rejected',
  'failure:permission_error': 'Not allowed',
  'failure:not_found_error': 'Not found',
  'failure:rate_limit_error': 'Rate limited',
  'failure:api_error': 'Provider failed',
  'failure:overloaded_error': 'Provider overloaded',
};
