// What the Usage page says. Copy lives in modules like this one, never inline in a component.
import { fmtInt } from './format';

/** A window in hours as a person says it. */
export const spanWords = (hours: number): string => (hours === 24 ? 'the last 24 hours' : hours === 168 ? 'the last 7 days' : `the last ${Math.round(hours / 24)} days`);

export const U = {
  title: 'Usage',
  requestScope: 'This page counts client requests only. Playground sends are not counted on this page.',
  reading: 'Reading the usage.',
  readingMetric: 'Reading…',
  readingRequests: 'Reading requests…',
  requestsUnavailable: 'Request history unavailable',
  countNotReported: 'The request count was not reported.',
  historyUnreadable: 'The daemon returned an unreadable request history.',
  commandsReading: (names: string) => `Still reading requests for ${names}.`,
  window: 'Window',
  notRetained: (asked: string, shown: string) => `The full range of ${asked} is not retained. Showing ${shown}.`,
  totalsTurns: 'Requests',
  totalsTurnsWhy: (commands: number, span: string, incomplete = false) => `${incomplete ? 'Across at least' : 'Across'} ${commands} ${commands === 1 ? 'command' : 'commands'} with requests in ${span}.`,
  totalsTurnsReading: 'Reading which commands had requests…',
  totalsIn: 'Tokens read in',
  totalsInWhy: (cached: string) => `${cached} came from the cache.`,
  totalsInPlain: 'Everything the models were asked to read.',
  totalsOut: 'Tokens written out',
  totalsOutWhy: 'Answers, tools and thinking.',
  totalsCost: 'API cost, estimated',
  totalsCostWhy: 'Equivalent API cost at the declared model prices, not a subscription bill.',
  totalsCostNone: 'No dollar estimate is available for this window.',
  unpricedUncounted: (n: number) => `${fmtInt(n)} ${n === 1 ? 'request has' : 'requests have'} no token count, so ${n === 1 ? 'it' : 'they'} cannot be priced.`,
  unpricedPlan: (n: number) => `${fmtInt(n)} ${n === 1 ? 'request is' : 'requests are'} covered by a plan, so ${n === 1 ? 'it has' : 'they have'} no price.`,
  unpricedUndeclared: (n: number) => `${fmtInt(n)} ${n === 1 ? 'request has' : 'requests have'} no recorded price.`,
  unpricedUnknown: (n: number) => `${fmtInt(n)} ${n === 1 ? 'request has' : 'requests have'} no price.`,
  unpricedLocal: (n: number) => `${fmtInt(n)} ${n === 1 ? 'request ran its model' : 'requests ran their models'} on this computer, so ${n === 1 ? 'it has' : 'they have'} no provider price.`,
  unanswered: (n: number) => `${fmtInt(n)} ${n === 1 ? 'request failed' : 'requests failed'} without a recorded answer or token usage.`,
  cutRounds: (n: number) => `${fmtInt(n)} ${n === 1 ? 'reply' : 'replies'} stopped before ${n === 1 ? 'it' : 'they'} finished, so ${n === 1 ? 'its' : 'their'} tokens are not reported.`,
  plansTitle: 'Each command’s usage readings',
  plansWhy: 'These percentages can come from provider readings or a configured token-warning threshold. splice only marks a command out of quota when the provider refuses it.',
  shortWindow: 'Short window',
  longWindow: 'Longer window',
  plansNone: 'No command has reported its usage yet.',
  ofLimit: (pct: number, window?: string | null) => window == null ? `${pct}% on its reported reading` : `${pct}% on its ${window === '5h' ? 'short-window' : window === '7d' ? 'longer-window' : window} reading`,
  noLimit: 'No limit reported',
  rateLimitReading: (age: string): string => `Last rate-limit reading ${age}`,
  refused: 'Out of quota',
  resets: (when: string) => `resets ${when}`,
  paceLess: 'less than an hour left at this pace',
  paceHours: (n: number) => `about ${n} ${n === 1 ? 'hour' : 'hours'} left at this pace`,
  paceDays: (n: number) => `about ${n} ${n === 1 ? 'day' : 'days'} left at this pace`,
  idle: 'idle in this window',
  idlePlans: (names: string, span: string) => `No requests in ${span} on ${names}.`,
  readIn: 'tokens read in',
  cached: (pct: string) => `${pct} cached`,
  noCache: 'Cache share not reported',
  sparkLabel: 'Tokens per hour, last 24 hours',
  hourlyUnreported: (n: number) => `${fmtInt(n)} ${n === 1 ? 'turn has an incomplete or missing usage report' : 'turns have incomplete or missing usage reports'}, so these totals include only reported usage and are lower bounds.`,
  paceLowerBound: 'Recorded usage pace is a lower bound because usage was not reported for every turn.',
  budgetsTitle: 'Budgets',
  budgetsWhy: 'A budget is your own daily ceiling in dollars. splice tells you, or stops the turn, when a command reaches it.',
  budgetResets: (when: string) => `Daily budgets reset at ${when}.`,
  budgetsPending: 'This splice does not serve budgets yet.',
  budgetsUnreadable: (why: string) => `Budgets could not be read, so every command runs with none: ${why}`,
  budgetSet: (usd: string, spent: string, action: 'warn' | 'block') => `${usd} a day. ${spent} spent in its daily budget window. ${action === 'block' ? 'splice stops turns once it is reached.' : 'splice tells you once it is reached.'}`,
  budgetLeft: (remaining: string) => `${remaining} left in its daily budget window.`,
  budgetReading: "Reading today's spending.",
  budgetNone: 'No command has a budget.',
  budgetAdd: 'Add a budget',
  budgetPlan: 'Command',
  budgetChange: 'Change',
  budgetDialog: (plan: string) => `Budget for ${plan}`,
  budgetDialogWhy: 'Dollars a day, counted at this command’s declared token prices.',
  budgetChoose: 'Choose a command to check whether its spending can be counted.',
  budgetDollars: 'Dollars a day',
  budgetAction: 'When it is reached',
  budgetWarn: 'Tell me',
  budgetWarnHint: 'The turn still runs.',
  budgetBlock: 'Stop the turn',
  budgetBlockHint: 'New turns are refused until the daily reset shown above.',
  budgetSave: 'Save',
  budgetRemove: 'Remove the budget',
  budgetCancel: 'Cancel',
  budgetFailed: 'That did not save:',
  alertsTitle: 'Alerts',
  alertsWhy: 'Where splice sends a message when a command nears a usage limit or reaches its budget.',
  alertsPending: 'This splice does not serve alerts yet.',
  alertWebhook: 'Webhook',
  alertWebhookWhy: 'A URL splice posts to.',
  alertWebhookNone: 'None set',
  alertWebhookSave: 'Save the webhook',
  alertTest: 'Send a test',
  alertTestWhy: 'Posts to the saved webhook and tells you what it said.',
  alertTestNeeds: 'Save a webhook first.',
  alertTestSent: 'Sent.',
  alertFailed: 'That did not work:',
  on: 'On',
  off: 'Off',
} as const;
