// What the Requests pages say. Copy lives in modules like this one, never inline in a component.
import type { PerfWindowLabel } from '../types/perf';

/** What a turn's longest stage was doing, said as a phrase that ends a sentence. */
export const STAGE_PHRASE = {
  prepare: 'splice preparing the request',
  queue: 'waiting in line behind other requests',
  provider: 'the model thinking before its first word',
  stream: 'the answer arriving',
  wait: 'time after the last recorded activity',
} as const;

/** The older daemon sentence, recognized only to render retained restart history in current words. */
export const LEGACY_RESTART_SENTENCE = 'splice restarted while this request was running; retry the request';

export const T = {
  title: 'Requests',
  window: 'Window',
  windows: [['1h', '1 hour'], ['24h', '24 hours'], ['7d', '7 days']] as readonly (readonly [PerfWindowLabel, string])[],
  windowSpoken: { '1h': 'the last hour', '24h': 'the last 24 hours', '7d': 'the last 7 days' } as Record<PerfWindowLabel, string>,
  reading: 'Reading the requests.',
  runningTitle: 'Running now',
  working: 'Working',
  runningWhy: 'A request stays here until its answer lands.',
  runningNone: 'Nothing is running.',
  stopUnavailable: 'This request cannot be matched to a live turn, so Stop is unavailable.',
  runningQuiet: (n: number, quiet: string) => `${n === 1 ? 'One has' : `${n} have`} been quiet for ${quiet}.`,
  plansTitle: 'How each command is answering',
  plansWhy: 'The dark end of each bar is the typical first word; the pale end is the slowest twentieth.',
  plansNone: 'No command has answered a request in this window.',
  colPlan: 'Command',
  colTurns: 'Requests',
  colFailed: 'Failed',
  colFirstWord: 'First word',
  typical: 'typical',
  slowest: 'slowest',
  cached: (pct: string) => `${pct} cached`,
  finishedTitle: 'Finished',
  finishedWhy: 'Open a request to see where its time went, what was asked and what came back.',
  filterLabel: 'Show',
  filters: [['all', 'All'], ['failed', 'Failed'], ['stopped', 'Stopped'], ['compacted', 'Compaction']] as readonly (readonly ['all' | 'failed' | 'stopped' | 'compacted', string])[],
  none: 'No finished request matches.',
  noneWhy: 'Requests land here as commands answer them.',
  matching: (count: number) => `${count.toLocaleString('en-US')} ${count === 1 ? 'request matches' : 'requests match'}.`,
  narrowedLabel: 'Showing only',
  selector: { head: 'Command', model: 'Model', account: 'Account', session: 'Session' } as Record<'head' | 'model' | 'account' | 'session', string>,
  unattributed: { model: 'No model recorded', account: 'No account recorded' } as Record<'model' | 'account', string>,
  widen: (what: string) => `Show requests beyond ${what}`,
  sameSession: 'Same session',
  linkUnread: (param: string, value: string) => (value === '' ? `This link has no ${param}, so the requests it means cannot be found.` : `This link's ${param}, "${value}", is not one this page can read.`),
  spanLede: (count: number | null, range: string) => (count === null ? `Requests ${range}.` : count === 0 ? `No requests ${range}.` : `${count.toLocaleString('en-US')} ${count === 1 ? 'request' : 'requests'} ${range}.`),
  onDay: (day: string) => `on ${day}`,
  between: (from: string, to: string) => `from ${from} to ${to}`,
  sinceTime: (from: string) => `since ${from}`,
  failedOf: (count: number, command: string) => `${count.toLocaleString('en-US')} failed requests on ${command}`,
  emptyAnswerLede: 'The session received an empty answer from the model, which ended its reply with no text and no tool call.',
  emptyAnswerThinking: 'The model reported thinking tokens.',
  servedLocallyLede: 'This step sent no request to the model. Splice answered from the existing script, so its input and output token counts are zero.',
  servedLocallyTag: 'Answered by splice',
  localLeftOut: (count: number) => `${count.toLocaleString('en-US')} ${count === 1 ? 'step' : 'steps'} splice answered itself, without asking the model, ${count === 1 ? 'is' : 'are'} left out of this list.`,
  shownOf: (shown: number, total: number) => `Showing the newest ${shown.toLocaleString('en-US')} of ${total.toLocaleString('en-US')}. Narrow the window or filter to see the rest.`,
  in: 'in',
  out: 'out',
  compacted: 'Compaction',
  cacheHit: 'Cache hit',
  retried: 'Retried',
  switchedAccount: 'Switched account',
  notPriced: 'Not priced',
  runtimeRefused: (port: number) => `Couldn't reach its runtime on :${port}`,
  progressTimeout: (quiet: string) => `splice gave up after ${quiet} without progress from the provider. Retry the request.`,
  restarted: 'Splice restarted while this request was running. Retry the request.',
  unreadTitle: 'Not read',
  unread: (head: string, why: string) => `${head}: ${why}`,
  runningFor: (age: string) => `running ${age}`,
  quietFor: (quiet: string) => `No word from the model for ${quiet}; splice is keeping the request open.`,
  connecting: 'Waiting for the model to answer',
  streaming: 'Streaming its answer',
  open: 'Open the request',
} as const;

/** One request's own page. */
export const P = {
  back: 'Requests',
  gone: 'This request is no longer held.',
  goneWhy: 'The daemon keeps a window of requests; this one has aged out of it.',
  resumeWhy: 'To continue the session, copy a resume command and run it in your terminal.',
  stagesTitle: 'Where the time went',
  stagesWhy: 'splice cannot say why the model was slow, only where the time sat.',
  stagesNone: 'This request carries no timing.',
  stages: {
    prepare: ['Prepare', 'splice reading and shaping the request'],
    queue: ['Waiting in line', 'The command’s limit on requests at once'],
    provider: ['Model thinking', 'From sending to the first word back'],
    stream: ['Streaming', 'The answer arriving'],
    wait: ['Unrecorded time', 'From the last recorded activity until the request ended.'],
  } as Record<'prepare' | 'queue' | 'provider' | 'stream' | 'wait', readonly [string, string]>,
  movedTitle: 'What it moved',
  readIn: 'Read in',
  notReported: 'Not reported',
  tokenCountNotReported: 'No token count was reported for this request.',
  readInWhy: (cached: string) => `${cached} of them came from the cache.`,
  readInPlain: 'Every token the model was asked to read.',
  writtenOut: 'Written out',
  writtenOutWhy: 'The answer, tools and thinking.',
  writtenOutThinking: (count: string): string => `${count} of the written tokens were reported as thinking.`,
  cost: 'API cost, estimated',
  costWhy: 'Estimated at this command’s declared token prices.',
  costNone: 'This request was not priced.',
  costUnreported: 'The price is unknown because token counts were not reported.',
  retries: 'Retries',
  retriesWhy: 'splice tried again before the first word came back.',
  openSession: 'Open the session',
  tabsLabel: 'What was kept of this request',
  tabConversation: 'Conversation',
  tabRequest: 'Request and answer',
  tabSent: 'Sent to the model',
  readingConversation: 'Reading the conversation…',
  readingRequest: 'Reading the kept request and answer…',
  conversationOff: 'The conversation is not shown.',
  conversationNoId: 'This request carries no session, so its conversation cannot be found.',
  conversationNoReply: 'No response message was recorded for this request, so its conversation cannot be selected. Open the session to read its transcript.',
  readingFailure: 'Reading the recorded reason…',
  contentRefusal: 'The provider stopped the answer under its content check; ask for a different task',
  modelRefusal: 'The model declined to answer; ask for a different task',
  stoppedNoReason: 'This answer stopped before it completed. No detailed stop reason was kept.',
  failureNoReason: (outcome: string) => `This request ended: ${outcome}. No detailed failure reason was kept.`,
  conversationEarlier: (n: number) => `${n} earlier ${n === 1 ? 'message' : 'messages'} not shown.`,
  asked: 'You asked',
  answered: (who: string) => `${who} answered`,
  system: 'splice',
  captureOff: (plan: string) => `Request capture is off for ${plan}, so this request and its answer were not kept.`,
  captureSwitch: (plan: string, days: number | null): string => `Keep full requests and replies for ${plan} (${days === null ? '' : `${days} ${days === 1 ? 'day' : 'days'}, `}only you can read them)`,
  captureRecording: (plan: string) => `Recording bodies for ${plan}.`,
  captureWaits: (on: boolean) => `Restart to apply. Capture will be ${on ? 'on' : 'off'} after splice restarts.`,
  captureRefused: 'That did not work:',
  keptGone: 'This request is no longer in the kept requests.',
  attempt: (n: number) => `Attempt ${n}`,
  sentRequest: 'Sent',
  received: 'Came back',
  truncated: 'Cut at the size limit.',
  bodyUnavailable: 'Body unavailable.',
  wireNone: 'The sent record cannot be matched to this request.',
  close: 'Close',
} as const;

/** One word per tag the daemon can write, kept exhaustive against its Kotlin source by tests/outcome-words.test.ts. The reason in full is the
 *  turn page's failure sentence. */
export const OUTCOME_WORD: Readonly<Record<string, string>> = {
  client_abort: 'Stopped',
  empty_model: 'Empty answer',
  empty_compact: 'Empty answer',
  empty_message: 'Empty answer',
  'error:cancelled': 'Ended by splice',
  'error:restarted': 'Restarted by splice',
  'error:unexpected': 'Unexpected failure',
  'error:rate-limited': 'Rate limited',
  'error:plan-limit': 'Out of quota',
  'error:all-accounts-exhausted': 'Out of quota',
  'error:budget-blocked': 'Over budget',
  'error:auth-missing': 'Signed out',
  'error:upstream-failed': 'Provider failed',
  'error:upstream-frame-too-large': 'Answer too large',
  'error:conn-reset': 'Connection lost',
  'error:stopped': 'Stopped',
  'error:compaction-preflight-compactable': 'Too large to send',
  'error:compaction-preflight-first-exchange': 'First message too large',
  'error:compaction-preflight-compact-overflow': 'Too large to compact',
  'failure:invalid_request_error': 'Request rejected',
  'failure:authentication_error': 'Credentials rejected',
  'failure:permission_error': 'Not allowed',
  'failure:not_found_error': 'Not found',
  'failure:rate_limit_error': 'Rate limited',
  'failure:api_error': 'Provider failed',
  'failure:overloaded_error': 'Provider overloaded',
};
