// What the compaction block says. Copy lives in modules like this one, never inline in a component.
export const W = {
  title: 'Compaction',
  why: 'When a session’s context fills, its command writes a summary and carries on from it. This is how those went, and which instructions they ran under.',
  reading: 'Reading the compactions.',
  none: 'No compaction has run yet.',
  count: (total: number, week: boolean): string => `${total} ${total === 1 ? 'compaction' : 'compactions'}${week ? ' in the last 7 days' : ''}.`,
  noneFailed: 'None failed.',
  someFailed: (failed: number, share: string): string => `${failed} failed (${share}).`,
  outcomes: 'How they ended',
  recent: 'Recent',
  recentPlan: (plan: string): string => plan,
  took: 'Typical time',
  chars: 'Typical summary length',
  charsUnit: (n: string): string => `${n} characters`,
  rules: 'Instructions in effect',
  rulesNone: 'No rule is set, so Claude Code’s own instructions apply.',
  rulesWhy: 'The most specific rule that matches a session wins.',
  rulePlans: (plans: string): string => `On ${plans}.`,
  ruleChars: (n: number): string => `${n} characters`,
  ruleOptOut: 'Explicitly none.',
  ruleUnreadable: 'Its file cannot be read.',
  scope: { client: 'Claude Code’s own', global: 'Everywhere', model: 'For a model', project: 'For a project', 'project-model': 'For a project and model' },
  unread: (head: string, why: string): string => `${head}: ${why}`,
  outcome: {
    model_text: 'Summary written',
    model_thinking: 'Summary from reasoning',
    model_text_weak: 'Weak summary',
    tooled_no_text: 'Tool call instead',
    empty_model: 'Empty reply',
    stream_error: 'Stream failed',
    upstream_error: 'Provider error',
  },
} as const;
