// What the plan-card derivation says: each state's one line and its note. Copy lives in modules like this one, never inline in logic.
export const FL = {
  quotaNearlyUsed: 'Quota nearly used',
  atReportedLimit: 'At reported limit',
  warnReading: 'near its limit',
  criticalReading: 'almost at its reported limit',
  fullReading: 'at its reported limit',
  stopped: 'This command is not running.',
  unhealthy: 'Its health check is failing.',
  signedOut: 'Its next turn will fail until you sign in.',
  keyMissing: 'Its next turn will fail until its key is set.',
  loginExpired: 'Its login could not be refreshed, so its next turn will fail.',
  accountExcluded: 'The pool has set its selected account aside.',
  queueFull: 'Turns are waiting for a free slot.',
  restartNeeded: 'The configuration changed after this command started.',
  payPerToken: 'Pays per token; no window',
  noReading: 'No quota reading reported',
  notChecked: 'Not checked yet',
  readinessUnknown: 'No answer is recorded yet. Send a request to check the connection.',
  modelNotResponding: 'Model not responding',
  runtimeNotAnswering: 'The model on this computer is not responding.',
  accessRefused: 'The provider’s last answer refused access. Check the account’s access or plan.',
  rateRefused: 'The provider’s last answer was rate-limited. No new acceptance has been recorded.',
  providerRefused: 'The provider’s last answer was a refusal. No new acceptance has been recorded.',
  providerAnswer: (accepted: boolean, age: string): string =>
    `Last provider answer: ${accepted ? 'accepted' : 'refused'}, ${age}`,
  rateLimitReading: (age: string): string => `Last rate-limit reading ${age}`,
  lastReading: (age: string, pct: number, window: string, resetPassed: boolean): string => `Last reading ${age}: ${pct}% of ${window}, ${resetPassed ? 'which has reset since' : 'not current'}`,
  plans: (label: string, groups: string): string => `${label}${groups === '' ? '' : `: ${groups}`}.`,
  onePlan: 'One command',
  manyPlans: 'commands',
  drag: 'Drag a card to put it where you want it; Sessions follows.',
  standing: { ready: 'ready', limited: 'with high quota use', quota: 'out of quota', 'signed-out': 'needs a sign-in or a key', off: 'not available', other: 'in need of a look' },
} as const;
