#!/usr/bin/env bash
# tools/e2e/docker/plan-limit.sh — an Anthropic plan-limit 429, through splice, to the REAL Claude
# Code at the pinned version. Run INSIDE the container by `run.sh --scenario plan-limit`.
#
# Single-login native refusals reach Claude Code as HTTP 429 with unchanged body and rate-limit
# headers, with one upstream attempt and no proxy retries. That client runs in persistent retry
# mode (CLAUDE_CODE_RETRY_WATCHDOG=1), sleeps until the reset and resumes. A pooled refusal moves
# the same request to a free login before any client response.
# The upstream is mock_anthropic.ts: a five-hour plan-limit 429
# with the unified headers Claude Code reads, until its reset, then 200.
#
# Three heads on three mocks, so the evidence, the waiting turn and the pool do not share a clock:
#   planprobe  streamed and buffered native refusals, with exact wire and attempt checks
#              against the mock's recorded replies (plan_limit.ts probe);
#   planlimit  the real Claude Code in print mode, through the wrapper `install --all` linked;
#   planpool   the same real client completes on login two while login one is limited two hours out.
# Every upstream is a mock inside the container and the container has no network.
set -uo pipefail

RECEIPT_KIND="splice-plan-limit-e2e"
RECEIPT_LABEL="PLAN-LIMIT E2E"
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"
trap finish EXIT

PLAN_TS="$(dirname "${BASH_SOURCE[0]}")/plan_limit.ts"
PLAN_HEAD_PORT=3107
PROBE_HEAD_PORT=3108
POOL_HEAD_PORT=3109
POOL_MOCK_PORT=""
# Long enough that the turn meets the limit more than once (splice's retries, its hold, the client's
# own wait); short enough for CI. The probe's upstream never resets inside the run.
# The turn's upstream resets this long after the turn's first request: 90 s keeps CI short, and
# `run.sh --plan-reset-s 18000` asks the real question, whether the client outlasts a five-hour window.
PLAN_RESET_S="${PLAN_RESET_S:-90}"
PROBE_RESET_S=3600
# V4-233: once the upstream names its plan window spent, splice sends it nothing more until the reset:
# the turn's one request reaches the limited upstream, and every later one waits for the reset.
PLAN_UPSTREAM_MAX="${PLAN_UPSTREAM_MAX:-1}"
TURN_MOCK_PORT=""
PROBE_MOCK_PORT=""

echo "plan-limit e2e: user=$(id -un) home=$HOME artifacts=$ARTIFACTS"

step "Claude Code version matches the splice tested pin" client_version_receipt

# ── 1. two plan-limited Anthropic upstreams ─────────────────────────────────────────────────────
start_plan_mocks() {
  MOCK_ANTHROPIC_RESET_S=$PLAN_RESET_S MOCK_ANTHROPIC_LOG="$OUT/upstream-turn.jsonl" \
    nohup bun "$REPO/tools/e2e/docker/mock_anthropic.ts" 0 > "$OUT/mock_anthropic_turn.out" 2> "$OUT/mock_anthropic_turn.err" &
  echo $! > "$OUT/mock_anthropic_turn.pid"
  env ${PLAN_PROBE_MESSAGE:+"MOCK_ANTHROPIC_MESSAGE=$PLAN_PROBE_MESSAGE"} \
    MOCK_ANTHROPIC_RESET_S=$PROBE_RESET_S MOCK_ANTHROPIC_LOG="$OUT/upstream-probe.jsonl" \
    nohup bun "$REPO/tools/e2e/docker/mock_anthropic.ts" 0 > "$OUT/mock_anthropic_probe.out" 2> "$OUT/mock_anthropic_probe.err" &
  echo $! > "$OUT/mock_anthropic_probe.pid"
  MOCK_ANTHROPIC_POOLED=1 MOCK_ANTHROPIC_RESET_S=7200 MOCK_ANTHROPIC_LOG="$OUT/upstream-pool.jsonl" \
    nohup bun "$REPO/tools/e2e/docker/mock_anthropic.ts" 0 > "$OUT/mock_anthropic_pool.out" 2> "$OUT/mock_anthropic_pool.err" &
  echo $! > "$OUT/mock_anthropic_pool.pid"
  for _ in $(seq 1 50); do
    [ -s "$OUT/mock_anthropic_turn.out" ] && [ -s "$OUT/mock_anthropic_probe.out" ] && [ -s "$OUT/mock_anthropic_pool.out" ] && break
    sleep 0.2
  done
  [ -s "$OUT/mock_anthropic_turn.out" ] || { echo "turn mock did not start: $(cat "$OUT/mock_anthropic_turn.err")"; return 1; }
  [ -s "$OUT/mock_anthropic_probe.out" ] || { echo "probe mock did not start: $(cat "$OUT/mock_anthropic_probe.err")"; return 1; }
  [ -s "$OUT/mock_anthropic_pool.out" ] || { echo "pool mock did not start"; return 1; }
  cat "$OUT/mock_anthropic_turn.out" "$OUT/mock_anthropic_probe.out" "$OUT/mock_anthropic_pool.out"
}
step "plan-limited Anthropic mocks up" start_plan_mocks
TURN_MOCK_PORT="$(mock_field mock_anthropic_turn.out port 2>/dev/null)"
PROBE_MOCK_PORT="$(mock_field mock_anthropic_probe.out port 2>/dev/null)"
POOL_MOCK_PORT="$(mock_field mock_anthropic_pool.out port 2>/dev/null)"

# ── 2. topology: two claude-splice-shaped heads (anthropic-passthrough, the client's own login) ───
write_plan_topology() {
  mkdir -p "$HOME/.config/splice"
  cat > "$HOME/.config/splice/splice.toml" <<EOF
# plan-limit e2e topology — generated by tools/e2e/docker/plan-limit.sh
[daemon]
control_port = $CONTROL_PORT

[providers.anthro]
dialect = "anthropic-passthrough"
base_url = "http://127.0.0.1:$TURN_MOCK_PORT"
auth = { kind = "client" }
extra_headers = { anthropic-version = "2023-06-01" }
[[providers.anthro.models]]
id = "claude-sonnet-5"
label = "Claude Sonnet 5 (mock)"
context_window = 200000

[providers.anthroprobe]
dialect = "anthropic-passthrough"
base_url = "http://127.0.0.1:$PROBE_MOCK_PORT"
auth = { kind = "client" }
extra_headers = { anthropic-version = "2023-06-01" }
[[providers.anthroprobe.models]]
id = "claude-sonnet-5"
label = "Claude Sonnet 5 (mock)"
context_window = 200000

[providers.anthropool]
dialect = "anthropic-passthrough"
base_url = "http://127.0.0.1:$POOL_MOCK_PORT"
auth = { kind = "client" }
extra_headers = { anthropic-version = "2023-06-01" }
[[providers.anthropool.models]]
id = "claude-sonnet-5"
label = "Claude Sonnet 5 (mock)"
context_window = 200000

[heads.planpool]
provider = "anthropool"
port = $POOL_HEAD_PORT
discovery_prefix = "claude-planpool--"
pinned_model = "claude-sonnet-5"
[heads.planpool.claude]
command = "claude-planpool"

[heads.planlimit]
provider = "anthro"
port = $PLAN_HEAD_PORT
discovery_prefix = "claude-planlimit--"
pinned_model = "claude-sonnet-5"
[heads.planlimit.claude]
command = "claude-planlimit"

[heads.planprobe]
provider = "anthroprobe"
port = $PROBE_HEAD_PORT
discovery_prefix = "claude-planprobe--"
pinned_model = "claude-sonnet-5"
[heads.planprobe.claude]
command = "claude-planprobe"
EOF
  cat "$HOME/.config/splice/splice.toml"
}
step "topology written" write_plan_topology

# ── 3. install and cold start, as a user would ─────────────────────────────────────────────────
install_plan() {
  { [ -f "$ARTIFACTS/splice.jar" ] && [ -f "$ARTIFACTS/splice-launch" ]; } || { echo "no artifacts in $ARTIFACTS"; return 1; }
  local installer="$REPO/install.sh"
  [ -f "$ARTIFACTS/install.sh" ] && installer="$ARTIFACTS/install.sh"
  SPLICE_JAR="$ARTIFACTS/splice.jar" SPLICE_SHIM="$ARTIFACTS/splice-launch" bash "$installer" </dev/null || return 1
  [ -x "$HOME/.local/bin/claude-planlimit" ] || { echo "claude-planlimit wrapper not linked"; return 1; }
  splice version
}
step "install.sh from artifacts: claude-planlimit linked" install_plan

# Full synthetic Claude sign-in, private from its first byte. The caller is the first login;
# one splice-owned folder adds exactly one other login. Future expiry prevents refresh traffic.
pool_login() {
  local folder
  folder="$(resolve_state_dir)/claude-accounts/planpool/two"
  ( umask 077
    mkdir -p "$folder" || exit 1
    chmod 0700 "$folder" || exit 1
    printf '%s\n' '{"claudeAiOauth":{"accessToken":"synthetic-two","refreshToken":"synthetic-refresh","expiresAt":4102444800000,"scopes":["user:inference","user:profile"]}}' > "$folder/.credentials.json"
    printf '%s\n' '{"oauthAccount":{"accountUuid":"00000000-0000-0000-0000-000000000002","emailAddress":"synthetic@example.invalid"}}' > "$folder/.claude.json"
  )
}
step "two synthetic sign-ins: caller and one private account folder" pool_login

plan_cold_start() {
  splice restart </dev/null || return 1
  wait_health 60 || return 1
  ss -ltn | grep -E ":($PLAN_HEAD_PORT|$PROBE_HEAD_PORT) " || { echo "head ports not listening"; return 1; }
}
step "daemon cold start: both heads ready" plan_cold_start

# The launch recipe is where persistent retry is planted; without it the client stops after its
# default retries and the rest of this scenario would be measuring something else. It carries the
# turn key too, so it lives in lib.sh's 0700 $PRIVATE, 0600 from its first byte, never under $OUT,
# which run.sh copies into the receipts and e2e-docker.yml uploads (V4-311).
PLAN_RECIPE="$PRIVATE/recipe-planlimit.json"
plan_recipe() {
  mkdir -p "$PRIVATE" && chmod 0700 "$PRIVATE" || return 1
  ( umask 077
    curl_mgmt -X POST -H 'Content-Type: application/json' \
      --data '{"dangerouslySkipPermissions":"","args":[]}' "http://127.0.0.1:$CONTROL_PORT/launch/planlimit" \
      > "$PLAN_RECIPE" ) || return 1
  grep -o '"CLAUDE_CODE_RETRY_WATCHDOG":"[^"]*"' "$PLAN_RECIPE" || { echo "no CLAUDE_CODE_RETRY_WATCHDOG in the recipe"; return 1; }
  grep -q '"CLAUDE_CODE_RETRY_WATCHDOG":"1"' "$PLAN_RECIPE" || { echo "persistent retry is not planted"; return 1; }
}
step "launch recipe: persistent retry planted" plan_recipe

# The same real-client request must move to the folder login before it hears any native refusal.
# Bound a red at 25 s; the first login resets two hours out, so sleeping is never mistaken for success.
pool_turn() {
  local rc started ended
  started=$(date +%s%3N)
  ANTHROPIC_AUTH_TOKEN=synthetic-one ANTHROPIC_API_KEY="" DISABLE_AUTOUPDATER=1 DISABLE_TELEMETRY=1 \
    DISABLE_ERROR_REPORTING=1 CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC=1 \
    timeout 25 claude-planpool -p "Say hello." --output-format stream-json --verbose </dev/null \
    > "$OUT/pool-client.jsonl" 2> "$OUT/pool-client.err"
  rc=$?
  ended=$(date +%s%3N)
  mkdir -p "$OUT/pool-transcripts"
  find -L "$HOME/.claude-planpool/projects" -name '*.jsonl' -exec cp {} "$OUT/pool-transcripts/" \; 2>/dev/null
  bun "$PLAN_TS" pooled "$OUT/upstream-pool.jsonl" "$OUT/pool-client.jsonl" "$OUT/pool-transcripts" "$started" "$ended" "$rc"
}
step "real Claude Code: same request completes on the next login without hearing 429" pool_turn

# ── 4. native HTTP 429: unchanged wire, one attempt, local follower, bounded re-probe ───────────
step "native 429: verbatim headers and body, one attempt without proxy retries" \
  bun "$PLAN_TS" probe "$PROBE_HEAD_PORT" "$OUT/first-frame.json" "$OUT/upstream-probe.jsonl"

# ── 5. the real client sleeps through the limit and resumes after the reset ─────────────────────
plan_turn() {
  local out rc
  out="$(ANTHROPIC_API_KEY=mock-key DISABLE_AUTOUPDATER=1 DISABLE_TELEMETRY=1 DISABLE_ERROR_REPORTING=1 \
    CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC=1 \
    timeout $((PLAN_RESET_S + 390)) claude-planlimit -p "Say hello." --output-format text </dev/null 2>&1)"
  rc=$?
  date +%s%3N > "$OUT/turn-end-ms"
  printf '%s\n' "$out" | tail -c 1500
  [ $rc -eq 0 ] || { echo "claude-planlimit exit $rc"; return 1; }
  grep -qF "resumed after the reset" <<<"$out" || { echo "the turn's output lacks the upstream's post-reset reply"; return 1; }
}
step "real Claude Code: the turn waits out the plan limit and completes" plan_turn
step "the turn ended after the upstream's reset" bun "$PLAN_TS" resumed "$OUT/upstream-turn.jsonl" "$(cat "$OUT/turn-end-ms" 2>/dev/null || echo 0)"
step "upstream timeline while at its limit: at most $PLAN_UPSTREAM_MAX request before the reset" \
  bun "$PLAN_TS" upstream "$OUT/upstream-turn.jsonl" "$PLAN_UPSTREAM_MAX"

# The client's own record of what it was told: its transcripts, wherever the head's config dir put them.
keep_transcripts() {
  mkdir -p "$OUT/claude-transcripts"
  find "$HOME" -path '*/projects/*.jsonl' -newer "$PLAN_RECIPE" -exec cp {} "$OUT/claude-transcripts/" \; 2>/dev/null
  ls -l "$OUT/claude-transcripts"
}
step "Claude Code transcripts kept" keep_transcripts
