#!/usr/bin/env bash
# tools/e2e/docker/plan-limit.sh — an Anthropic plan-limit 429, through splice, to the REAL Claude
# Code at the pinned version. Run INSIDE the container by `run.sh --scenario plan-limit`.
#
# The claim under test is CHANGELOG 0.4.0 (V4-71, V4-72, V4-73): the first turn to meet a persistent
# 429 reaches Claude Code as the one in-band error it retries (`overloaded_error`, rate-limit words
# kept); every launched client runs in persistent retry mode (CLAUDE_CODE_RETRY_WATCHDOG=1); and it
# sleeps until the reset and resumes. The upstream is mock_anthropic.ts: a five-hour plan-limit 429
# with the unified headers Claude Code reads, until its reset, then 200.
#
# Two heads on two mocks, so the evidence and the turn never share a clock:
#   planprobe  a raw streaming turn, recorded whole: the FIRST relabelled frame a client gets, then
#              the refusal its immediate retry gets (plan_limit.ts probe);
#   planlimit  the real Claude Code in print mode, through the wrapper `install --all` linked.
# Every upstream is a mock inside the container and the container has no network.
set -uo pipefail

RECEIPT_KIND="splice-plan-limit-e2e"
RECEIPT_LABEL="PLAN-LIMIT E2E"
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"
trap finish EXIT

PLAN_TS="$(dirname "${BASH_SOURCE[0]}")/plan_limit.ts"
PLAN_HEAD_PORT=3107
PROBE_HEAD_PORT=3108
# Long enough that the turn meets the limit more than once (splice's retries, its hold, the client's
# own wait); short enough for CI. The probe's upstream never resets inside the run.
PLAN_RESET_S=90
PROBE_RESET_S=3600
TURN_MOCK_PORT=""
PROBE_MOCK_PORT=""

echo "plan-limit e2e: user=$(id -un) home=$HOME artifacts=$ARTIFACTS"

step "Claude Code version matches the splice tested pin" client_version_receipt

# ── 1. two plan-limited Anthropic upstreams ─────────────────────────────────────────────────────
start_plan_mocks() {
  MOCK_ANTHROPIC_RESET_S=$PLAN_RESET_S MOCK_ANTHROPIC_LOG="$OUT/upstream-turn.jsonl" \
    nohup bun "$REPO/tools/e2e/docker/mock_anthropic.ts" 0 > "$OUT/mock_anthropic_turn.out" 2> "$OUT/mock_anthropic_turn.err" &
  echo $! > "$OUT/mock_anthropic_turn.pid"
  MOCK_ANTHROPIC_RESET_S=$PROBE_RESET_S MOCK_ANTHROPIC_LOG="$OUT/upstream-probe.jsonl" \
    nohup bun "$REPO/tools/e2e/docker/mock_anthropic.ts" 0 > "$OUT/mock_anthropic_probe.out" 2> "$OUT/mock_anthropic_probe.err" &
  echo $! > "$OUT/mock_anthropic_probe.pid"
  for _ in $(seq 1 50); do
    [ -s "$OUT/mock_anthropic_turn.out" ] && [ -s "$OUT/mock_anthropic_probe.out" ] && break
    sleep 0.2
  done
  [ -s "$OUT/mock_anthropic_turn.out" ] || { echo "turn mock did not start: $(cat "$OUT/mock_anthropic_turn.err")"; return 1; }
  [ -s "$OUT/mock_anthropic_probe.out" ] || { echo "probe mock did not start: $(cat "$OUT/mock_anthropic_probe.err")"; return 1; }
  cat "$OUT/mock_anthropic_turn.out" "$OUT/mock_anthropic_probe.out"
}
step "plan-limited Anthropic mocks up" start_plan_mocks
TURN_MOCK_PORT="$(mock_field mock_anthropic_turn.out port 2>/dev/null)"
PROBE_MOCK_PORT="$(mock_field mock_anthropic_probe.out port 2>/dev/null)"

# ── 2. topology: two claude-splice-shaped heads (anthropic-passthrough, the client's own login) ───
write_plan_topology() {
  mkdir -p "$HOME/.config/splice"
  cat > "$HOME/.config/splice/splice.toml" <<EOF
# plan-limit e2e topology — generated by tools/e2e/docker/plan-limit.sh
[daemon]
control_port = $CONTROL_PORT

[providers.anthro]
dialect = "anthropic-passthrough"
base_url = "http://127.0.0.1:$TURN_MOCK_PORT"
auth = { kind = "client" }
extra_headers = { anthropic-version = "2023-06-01" }
[[providers.anthro.models]]
id = "claude-sonnet-5"
label = "Claude Sonnet 5 (mock)"
context_window = 200000

[providers.anthroprobe]
dialect = "anthropic-passthrough"
base_url = "http://127.0.0.1:$PROBE_MOCK_PORT"
auth = { kind = "client" }
extra_headers = { anthropic-version = "2023-06-01" }
[[providers.anthroprobe.models]]
id = "claude-sonnet-5"
label = "Claude Sonnet 5 (mock)"
context_window = 200000

[heads.planlimit]
provider = "anthro"
port = $PLAN_HEAD_PORT
discovery_prefix = "claude-planlimit--"
pinned_model = "claude-sonnet-5"
[heads.planlimit.claude]
command = "claude-planlimit"

[heads.planprobe]
provider = "anthroprobe"
port = $PROBE_HEAD_PORT
discovery_prefix = "claude-planprobe--"
pinned_model = "claude-sonnet-5"
[heads.planprobe.claude]
command = "claude-planprobe"
EOF
  cat "$HOME/.config/splice/splice.toml"
}
step "topology written" write_plan_topology

# ── 3. install and cold start, as a user would ─────────────────────────────────────────────────
install_plan() {
  { [ -f "$ARTIFACTS/splice.jar" ] && [ -f "$ARTIFACTS/splice-launch" ]; } || { echo "no artifacts in $ARTIFACTS"; return 1; }
  local installer="$REPO/install.sh"
  [ -f "$ARTIFACTS/install.sh" ] && installer="$ARTIFACTS/install.sh"
  SPLICE_JAR="$ARTIFACTS/splice.jar" SPLICE_SHIM="$ARTIFACTS/splice-launch" bash "$installer" </dev/null || return 1
  [ -x "$HOME/.local/bin/claude-planlimit" ] || { echo "claude-planlimit wrapper not linked"; return 1; }
  splice version
}
step "install.sh from artifacts: claude-planlimit linked" install_plan

plan_cold_start() {
  splice restart </dev/null || return 1
  wait_health 60 || return 1
  ss -ltn | grep -E ":($PLAN_HEAD_PORT|$PROBE_HEAD_PORT) " || { echo "head ports not listening"; return 1; }
}
step "daemon cold start: both heads ready" plan_cold_start

# The launch recipe is where persistent retry is planted; without it the client stops after its
# default retries and the rest of this scenario would be measuring something else. It carries the
# turn key too, so it lives in lib.sh's 0700 $PRIVATE, 0600 from its first byte, never under $OUT,
# which run.sh copies into the receipts and e2e-docker.yml uploads (V4-311).
PLAN_RECIPE="$PRIVATE/recipe-planlimit.json"
plan_recipe() {
  mkdir -p "$PRIVATE" && chmod 0700 "$PRIVATE" || return 1
  ( umask 077
    curl_mgmt -X POST -H 'Content-Type: application/json' \
      --data '{"dangerouslySkipPermissions":"","args":[]}' "http://127.0.0.1:$CONTROL_PORT/launch/planlimit" \
      > "$PLAN_RECIPE" ) || return 1
  grep -o '"CLAUDE_CODE_RETRY_WATCHDOG":"[^"]*"' "$PLAN_RECIPE" || { echo "no CLAUDE_CODE_RETRY_WATCHDOG in the recipe"; return 1; }
  grep -q '"CLAUDE_CODE_RETRY_WATCHDOG":"1"' "$PLAN_RECIPE" || { echo "persistent retry is not planted"; return 1; }
}
step "launch recipe: persistent retry planted" plan_recipe

# ── 4. what the client is told: the relabelled frame, the refusal, the buffered 429 ──────────────
step "what the client is told: the relabelled frame, the refusal, the buffered 429; no no-wait signal" \
  bun "$PLAN_TS" probe "$PROBE_HEAD_PORT" "$OUT/first-frame.json"

# ── 5. the real client sleeps through the limit and resumes after the reset ─────────────────────
plan_turn() {
  local out rc
  out="$(ANTHROPIC_API_KEY=mock-key DISABLE_AUTOUPDATER=1 DISABLE_TELEMETRY=1 DISABLE_ERROR_REPORTING=1 \
    CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC=1 \
    timeout 480 claude-planlimit -p "Say hello." --output-format text </dev/null 2>&1)"
  rc=$?
  date +%s%3N > "$OUT/turn-end-ms"
  printf '%s\n' "$out" | tail -c 1500
  [ $rc -eq 0 ] || { echo "claude-planlimit exit $rc"; return 1; }
  printf '%s' "$out" | grep -qF "resumed after the reset" || { echo "the turn's output lacks the upstream's post-reset reply"; return 1; }
}
step "real Claude Code: the turn waits out the plan limit and completes" plan_turn
step "the turn ended after the upstream's reset" bun "$PLAN_TS" resumed "$OUT/upstream-turn.jsonl" "$(cat "$OUT/turn-end-ms" 2>/dev/null || echo 0)"
step "upstream timeline while at its limit" bun "$PLAN_TS" upstream "$OUT/upstream-turn.jsonl"

# The client's own record of what it was told: its transcripts, wherever the head's config dir put them.
keep_transcripts() {
  mkdir -p "$OUT/claude-transcripts"
  find "$HOME" -path '*/projects/*.jsonl' -newer "$PLAN_RECIPE" -exec cp {} "$OUT/claude-transcripts/" \; 2>/dev/null
  ls -l "$OUT/claude-transcripts"
}
step "Claude Code transcripts kept" keep_transcripts
