#!/usr/bin/env bash
# tools/e2e/docker/runtime-head.sh — a local runtime head the way `splice setup` adds one, through
# splice, to the REAL Claude Code at the pinned version. Run INSIDE the container by
# `run.sh --scenario runtime-head`.
#
# The claim under test is V4-232: a fresh claude-bonsai prints no [claude-code:unrecognized_model]
# line and its print-mode stdout is the answer alone, because the row setup writes presents the
# runtime's model to the client as a Claude model it knows (client_model, written as the head's
# settings.json modelOverrides); the client then sizes the row from its own table (200k), and usage
# scaling keeps it compacting at the window the runtime serves. The runtime still gets its own model
# id and nothing it refuses. The upstream is runtime_head.ts serve: llama-server-shaped, one model.
#
# RUNTIME_CLIENT_MODEL is the row's client_model: claude-sonnet-4-6 as RuntimeHeadAdd writes it
# (RUNTIME_CLIENT_MODEL there), or `none` for the row as setup wrote it before V4-232 (the red).
set -uo pipefail

RECEIPT_KIND="splice-runtime-head-e2e"
RECEIPT_LABEL="RUNTIME-HEAD E2E"
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"
trap finish EXIT

RUNTIME_TS="$(dirname "${BASH_SOURCE[0]}")/runtime_head.ts"
RUNTIME_HEAD_PORT=3108
RUNTIME_MODEL="bonsai-2-27b"
# The live bonsai row's window: over 200k, so scaling carries the client past its table's number.
RUNTIME_SERVED=245760
RUNTIME_CLIENT_MODEL="${RUNTIME_CLIENT_MODEL:-claude-sonnet-4-6}"
RUNTIME_LOG="$OUT/runtime-requests.jsonl"
RUNTIME_PORT=""

echo "runtime-head e2e: user=$(id -un) home=$HOME artifacts=$ARTIFACTS client_model=$RUNTIME_CLIENT_MODEL"

step "Claude Code version matches the splice tested pin" client_version_receipt

# ── 1. the runtime ──────────────────────────────────────────────────────────────────────────────
start_runtime() {
  : > "$RUNTIME_LOG"
  RUNTIME_MODEL="$RUNTIME_MODEL" nohup bun "$RUNTIME_TS" serve "$RUNTIME_LOG" \
    > "$OUT/mock_runtime.out" 2> "$OUT/mock_runtime.err" &
  echo $! > "$OUT/mock_runtime.pid"
  for _ in $(seq 1 50); do [ -s "$OUT/mock_runtime.out" ] && break; sleep 0.2; done
  [ -s "$OUT/mock_runtime.out" ] || { echo "runtime did not start: $(cat "$OUT/mock_runtime.err")"; return 1; }
  cat "$OUT/mock_runtime.out"
}
step "llama-server-shaped runtime up" start_runtime
RUNTIME_PORT="$(mock_field mock_runtime.out port 2>/dev/null)"

# ── 2. topology: the row `splice setup` writes for a runtime rig describes ──────────────────────
# Line for line AddProfiles' rendering of RuntimeHeadAdd's profile (RuntimeRowPresentedTest pins the
# client_model line through the real loader), written before install.sh so init keeps it.
write_runtime_topology() {
  local presented=""
  [ "$RUNTIME_CLIENT_MODEL" = "none" ] || presented="client_model = \"$RUNTIME_CLIENT_MODEL\""
  mkdir -p "$HOME/.config/splice"
  cat > "$HOME/.config/splice/splice.toml" <<EOF
# runtime-head e2e topology — generated by tools/e2e/docker/runtime-head.sh
[daemon]
control_port = $CONTROL_PORT

# Added by \`splice setup\`.
[providers.bonsai]
dialect = "openai-chat"
base_url = "http://127.0.0.1:$RUNTIME_PORT/v1"
auth = { kind = "api-key", env = "BONSAI_API_KEY" }
# Served on this machine; the facts are \`rig describe $RUNTIME_MODEL\`'s. The endpoint takes no key:
# BONSAI_API_KEY in keys.toml is a placeholder, because the api-key kind needs one that resolves.
quirks = { reasoning_effort = false, slot_affinity = true }
[[providers.bonsai.models]]
id = "$RUNTIME_MODEL"
label = "Ternary Bonsai 2 27B (mock runtime)"
context_window = $RUNTIME_SERVED
$presented

[heads.bonsai]
provider = "bonsai"
port = $RUNTIME_HEAD_PORT
discovery_prefix = "claude-bonsai--"
pinned_model = "$RUNTIME_MODEL"
context_window = $RUNTIME_SERVED
[heads.bonsai.claude]
command = "claude-bonsai"
EOF
  cat "$HOME/.config/splice/splice.toml"
}
step "topology written: the runtime row as setup writes it" write_runtime_topology

# ── 3. install and cold start, as a user would ─────────────────────────────────────────────────
install_runtime() {
  { [ -f "$ARTIFACTS/splice.jar" ] && [ -f "$ARTIFACTS/splice-launch" ]; } || { echo "no artifacts in $ARTIFACTS"; return 1; }
  local installer="$REPO/install.sh"
  [ -f "$ARTIFACTS/install.sh" ] && installer="$ARTIFACTS/install.sh"
  SPLICE_JAR="$ARTIFACTS/splice.jar" SPLICE_SHIM="$ARTIFACTS/splice-launch" bash "$installer" </dev/null || return 1
  [ -x "$HOME/.local/bin/claude-bonsai" ] || { echo "claude-bonsai wrapper not linked"; return 1; }
  # RuntimeHeadAdd plants a placeholder key the same way: the endpoint takes none.
  printf '%s' "no-key" | splice key set BONSAI_API_KEY --stdin || return 1
  splice version
}
step "install.sh from artifacts: claude-bonsai linked" install_runtime

runtime_cold_start() {
  splice restart </dev/null || return 1
  wait_health 60 || return 1
  ss -ltn | grep -E ":$RUNTIME_HEAD_PORT " || { echo "head port not listening"; return 1; }
}
step "daemon cold start: the runtime head ready" runtime_cold_start

# ── 4. the real client, print mode: no unrecognized_model line, the answer alone ────────────────
bonsai() { # output-format stdout-file stderr-file
  DISABLE_AUTOUPDATER=1 DISABLE_TELEMETRY=1 DISABLE_ERROR_REPORTING=1 CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC=1 \
    timeout 120 claude-bonsai -p "Say hello." --output-format "$1" </dev/null > "$2" 2> "$3"
}
text_turn() {
  bonsai text "$OUT/p-text.stdout" "$OUT/p-text.stderr"
  local rc=$?
  echo "claude-bonsai -p exit $rc"
  [ $rc -eq 0 ]
}
# step runs its command in a subshell, so each turn's first log line is taken here, in the main shell.
TEXT_FROM="$(wc -l < "$RUNTIME_LOG")"
step "real Claude Code: claude-bonsai -p answers" text_turn
step "print mode: no [claude-code:unrecognized_model] line" bun "$RUNTIME_TS" quiet "$OUT/p-text.stderr"
step "print mode: stdout is the answer alone" bun "$RUNTIME_TS" answer "$OUT/p-text.stdout"
step "the runtime got its own model id and nothing it refuses, answered 200" \
  bun "$RUNTIME_TS" served "$RUNTIME_LOG" "$RUNTIME_MODEL" "$TEXT_FROM"

# ── 5. the client compacts at the runtime's own window: its window for the row and the counts ──────
json_turn() {
  bonsai json "$OUT/p-json.stdout" "$OUT/p-json.stderr"
  local rc=$?
  echo "claude-bonsai -p --output-format json exit $rc"
  [ $rc -eq 0 ]
}
JSON_FROM="$(wc -l < "$RUNTIME_LOG")"
step "real Claude Code: claude-bonsai -p --output-format json answers" json_turn
step "the client compacts at the runtime's own window, $RUNTIME_SERVED, through its window and the scaled counts" \
  bun "$RUNTIME_TS" window "$OUT/p-json.stdout" "$RUNTIME_SERVED" "$RUNTIME_LOG" "$JSON_FROM"

# ── 6. interactive: the same session with a terminal, the line read from its debug log ─────────
# Interactively Claude Code writes the line to its debug log at warn level, never to a stream (cli
# 2.1.283 `Wee`: stderr in print mode only), so the session runs under `script` for a terminal, with
# --debug-file, and the log is read once the runtime has answered the turn. The folder-trust record a
# user grants once sits in ~/.claude.json, and each launch carries it into the head (FolderTrust), so
# the session reaches the prompt rather than the trust dialog.
seed_trust() {
  mkdir -p "$HOME/work" || return 1
  printf '{"projects":{"%s":{"hasTrustDialogAccepted":true}}}\n' "$HOME/work" > "$HOME/.claude.json"
  cat "$HOME/.claude.json"
}
step "folder trust granted for the interactive session's cwd" seed_trust

interactive_turn() { # first-log-line
  local answered=0 group
  ( cd "$HOME/work" && exec setsid env DISABLE_AUTOUPDATER=1 DISABLE_TELEMETRY=1 DISABLE_ERROR_REPORTING=1 \
      CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC=1 TERM=xterm-256color bash -c \
      "sleep 120 | script -qefc \"claude-bonsai --debug-file '$OUT/interactive-debug.log' 'Say hello.'\" /dev/null" \
      > "$OUT/interactive.tty" 2>&1 ) &
  group=$!
  for _ in $(seq 1 180); do
    # The main thread's request (it carries tools; the title request does not), answered. One reader,
    # no pipe: under pipefail, `tail | grep -q` fails on tail's SIGPIPE once grep matches.
    if awk -v from="$1" 'NR > from && /"status":200/ && /"tools":\[/ { hit = 1 } END { exit !hit }' "$RUNTIME_LOG"; then
      answered=1; break
    fi
    sleep 0.5
  done
  sleep 2
  kill -- -"$group" 2>/dev/null
  wait "$group" 2>/dev/null
  echo "the runtime answered the interactive turn: $answered"
  [ "$answered" = 1 ] || { strip_ansi < "$OUT/interactive.tty" | tail -c 1200; return 1; }
}
INTERACTIVE_FROM="$(wc -l < "$RUNTIME_LOG")"
step "real Claude Code, interactive: the turn reaches the runtime and is answered" interactive_turn "$INTERACTIVE_FROM"
step "interactive: no [claude-code:unrecognized_model] line in the debug log" \
  bun "$RUNTIME_TS" quiet "$OUT/interactive-debug.log"
