// NEW: a selected live cell closed by a source tear must not become invalid client input.
package splice.provider.codex

import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.CompletableDeferred
import kotlinx.coroutines.async
import kotlinx.coroutines.runBlocking
import kotlinx.coroutines.withTimeout
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertFalse
import org.junit.jupiter.api.Assertions.assertNull
import org.junit.jupiter.api.Assertions.assertThrows
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Timeout
import org.junit.jupiter.params.ParameterizedTest
import org.junit.jupiter.params.provider.CsvSource
import org.junit.jupiter.params.provider.ValueSource
import splice.core.turn.FailureCause
import splice.core.turn.FailurePhase
import splice.core.turn.TurnOutcome
import splice.upstream.RedirectableRoundPost
import splice.upstream.codemode.CodeModeCell
import splice.upstream.codemode.CodeModeResult
import splice.upstream.codemode.CodeModeRuntime
import splice.upstream.codemode.CodeModeSource
import splice.upstream.codemode.CodeModeSourcePart
import splice.upstream.codemode.CodeModeStep
import splice.upstream.failure.CodeModeInfrastructureCategory
import splice.upstream.failure.CodeModeInfrastructureClass
import splice.upstream.failure.CodeModeInfrastructureException
import splice.upstream.sse.WireSink
import java.io.IOException

/** A retained source can fail while a client-result step has already selected its live cell. */
class CodexCodeModeSourceTearTest : CodeModeStatementStreamSupport() {
    @ParameterizedTest
    @CsvSource(
        "io,closed",
        "io,buffered",
        "UPSTREAM_CONN_RESET,closed",
        "UPSTREAM_TRUNCATED,closed",
        "UPSTREAM_STALLED,closed",
        "local,closed",
        "io,persistence",
        "io,infrastructure",
        "io,cancel",
    )
    @Timeout(20)
    fun `source failure preserves attribution and accepted calls without replay`(
        sourceFailure: String,
        cellExit: String,
    ) = runBlocking {
        val runtime = ClosingRuntime(cellExit)
        val manager = bridge(runtime)
        val sink = StepSink()
        val post = GatedPost(sink)
        val sourcePost = failingSource(post, sourceFailure)
        try {
            manager.interceptor(turn(), disableParallel = false).intercept(BASE_REQUEST, sink, sourcePost)
            val first = sink.callback.await()
            val next = StepSink()
            val request = async {
                manager.interceptor(turn(first.id, "result-0"), disableParallel = false)
                    .intercept(history(listOf(first)), next, sourcePost)
            }
            withTimeout(1_500) { runtime.advancing.await() }
            post.tearAfterFirst = true
            post.gates[1].complete(Unit)
            if (cellExit == "cancel") {
                assertThrows(CancellationException::class.java) {
                    runBlocking { withTimeout(5_000) { request.await() } }
                }
                assertTrue(request.isCancelled, "the cell cancellation must reach its caller, not an await timeout")
                assertFalse(next.callback.isCompleted)
                return@runBlocking
            }
            val outcome = withTimeout(5_000) { request.await() } as TurnOutcome.Failure
            assertEquals(
                sourceFailure == "local" || cellExit == "infrastructure",
                outcome.deterministic,
                outcome.toString(),
            )
            val localFault = sourceFailure == "local" || cellExit == "persistence" || cellExit == "infrastructure"
            assertEquals(
                if (localFault) FailureCause.CODE_MODE_PROTOCOL else FailureCause.UPSTREAM_CONN_RESET,
                outcome.cause,
            )
            assertNull(outcome.partial, "partial exec source cannot be regenerated by a server reanchor")
            assertFalse(next.callback.isCompleted, "no statement after the tear may execute")
            assertEquals(1, runtime.starts)
            assertEquals(1, post.posts, "failure itself must not regenerate the live source")
            assertLostRecovery(manager, first, post, runtime)
        } finally {
            manager.onHeadStop()
        }
    }

    private suspend fun assertLostRecovery(
        manager: CodexCodeModeBridge,
        first: SeenTool,
        post: GatedPost,
        runtime: ClosingRuntime,
    ) {
        val recovered = manager.interceptor(turn(first.id, "result-0"), disableParallel = false)
            .intercept(history(listOf(first)), StepSink(), post)
        assertTrue(recovered is TurnOutcome.Success, recovered.toString())
        assertTrue(post.continuation.contains("source was not rerun"))
        assertTrue(post.continuation.contains("result-0"))
        assertEquals(1, runtime.starts, "client retry resumes lost-record evidence, not script execution")
    }

    @ParameterizedTest
    @ValueSource(strings = ["io", "UPSTREAM_TRUNCATED", "local"])
    @Timeout(20)
    fun `a source tear while the runtime starts keeps the upstream verdict`(sourceFailure: String) = runBlocking {
        val runtime = StartingRuntime()
        val manager = bridge(runtime)
        val sink = StepSink()
        val post = GatedPost(sink)
        val request = async {
            manager.interceptor(turn(), disableParallel = false)
                .intercept(BASE_REQUEST, sink, failingSource(post, sourceFailure))
        }
        try {
            withTimeout(5_000) { runtime.starting.await() }
            post.tearAfterFirst = true
            post.gates[1].complete(Unit)
            withTimeout(5_000) {
                while (!stateFiles.records().single().toString().contains("LOST")) kotlinx.coroutines.yield()
            }
            runtime.release.complete(Unit)
            val outcome = withTimeout(5_000) { request.await() } as TurnOutcome.Failure
            assertEquals(
                if (sourceFailure == "local") FailureCause.INTERNAL else FailureCause.UPSTREAM_CONN_RESET,
                outcome.cause,
            )
            assertFalse(outcome.deterministic)
            assertNull(outcome.partial)
            assertFalse(sink.callback.isCompleted)
            assertEquals(1, post.posts)
        } finally {
            runtime.release.complete(Unit)
            manager.onHeadStop()
        }
    }

    private class StartingRuntime : CodeModeRuntime {
        val starting = CompletableDeferred<Unit>()
        val release = CompletableDeferred<Unit>()
        override suspend fun start(
            source: String,
            tools: Set<String>,
            descriptions: Map<String, String>,
        ): CodeModeCell = error("streaming source required")
        override suspend fun startStreaming(
            source: CodeModeSource,
            tools: Set<String>,
            descriptions: Map<String, String>,
        ): CodeModeCell {
            check(source.read() is CodeModeSourcePart.Delta)
            starting.complete(Unit)
            release.await()
            return object : CodeModeCell {
                override suspend fun advance(results: List<CodeModeResult>): CodeModeStep =
                    error("torn startup cannot advance")
                override fun close() = Unit
            }
        }
        override fun close() = Unit
    }

    private fun failingSource(post: GatedPost, failure: String): RedirectableRoundPost =
        object : RedirectableRoundPost by post {
            override suspend fun into(bodyJson: String, sink: WireSink): TurnOutcome = try {
                post.into(bodyJson, sink)
            } catch (error: IOException) {
                if (failure == "io") throw error
                if (failure == "local") error("synthetic private protocol bytes")
                TurnOutcome.Failure(
                    "synthetic source transport failure",
                    cause = FailureCause.valueOf(failure),
                    phase = FailurePhase.MID_OUTPUT,
                )
            }
        }

    /** Matches JvmCodeModeCell disposal, including a buffered result racing the source failure. */
    private inner class ClosingRuntime(private val exit: String) : CodeModeRuntime {
        val advancing = CompletableDeferred<Unit>()
        private val closed = CompletableDeferred<Unit>()
        var starts = 0
        override suspend fun start(
            source: String,
            tools: Set<String>,
            descriptions: Map<String, String>,
        ): CodeModeCell = error("live source requires streaming")

        override suspend fun startStreaming(
            source: CodeModeSource,
            tools: Set<String>,
            descriptions: Map<String, String>,
        ): CodeModeCell {
            starts++
            check(source.read() is CodeModeSourcePart.Delta)
            return object : CodeModeCell {
                private var first = true
                override suspend fun advance(results: List<CodeModeResult>): CodeModeStep {
                    if (first) {
                        first = false
                        return CodeModeStep.Calls(listOf(call("runtime-first", "Read")))
                    }
                    advancing.complete(Unit)
                    closed.await()
                    if (exit == "cancel") throw CancellationException("synthetic cell cancellation")
                    if (exit == "infrastructure") {
                        throw CodeModeInfrastructureException(
                            CodeModeInfrastructureCategory.PROTOCOL,
                            CodeModeInfrastructureClass.IO,
                        )
                    }
                    if (exit == "buffered") return CodeModeStep.Calls(listOf(call("runtime-buffered", "Edit")))
                    if (exit == "persistence") {
                        throw CodeModePersistenceException(IOException("synthetic state bytes"), false)
                    }
                    check(!closed.isCompleted) { "Code-mode cell is closed" }
                    error("a disposed cell cannot advance")
                }
                override fun close() {
                    closed.complete(Unit)
                }
            }
        }
        override fun close() = Unit
    }
}
