// NEW: a selected live cell closed by a source tear must not become invalid client input.
package splice.provider.codex

import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.CompletableDeferred
import kotlinx.coroutines.async
import kotlinx.coroutines.runBlocking
import kotlinx.coroutines.withTimeout
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertFalse
import org.junit.jupiter.api.Assertions.assertNull
import org.junit.jupiter.api.Assertions.assertThrows
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.Timeout
import org.junit.jupiter.params.ParameterizedTest
import org.junit.jupiter.params.provider.CsvSource
import org.junit.jupiter.params.provider.ValueSource
import splice.core.index.WireBlockIndex
import splice.core.turn.FailureCause
import splice.core.turn.FailurePhase
import splice.core.turn.TurnOutcome
import splice.core.util.JsonScalars
import splice.upstream.RedirectableRoundPost
import splice.upstream.codemode.CodeModeCell
import splice.upstream.codemode.CodeModeResult
import splice.upstream.codemode.CodeModeRuntime
import splice.upstream.codemode.CodeModeSource
import splice.upstream.codemode.CodeModeSourcePart
import splice.upstream.codemode.CodeModeStep
import splice.upstream.failure.CodeModeInfrastructureCategory
import splice.upstream.failure.CodeModeInfrastructureClass
import splice.upstream.failure.CodeModeInfrastructureException
import splice.upstream.sse.WireSink
import java.io.IOException

/** A retained source can fail while a client-result step has already selected its live cell. */
class CodexCodeModeSourceTearTest : CodeModeStatementStreamSupport() {
    @ParameterizedTest
    @CsvSource(
        "io,closed",
        "io,buffered",
        "UPSTREAM_CONN_RESET,closed",
        "UPSTREAM_TRUNCATED,closed",
        "UPSTREAM_STALLED,closed",
        "local,closed",
        "io,persistence",
        "io,infrastructure",
        "io,cancel",
    )
    @Timeout(20)
    fun `source failure preserves attribution and accepted calls without replay`(
        sourceFailure: String,
        cellExit: String,
    ) = runBlocking {
        val runtime = ClosingRuntime(cellExit)
        val manager = bridge(runtime)
        val sink = StepSink()
        val post = GatedPost(sink)
        val sourcePost = failingSource(post, sourceFailure)
        try {
            manager.interceptor(turn(), disableParallel = false).intercept(BASE_REQUEST, sink, sourcePost)
            val first = sink.callback.await()
            val next = StepSink()
            val request = async {
                manager.interceptor(turn(first.id, "result-0"), disableParallel = false)
                    .intercept(history(listOf(first)), next, sourcePost)
            }
            withTimeout(1_500) { runtime.advancing.await() }
            post.tearAfterFirst = true
            post.gates[1].complete(Unit)
            if (cellExit == "cancel") {
                assertThrows(CancellationException::class.java) {
                    runBlocking { withTimeout(5_000) { request.await() } }
                }
                assertTrue(request.isCancelled, "the cell cancellation must reach its caller, not an await timeout")
                assertFalse(next.callback.isCompleted)
                return@runBlocking
            }
            val outcome = withTimeout(5_000) { request.await() } as TurnOutcome.Failure
            assertEquals(
                sourceFailure == "local" || cellExit == "infrastructure",
                outcome.deterministic,
                outcome.toString(),
            )
            val localFault = sourceFailure == "local" || cellExit == "persistence" || cellExit == "infrastructure"
            assertEquals(
                if (localFault) FailureCause.CODE_MODE_PROTOCOL else FailureCause.UPSTREAM_CONN_RESET,
                outcome.cause,
            )
            assertNull(outcome.partial, "partial exec source cannot be regenerated by a server reanchor")
            assertFalse(next.callback.isCompleted, "no statement after the tear may execute")
            assertEquals(1, runtime.starts)
            assertEquals(1, post.posts, "failure itself must not regenerate the live source")
            assertLostRecovery(manager, first, post, runtime)
        } finally {
            manager.onHeadStop()
        }
    }

    /** Oct 4 at 2:28, 2:53 and 3:20 PM CT, a round ended without a completed exec while its step was waiting on
     *  the next statement. The capture lost the record, the loss closed the cell under that step, and the step
     *  ended as invalid_request, which Claude Code does not retry. */
    @Test
    @Timeout(20)
    fun `the step that posted a round ends as a source tear when the round leaves its exec incomplete`() {
        postingStepEndedBy(null)
    }

    @Test
    @Timeout(20)
    fun `the step that posted a round ends as a source tear when the round fails transiently`() {
        postingStepEndedBy(
            TurnOutcome.Failure(
                "upstream: synthetic transient failure",
                cause = FailureCause.UPSTREAM_REPORTED,
                phase = FailurePhase.MID_OUTPUT,
                providerReported = true,
            ),
        )
    }

    @Test
    @Timeout(20)
    fun `the step that posted a round ends with the round's permanent failure as it is`() {
        postingStepEndedBy(
            TurnOutcome.Failure(
                "upstream: generation stopped by content filter",
                cause = FailureCause.CONTENT_FILTERED,
                phase = FailurePhase.TERMINAL,
                providerReported = true,
                permanent = true,
            ),
        )
    }

    /** The posting step's cell waits on its next statement while the round ends: as an incomplete success with no
     *  [ending], or with [ending] in place of the response's terminal. */
    private fun postingStepEndedBy(ending: TurnOutcome.Failure?) = runBlocking<Unit> {
        val runtime = ClosingRuntime("closed", parkFirst = true)
        val manager = bridge(runtime)
        val sink = StepSink()
        val post = GatedPost(sink)
        val roundPost = ending?.let { endingWith(post, it) } ?: post
        try {
            val request = async {
                manager.interceptor(turn(), disableParallel = false).intercept(BASE_REQUEST, sink, roundPost)
            }
            withTimeout(1_500) { runtime.advancing.await() }
            if (ending == null) post.terminalProblem = "incomplete"
            endRound(post)
            val outcome = withTimeout(5_000) { request.await() }
            if (ending?.permanent == true) {
                val failure = outcome as TurnOutcome.Failure
                assertEquals(ending.cause, failure.cause, failure.toString())
                assertTrue(failure.permanent, "a permanent upstream verdict reaches the client as it is: $failure")
                assertEquals(ending.message, failure.message)
            } else {
                assertSourceTear(outcome)
            }
            assertFalse(sink.callback.isCompleted, "no statement after the round's terminal may execute")
            assertEquals(1, runtime.starts)
            assertEquals(1, post.posts, "the uncompleted source is never regenerated")
            val branch = ending?.let { "failure cause=${it.cause} permanent=${it.permanent}" } ?: "incomplete"
            val line = logLines.single { "upstream exec source did not complete" in it }
            assertTrue(line.startsWith("[code-mode] upstream exec source did not complete: $branch"), line)
            assertFalse(
                "synthetic" in line || "content filter" in line || "tools." in line,
                "the line names the ending, never upstream text or source: $line",
            )
        } finally {
            manager.onHeadStop()
        }
    }

    /** Control: with no step holding the cell, the uncompleted source is reclaimed and the next result step continues on
     *  the client's history, as it did before the waiting step's fix, rather than reporting the round's ending. */
    @Test
    @Timeout(20)
    fun `a parked script whose round ends incomplete continues on the client's history at its next step`() {
        runBlocking<Unit> {
            val runtime = ClosingRuntime("closed")
            val manager = bridge(runtime)
            val sink = StepSink()
            val post = GatedPost(sink)
            try {
                manager.interceptor(turn(), disableParallel = false).intercept(BASE_REQUEST, sink, post)
                val first = sink.callback.await()
                post.terminalProblem = "incomplete"
                endRound(post)
                withTimeout(5_000) {
                    while (JsonScalars.str(stateFiles.records().single()["error"]) == null) kotlinx.coroutines.yield()
                }
                assertLostRecovery(manager, first, post, runtime)
            } finally {
                manager.onHeadStop()
            }
        }
    }

    /** The round [post] streams, ended by [ending] in place of its own terminal. */
    private fun endingWith(post: GatedPost, ending: TurnOutcome.Failure): RedirectableRoundPost =
        object : RedirectableRoundPost by post {
            override suspend fun into(bodyJson: String, sink: WireSink): TurnOutcome {
                val outcome = post.into(bodyJson, sink)
                return if (post.posts == 1) ending else outcome
            }
        }

    @Test
    @Timeout(20)
    fun `a result step whose cell the incomplete round closes ends as a source tear`() {
        resultStepAfterIncompleteRound("closed")
    }

    @Test
    @Timeout(20)
    fun `a result step whose buffered reply beats the incomplete round's close ends as a source tear`() {
        resultStepAfterIncompleteRound("buffered")
    }

    private fun resultStepAfterIncompleteRound(cellExit: String) = runBlocking<Unit> {
        val runtime = ClosingRuntime(cellExit)
        val manager = bridge(runtime)
        val sink = StepSink()
        val post = GatedPost(sink)
        try {
            manager.interceptor(turn(), disableParallel = false).intercept(BASE_REQUEST, sink, post)
            val first = sink.callback.await()
            val next = StepSink()
            val request = async {
                manager.interceptor(turn(first.id, "result-0"), disableParallel = false)
                    .intercept(history(listOf(first)), next, post)
            }
            withTimeout(1_500) { runtime.advancing.await() }
            post.terminalProblem = "incomplete"
            endRound(post)
            assertSourceTear(withTimeout(5_000) { request.await() })
            assertFalse(next.callback.isCompleted, "no statement after the incomplete terminal may execute")
            assertEquals(1, runtime.starts)
            assertEquals(1, post.posts, "the incomplete source is never regenerated")
            assertLostRecovery(manager, first, post, runtime)
        } finally {
            manager.onHeadStop()
        }
    }

    /** A result step attaches its sink after the record-error check, and the attach replays the round's buffered
     *  progress into it. The round can lose its uncertified source there, so the step reaches the machine's cell
     *  acquire with the cell gone. It ends as a torn source's step, never as the machine's "cell is unavailable". */
    @Test
    @Timeout(20)
    fun `a result step that reaches its cell after the incomplete round removed it ends as a source tear`() =
        runBlocking<Unit> {
            val runtime = ClosingRuntime("closed")
            val manager = bridge(runtime)
            val sink = StepSink()
            val post = GatedPost(sink)
            try {
                manager.interceptor(turn(), disableParallel = false).intercept(BASE_REQUEST, sink, post)
                val first = sink.callback.await()
                post.gates.drop(1).forEach { it.complete(Unit) }
                withTimeout(1_500) { post.itemDone.await() }
                val next = HeldSink()
                val request = async {
                    manager.interceptor(turn(first.id, "result-0"), disableParallel = false)
                        .intercept(history(listOf(first)), next, post)
                }
                withTimeout(1_500) { next.reached.await() }
                post.terminalProblem = "incomplete"
                post.complete.complete(Unit)
                withTimeout(5_000) {
                    while (JsonScalars.str(stateFiles.records().single()["error"]) == null) kotlinx.coroutines.yield()
                }
                next.held.complete(Unit)
                assertSourceTear(withTimeout(5_000) { request.await() })
                assertEquals(1, runtime.starts)
                assertEquals(1, post.posts, "the incomplete source is never regenerated")
                assertLostRecovery(manager, first, post, runtime)
            } finally {
                manager.onHeadStop()
            }
        }

    /** A client step's sink that holds the first progress write the round's buffer replays into it. */
    private class HeldSink : WireSink by RecordingSink() {
        val reached = CompletableDeferred<Unit>()
        val held = CompletableDeferred<Unit>()
        override suspend fun thinkingDelta(index: WireBlockIndex, thinking: String) {
            reached.complete(Unit)
            held.await()
        }
    }

    /** The rest of the source streams and its item completes, then the response reaches its terminal. */
    private fun endRound(post: GatedPost) {
        post.gates.drop(1).forEach { it.complete(Unit) }
        post.complete.complete(Unit)
    }

    private fun assertSourceTear(outcome: TurnOutcome) {
        assertTrue(outcome is TurnOutcome.Failure, outcome.toString())
        val failure = outcome as TurnOutcome.Failure
        assertFalse(failure.deterministic, "a splice-local closed cell is retryable, never invalid_request: $failure")
        assertEquals(FailureCause.UPSTREAM_CONN_RESET, failure.cause, failure.toString())
        assertTrue(failure.message.contains("source was not rerun"), failure.message)
        assertNull(failure.partial, "partial exec source cannot be regenerated by a server reanchor")
    }

    private suspend fun assertLostRecovery(
        manager: CodexCodeModeBridge,
        first: SeenTool,
        post: GatedPost,
        runtime: ClosingRuntime,
    ) {
        val recovered = manager.interceptor(turn(first.id, "result-0"), disableParallel = false)
            .intercept(history(listOf(first)), StepSink(), post)
        assertTrue(recovered is TurnOutcome.Success, recovered.toString())
        assertTrue(post.continuation.contains("source was not rerun"))
        assertTrue(post.continuation.contains("result-0"))
        assertEquals(1, runtime.starts, "client retry resumes lost-record evidence, not script execution")
    }

    @ParameterizedTest
    @ValueSource(strings = ["io", "UPSTREAM_TRUNCATED", "local"])
    @Timeout(20)
    fun `a source tear while the runtime starts keeps the upstream verdict`(sourceFailure: String) = runBlocking {
        val runtime = StartingRuntime()
        val manager = bridge(runtime)
        val sink = StepSink()
        val post = GatedPost(sink)
        val failureReached = CompletableDeferred<Unit>()
        val releaseFailure = CompletableDeferred<Unit>()
        val sourcePost = failingSource(post, sourceFailure) {
            failureReached.complete(Unit)
            releaseFailure.await()
        }
        val request = async {
            manager.interceptor(turn(), disableParallel = false)
                .intercept(BASE_REQUEST, sink, sourcePost)
        }
        try {
            withTimeout(5_000) { runtime.starting.await() }
            post.tearAfterFirst = true
            post.gates[1].complete(Unit)
            withTimeout(5_000) { failureReached.await() }
            val admission = stateFiles.records().single()
            assertEquals("LOST", JsonScalars.str(admission["phase"]))
            assertNull(JsonScalars.str(admission["error"]), "the no-rerun admission is not a source failure")
            releaseFailure.complete(Unit)
            // Admission is already durably LOST. Only the failure's error proves attachment must reject.
            withTimeout(5_000) {
                while (JsonScalars.str(stateFiles.records().single()["error"]) == null) kotlinx.coroutines.yield()
            }
            runtime.release.complete(Unit)
            val outcome = withTimeout(5_000) { request.await() } as TurnOutcome.Failure
            assertEquals(
                if (sourceFailure == "local") FailureCause.INTERNAL else FailureCause.UPSTREAM_CONN_RESET,
                outcome.cause,
            )
            assertFalse(outcome.deterministic)
            assertNull(outcome.partial)
            assertFalse(sink.callback.isCompleted)
            assertEquals(0, runtime.advances, "failed source attachment must not advance the returned cell")
            assertEquals(1, post.posts)
        } finally {
            releaseFailure.complete(Unit)
            runtime.release.complete(Unit)
            manager.onHeadStop()
        }
    }

    private class StartingRuntime : CodeModeRuntime {
        val starting = CompletableDeferred<Unit>()
        val release = CompletableDeferred<Unit>()
        var advances = 0
        override suspend fun start(
            source: String,
            tools: Set<String>,
            descriptions: Map<String, String>,
        ): CodeModeCell = error("streaming source required")
        override suspend fun startStreaming(
            source: CodeModeSource,
            tools: Set<String>,
            descriptions: Map<String, String>,
        ): CodeModeCell {
            check(source.read() is CodeModeSourcePart.Delta)
            starting.complete(Unit)
            release.await()
            return object : CodeModeCell {
                override suspend fun advance(results: List<CodeModeResult>): CodeModeStep {
                    advances++
                    error("torn startup cannot advance")
                }
                override fun close() = Unit
            }
        }
        override fun close() = Unit
    }

    private fun failingSource(
        post: GatedPost,
        failure: String,
        beforeFailure: suspend () -> Unit = {},
    ): RedirectableRoundPost =
        object : RedirectableRoundPost by post {
            override suspend fun into(bodyJson: String, sink: WireSink): TurnOutcome = try {
                post.into(bodyJson, sink)
            } catch (error: IOException) {
                beforeFailure()
                if (failure == "io") throw error
                if (failure == "local") error("synthetic private protocol bytes")
                TurnOutcome.Failure(
                    "synthetic source transport failure",
                    cause = FailureCause.valueOf(failure),
                    phase = FailurePhase.MID_OUTPUT,
                )
            }
        }

    /** Matches JvmCodeModeCell disposal, including a buffered result racing the source failure. With [parkFirst],
     *  the first advance already waits, as a cell waiting on its next streamed statement does. */
    private inner class ClosingRuntime(private val exit: String, private val parkFirst: Boolean = false) :
        CodeModeRuntime {
        val advancing = CompletableDeferred<Unit>()
        private val closed = CompletableDeferred<Unit>()
        var starts = 0
        override suspend fun start(
            source: String,
            tools: Set<String>,
            descriptions: Map<String, String>,
        ): CodeModeCell = error("live source requires streaming")

        override suspend fun startStreaming(
            source: CodeModeSource,
            tools: Set<String>,
            descriptions: Map<String, String>,
        ): CodeModeCell {
            starts++
            check(source.read() is CodeModeSourcePart.Delta)
            return object : CodeModeCell {
                private var first = !parkFirst
                override suspend fun advance(results: List<CodeModeResult>): CodeModeStep {
                    if (first) {
                        first = false
                        return CodeModeStep.Calls(listOf(call("runtime-first", "Read")))
                    }
                    advancing.complete(Unit)
                    closed.await()
                    if (exit == "cancel") throw CancellationException("synthetic cell cancellation")
                    if (exit == "infrastructure") {
                        throw CodeModeInfrastructureException(
                            CodeModeInfrastructureCategory.PROTOCOL,
                            CodeModeInfrastructureClass.IO,
                        )
                    }
                    if (exit == "buffered") return CodeModeStep.Calls(listOf(call("runtime-buffered", "Edit")))
                    if (exit == "persistence") {
                        throw CodeModePersistenceException(IOException("synthetic state bytes"), false)
                    }
                    check(!closed.isCompleted) { "Code-mode cell is closed" }
                    error("a disposed cell cannot advance")
                }
                override fun close() {
                    closed.complete(Unit)
                }
            }
        }
        override fun close() = Unit
    }
}
