// PORT-OF: ChatStreamTranslator.kt @ e2e0d0f — invariants unchanged: the prose-shape rules (which
// key carries CoT, how a final message dedups against streamed prose, how a refusal fragment
// accumulates) moved out verbatim. Stateless — every buffer stays on the caller and is passed in.
package splice.dialect.chat

import kotlinx.serialization.json.JsonObject
import splice.core.util.JsonScalars
import splice.spi.BufferCapacity

// FILE SCOPE ON PURPOSE: one shared key list walked per delta; as a member it would be rebuilt per
// translator instance (one per turn).
private val REASONING_KEYS = listOf("reasoning_content", "reasoning", "thinking", "reasoning_text")

/** The chat dialect's vendor-shape prose rules: which key carries CoT, how a final message dedups
 *  against streamed prose, how a refusal fragment accumulates. Stateless — every buffer stays on
 *  the caller and is passed in. */
internal class ChatProseFold {

    /** First non-empty cleartext reasoning field on a chat delta/message. */
    fun reasoningDeltaText(obj: JsonObject): String? {
        for (key in REASONING_KEYS) {
            val v = JsonScalars.strOrEmpty(obj[key])
            if (v.isNotEmpty()) return v
        }
        return null
    }

    /** Prefix-aware fold shared by the reasoning and text final-message channels: emit only what the
     *  streamed deltas haven't already carried ("Hello" streamed + "Hello world" final → " world";
     *  full duplicate → nothing; disjoint payload → all of it). A plain contains() check appended
     *  "Hello world" onto "Hello" → "HelloHello world". Known gap (left as-is): a final message that
     *  re-emits the streamed prose with NORMALIZED whitespace is neither a clean prefix nor a
     *  substring, so it falls to the `else` and re-sends in full — a whitespace-aware compare can't be
     *  made provably safe (it would drop legitimately-repeated content). */
    fun unseenSuffix(already: String, final: String): String = when {
        already.isEmpty() -> final
        final.startsWith(already) -> final.substring(already.length)
        already.contains(final) -> ""
        else -> final
    }

    /** CX-08: fold an OpenAI `refusal` field into [buf] from either of its two carriers.
     *
     *  TWO guards, closing two different axes; neither replaces the other.
     *  · TYPE — [strIfString], not [strOrEmpty]. OpenAI types `delta.refusal` as anyOf[string, null]
     *    ("the refusal message generated by the model"), so a vendor that ships it as a did-the-model-
     *    refuse FLAG (`"refusal": false`, `"refusal": 0`) is deviating from the wire contract, and
     *    strOrEmpty would hand back the non-blank strings "false" / "0" and fail 100% of that vendor's
     *    WORKING turns as a provider-reported refusal. A non-string primitive is not a refusal message.
     *  · BLANK — `refusal: ""` / JSON null / whitespace on every frame must never trip the gate.
     *
     *  DELTA-WINS accumulation, NOT [unseenSuffix]. The carriers are (i) incremental `delta.refusal`
     *  fragments and (ii) a whole-copy echo on the final message. Deltas own the buffer: each one is
     *  appended VERBATIM (what the vendor SDK does — openai-python builds `message.refusal` by
     *  concatenating every `delta.refusal`), and the whole-copy carrier is used only when no delta ever
     *  arrived. Running a whole-message dedup over an INCREMENTAL carrier deleted every token that had
     *  occurred before, so a real streamed refusal shipped garbled ("I can't help with that. I can't
     *  help with anything illegal." → "I can't help with that. I anything illegal"); carrying the
     *  model's own words is the entire value of this gate. One condition also kills the double-append.
     *  Capped by the NF-06 buffer law. The refusal is NOT written to the wire — it is the turn's
     *  verdict, not its content. */
    fun appendRefusal(buf: StringBuilder, obj: JsonObject, isDelta: Boolean) {
        val refusal = JsonScalars.strIfString(obj["refusal"])
        // Round-2 review: isBlank() is a WHOLE-VALUE predicate and this is an INCREMENTAL carrier —
        // applying it per-frame silently deleted every whitespace-only fragment (a newline token
        // between sentences, a lone space), shipping the refusal garbled. A FRAGMENT is dropped only
        // when empty; a WHOLE COPY is still dropped when blank, so the blank negative control keeps
        // its teeth. Three statements, not a merged condition: the && form trips ComplexCondition(3).
        if (refusal.isEmpty()) return
        if (!isDelta && refusal.isBlank()) return
        if (!isDelta && buf.isNotBlank()) return
        if (buf.length < BufferCapacity.MAX_BUFFERED_CHARS) buf.append(refusal)
    }
}
