// What Settings says. Copy lives in modules like this one, never inline in a component.
export const T = {
  title: 'Settings',
  lede: 'How splice looks, what it remembers, and how it behaves. Changes apply as you make them; a few wait for a restart and say so.',
  reading: 'Reading the settings…',
  sections: 'Settings sections',
  section: { general: 'General', conversation: 'Conversation', tools: 'Tools', storage: 'Storage', health: 'Health', advanced: 'Advanced' },
  showKey: 'Show this setting’s key',
  saved: 'Saved',
  saving: 'Saving…',
  waits: 'Applies after a restart',
  restartNow: 'Restart now',
  liveOnly: 'In force now, but it did not reach the file, so a restart forgets it:',
  failed: 'That did not save:',
  rejected: 'splice did not accept it:',
  cancel: 'Cancel',
  save: 'Save',
  // General
  appearance: 'Appearance',
  appearanceWhy: 'Follows your computer unless you choose.',
  day: 'Day',
  night: 'Night',
  system: 'Match my computer',
  openAt: 'Open the console at',
  openAtWhy: 'This address only opens on this computer.',
  copy: 'Copy',
  copied: 'Copied',
  warn: 'Warn me when a command is this full',
  warnWhy: 'splice flags a command’s window once it passes this share of its limit.',
  debug: 'Detailed log',
  debugWhy: 'Writes extra lines to the splice log. Turn it on while chasing a problem.',
  // Conversation
  effort: 'How hard the model thinks',
  effortWhy: 'Used when Claude Code sets nothing of its own; each model keeps its default until you pick.',
  effortElsewhere: (value: string): string => `Set to ${value} in Advanced.`,
  effortScope: 'Thinking default for',
  effortScopeWhy: 'Choose whose thinking default to change. The other conversation settings still apply to all commands.',
  effortAll: 'All commands',
  effortInherit: 'Use all commands',
  effortRunning: (value: string) => `Currently running: ${value}.`,
  effortLevel: { '': 'Model default', low: 'Low', medium: 'Medium', high: 'High' },
  effortHelp: { '': 'Let the model choose unless the client sets a level.', low: 'Less thinking for straightforward work. Usually faster.', medium: 'A balance of thinking and speed for everyday work.', high: 'More thinking for difficult work. Can take longer.' },
  effortSaved: (value: string) => `Saved default: ${value}.`,
  effortInherited: 'This command uses the default for all commands unless its client chooses a level.',
  effortReading: 'Reading the thinking default…',
  effortCompare: 'Compare thinking levels',
  inflight: 'Turns at once, per command',
  inflightWhy: 'More turns at once finish sooner but use the provider’s limit faster. Zero means no limit.',
  reasoning: 'Show the model’s reasoning',
  reasoningWhy: 'Some models think before they answer. Choose how Claude Code shows that.',
  // Storage
  history: 'Keep message history for',
  historyWhy: 'splice’s record of which session messaged which. Older days are removed from this computer; nothing is sent anywhere.',
  traces: 'Keep request traces for',
  tracesWhy: 'The turn-by-turn record behind Turns. Older days are deleted.',
  days: (n: number): string => (n === 1 ? '1 day' : `${n} days`),
  git: 'Show git branches in',
  gitWhy: 'Folders beyond your home folder and /tmp where a session’s branch is read.',
  addFolder: 'Add a folder',
  removeFolder: (path: string): string => `Stop showing branches in ${path}`,
  folderAsk: 'Show git branches in which folder?',
  folderWhy: 'The full path of a folder whose repositories splice should read the branch of.',
  folderField: 'Folder path',
  folderInvalid: 'Give the folder’s path, without a colon.',
  openrouter: 'OpenRouter key',
  openrouterWhy: 'Used by the OpenRouter command. splice keeps it in its key store and never shows it again.',
  keySet: 'Saved',
  keyNotSet: 'Not set',
  keyReplace: 'Replace',
  keySetNew: 'Set',
  keyAsk: 'The OpenRouter key',
  keyWhy: 'It is written to splice’s key store and is never shown again.',
  keyField: 'Key',
  keyRemove: 'Remove',
  keyRead: 'A head reads it from the environment or a file first, so this stored one is not the one it uses.',
  // Tools
  sharing: 'Share tools across sessions',
  sharingWhy: 'One process per tool server, handed to every session so any model can call it.',
  toolWhy: (state: string): string => state,
  toolRunning: 'Reads and serves tools for every session that calls it.',
  toolIdle: 'Started when a session first calls it.',
  toolExcluded: 'Left out of sharing until you turn it on.',
  toolsOff: 'Sharing is off, so no server is shared.',
  toolsUnserved: 'This version of splice does not serve its topology, so tools cannot be shared from here.',
  noTools: 'No tool servers are set up.',
  // Health
  healthTitle: 'Everything splice depends on',
  healthChecked: (ago: string): string => `Sign-ins, ports, folders and splice itself, checked ${ago}.`,
  healthUnserved: 'This version of splice does not serve its checks.',
  needsYou: 'Needs you',
  worth: 'Worth a look',
  showAllFindings: (count: number): string => `Show all ${count} findings`,
  showDetails: 'Show the details',
  recheck: 'Check again',
  rechecking: 'Checking…',
  // Advanced
  showKeys: 'Show setting keys',
  showKeysWhy: 'Print each setting’s name under it, the way it is written in splice.toml. Off, only the <> on a row reveals its key.',
  everyOther: 'Every other setting',
  everyOtherWhy: 'The settings this page does not group above, each as its own control, for one command or all.',
  openList: 'Open the full list',
  closeList: 'Close the list',
} as const;

export const AS = {
  scope: 'Which command',
  scopeAll: 'All commands',
  scopeWhy: 'A value set for all commands; a command can override it with its own.',
  none: 'Not set',
  locked: 'splice fixes this value.',
  headOnly: 'Set only for a command of its own: choose the command above.',
  headUnserved: 'This version of splice does not serve its topology, so a command’s own value cannot be written from here.',
  reset: 'Use the value for all commands',
  source: { default: 'Default', 'defaults table': 'splice.toml', 'head override': 'This command’s own', 'state file': 'Set here', env: 'Environment', patch: 'Set here' },
  overriddenBy: (heads: string): string => `A command sets its own: ${heads}.`,
  empty: 'Every setting is in the sections above.',
} as const;
