// The names this page owns in the replacement console, each with what the console does with it. The disposition says what a person
// can do here, not what the daemon does with the name. A name carries exactly one page disposition.
import type { Disposition } from '../../coverage/checks';
import type { PageJob } from '../../coverage/jobs';

export const dispositions: readonly Disposition[] = [
  { kind: 'route', name: '/api/config', disposition: 'editable' },
  { kind: 'route', name: '/api/topology', disposition: 'editable' },
  { kind: 'route', name: '/api/topology/preview', disposition: 'read-only', reason: 'the Settings command instruction editor reads a draft file without saving topology' },
  { kind: 'route', name: '/api/claude-head', disposition: 'read-only', reason: 'a status read; the mode changes through the two action routes beside it' },
  { kind: 'route', name: '/api/claude-head/wrap', disposition: 'editable' },
  { kind: 'route', name: '/api/claude-head/unwrap', disposition: 'editable' },
  { kind: 'route', name: '/api/doctor', disposition: 'read-only' },
  { kind: 'route', name: '/api/doctor/fix/{id}', disposition: 'editable' },
  { kind: 'route', name: '/api/upgrade', disposition: 'editable' },
  { kind: 'route', name: '/api/upgrade/run', disposition: 'read-only' },
  { kind: 'route', name: '/api/playground', disposition: 'editable' },
  { kind: 'route', name: '/api/keys', disposition: 'read-only' },
  { kind: 'route', name: '/api/keys/{name}', disposition: 'editable' },
  { kind: 'route', name: '/api/daemon/restart', disposition: 'editable' },
  { kind: 'route', name: '/api/kept/edges', disposition: 'editable' },
  { kind: 'route', name: '/api/kept/labels', disposition: 'editable' },
  { kind: 'route', name: '/api/kept/turns', disposition: 'editable' },
  { kind: 'route', name: '/api/heads/{head}/trace/kept', disposition: 'editable' },
  { kind: 'route', name: '/api/compact', disposition: 'read-only' },
  { kind: 'route', name: '/api/compaction/instructions', disposition: 'read-only' },
  { kind: 'route', name: '/api/mcp', disposition: 'read-only' },
  { kind: 'verb', name: 'doctor', disposition: 'read-only', via: '/api/doctor' },
  { kind: 'verb', name: 'install', disposition: 'editable', action: 'Fix a problem the health check found', via: '/api/doctor/fix/{id}' },
  { kind: 'verb', name: 'key', disposition: 'editable', action: 'Store or remove an API key', via: '/api/keys/{name}' },
  { kind: 'verb', name: 'restart', disposition: 'editable', action: 'Restart splice', via: '/api/daemon/restart' },
  { kind: 'verb', name: 'upgrade', disposition: 'editable', action: 'Upgrade or roll back splice', via: '/api/upgrade' },
  { kind: 'verb', name: 'version', disposition: 'read-only', via: '/api/doctor' },
  { kind: 'verb', name: 'init', disposition: 'excluded', reason: 'writes the first splice.toml and state before any daemon runs; the console exists only on a running one' },
  { kind: 'verb', name: 'setup', disposition: 'excluded', reason: 'the first-run wizard that installs and starts the daemon this console runs on' },
  { kind: 'verb', name: 'record-launch', disposition: 'excluded', reason: 'the launch shim\'s own call just before it starts the client, recording which command started it; an operator never types it' },
  { kind: 'verb', name: 'pending-login', disposition: 'excluded', reason: 'the sign-in hook\'s own call to cancel a login still waiting; it answers a machine-readable outcome and an operator never types it' },
  { kind: 'verb', name: 'shim-version', disposition: 'excluded', reason: 'the client shim\'s build stamp for the installer\'s own check; doctor shows the versions an operator reads' },
  { kind: 'verb', name: 'dashboard', disposition: 'excluded', reason: 'opens this console' },
  { kind: 'verb', name: 'uninstall', disposition: 'excluded', reason: 'deletes wrapper commands from the operator\'s bin directory, splice itself with --all; destructive, CLI only' },
  { kind: 'knob', name: 'ACTIVITY_RETENTION_DAYS', disposition: 'editable' },
  { kind: 'knob', name: 'ACTIVITY_STORE_HEADS', disposition: 'editable' },
  { kind: 'knob', name: 'AUTH_CACHE_MS', disposition: 'editable' },
  { kind: 'knob', name: 'BUDGET_DEFAULT_ACTION', disposition: 'editable' },
  { kind: 'knob', name: 'CHATGPT_API_BASE', disposition: 'editable' },
  { kind: 'knob', name: 'CODEX_AUTH_PATH', disposition: 'editable' },
  { kind: 'knob', name: 'CONTEXT_WINDOW_OVERRIDE', disposition: 'editable' },
  { kind: 'knob', name: 'CONTROL_PORT', disposition: 'editable' },
  { kind: 'knob', name: 'DEBUG', disposition: 'editable' },
  { kind: 'knob', name: 'EFFORT', disposition: 'editable' },
  { kind: 'knob', name: 'FIRST_BYTE_TIMEOUT_MS', disposition: 'editable' },
  { kind: 'knob', name: 'FOLD_MARKER_TEXT', disposition: 'editable' },
  { kind: 'knob', name: 'FOLD_MAX_CONTINUE', disposition: 'editable' },
  { kind: 'knob', name: 'FOLD_MAX_TIER', disposition: 'editable' },
  { kind: 'knob', name: 'FOLD_REASONING_MODELS', disposition: 'editable' },
  { kind: 'knob', name: 'GROK_AUTH_PATH', disposition: 'editable' },
  { kind: 'knob', name: 'GROK_MODEL', disposition: 'editable' },
  { kind: 'knob', name: 'GROK_PORT', disposition: 'editable' },
  { kind: 'knob', name: 'MATERIALIZATION_HEAP_BYTES', disposition: 'editable' },
  { kind: 'knob', name: 'MAX_INFLIGHT', disposition: 'editable' },
  { kind: 'knob', name: 'MAX_QUEUED', disposition: 'editable' },
  { kind: 'knob', name: 'MAX_REQUEST_BYTES', disposition: 'editable' },
  { kind: 'knob', name: 'MCP_IDLE_TIMEOUT_MS', disposition: 'editable' },
  { kind: 'knob', name: 'MCP_INITIALIZE_TIMEOUT_MS', disposition: 'editable' },
  { kind: 'knob', name: 'MCP_MAX_SERVERS', disposition: 'editable' },
  { kind: 'knob', name: 'MCP_REQUEST_TIMEOUT_MS', disposition: 'editable' },
  { kind: 'knob', name: 'MCP_SLICE', disposition: 'editable' },
  { kind: 'knob', name: 'MESSAGE_EDGES', disposition: 'editable' },
  { kind: 'knob', name: 'MIRROR_REASONING', disposition: 'editable' },
  { kind: 'knob', name: 'PERF_ARCHIVE_RETENTION_DAYS', disposition: 'editable' },
  { kind: 'knob', name: 'PINNED_MODEL', disposition: 'editable' },
  { kind: 'knob', name: 'PORT', disposition: 'editable' },
  { kind: 'knob', name: 'PROGRESS_LINE', disposition: 'editable' },
  { kind: 'knob', name: 'QUOTA_POLL', disposition: 'editable' },
  { kind: 'knob', name: 'QUOTA_POLL_INTERVAL_MS', disposition: 'editable' },
  { kind: 'knob', name: 'REPLAY_REASONING', disposition: 'editable' },
  { kind: 'knob', name: 'REQUEST_READ_TIMEOUT_MS', disposition: 'editable' },
  { kind: 'knob', name: 'RETRY_BACKOFF_BASE_MS', disposition: 'editable' },
  { kind: 'knob', name: 'RETRY_BACKOFF_CAP_MS', disposition: 'editable' },
  { kind: 'knob', name: 'RETRY_BACKOFF_JITTER_PCT', disposition: 'editable' },
  { kind: 'knob', name: 'SHOW_REASONING', disposition: 'editable' },
  { kind: 'knob', name: 'STALL_REANCHOR_MS', disposition: 'editable' },
  { kind: 'knob', name: 'STATUSLINE_GIT_ROOTS', disposition: 'editable' },
  { kind: 'knob', name: 'STREAM_IDLE_MS', disposition: 'editable' },
  { kind: 'knob', name: 'SUMMARY', disposition: 'editable' },
  { kind: 'knob', name: 'SUPERVISOR_UNIT', disposition: 'editable' },
  { kind: 'knob', name: 'TOOL_SURFACE', disposition: 'editable' },
  { kind: 'knob', name: 'TRACE', disposition: 'read-only', reason: 'per head only, in [heads.KEY.overrides]' },
  { kind: 'knob', name: 'TRACE_MAX_BODY_CHARS', disposition: 'editable' },
  { kind: 'knob', name: 'TRACE_RETENTION_DAYS', disposition: 'editable' },
  { kind: 'knob', name: 'TRANSCRIPT_VIEW', disposition: 'editable' },
  { kind: 'knob', name: 'UPSTREAM_RETRIES', disposition: 'editable' },
  { kind: 'knob', name: 'UPSTREAM_TIMEOUT_MS', disposition: 'editable' },
  { kind: 'knob', name: 'USAGE_WARN_PCT', disposition: 'editable' },
  { kind: 'knob', name: 'USAGE_WARN_TOKENS_5H', disposition: 'editable' },
  { kind: 'knob', name: 'WIRE_TAP', disposition: 'read-only', reason: 'per head only, in [heads.KEY.overrides]' },
  { kind: 'knob', name: 'XAI_API_BASE', disposition: 'editable' },
  { kind: 'topology', name: 'claude.share', disposition: 'editable' },
  { kind: 'topology', name: 'compaction.file', disposition: 'editable' },
  { kind: 'topology', name: 'compaction.instructions', disposition: 'editable' },
  { kind: 'topology', name: 'compaction.model[].file', disposition: 'editable' },
  { kind: 'topology', name: 'compaction.model[].instructions', disposition: 'editable' },
  { kind: 'topology', name: 'compaction.model[].model', disposition: 'editable' },
  { kind: 'topology', name: 'compaction.project[].file', disposition: 'editable' },
  { kind: 'topology', name: 'compaction.project[].instructions', disposition: 'editable' },
  { kind: 'topology', name: 'compaction.project[].model', disposition: 'editable' },
  { kind: 'topology', name: 'compaction.project[].path', disposition: 'editable' },
  { kind: 'topology', name: 'daemon.control_port', disposition: 'editable' },
  { kind: 'topology', name: 'daemon.effort', disposition: 'editable' },
  { kind: 'topology', name: 'daemon.fold_marker_text', disposition: 'editable' },
  { kind: 'topology', name: 'daemon.fold_max_continue', disposition: 'editable' },
  { kind: 'topology', name: 'daemon.fold_max_tier', disposition: 'editable' },
  { kind: 'topology', name: 'daemon.fold_reasoning_models', disposition: 'editable' },
  { kind: 'topology', name: 'daemon.mcp_hosting', disposition: 'editable' },
  { kind: 'topology', name: 'daemon.mcp_hosting_exclude', disposition: 'editable' },
  { kind: 'topology', name: 'daemon.mirror_reasoning', disposition: 'editable' },
  { kind: 'topology', name: 'daemon.replay_reasoning', disposition: 'editable' },
  { kind: 'topology', name: 'daemon.show_reasoning', disposition: 'editable' },
  { kind: 'topology', name: 'daemon.state_dir', disposition: 'editable' },
  { kind: 'topology', name: 'daemon.summary', disposition: 'editable' },
  { kind: 'topology', name: 'defaults.*', disposition: 'editable' },
  { kind: 'topology', name: 'heads.*.claude.command', disposition: 'editable' },
  { kind: 'topology', name: 'heads.*.claude.config_dir', disposition: 'editable' },
  { kind: 'topology', name: 'heads.*.claude.isolate', disposition: 'editable' },
  { kind: 'topology', name: 'heads.*.context_window', disposition: 'editable' },
  { kind: 'topology', name: 'heads.*.discovery_prefix', disposition: 'editable' },
  { kind: 'topology', name: 'heads.*.model_slots.*', disposition: 'editable' },
  { kind: 'topology', name: 'heads.*.models[].id', disposition: 'editable' },
  { kind: 'topology', name: 'heads.*.models[].slot', disposition: 'editable' },
  { kind: 'topology', name: 'heads.*.overrides.*', disposition: 'editable' },
  { kind: 'topology', name: 'heads.*.pinned_model', disposition: 'editable' },
  { kind: 'topology', name: 'heads.*.port', disposition: 'editable' },
  { kind: 'topology', name: 'heads.*.provider', disposition: 'editable' },
  { kind: 'topology', name: 'heads.*.rates.*.cache_read', disposition: 'editable' },
  { kind: 'topology', name: 'heads.*.rates.*.cache_write', disposition: 'editable' },
  { kind: 'topology', name: 'heads.*.rates.*.input', disposition: 'editable' },
  { kind: 'topology', name: 'heads.*.rates.*.long_context_cache_read', disposition: 'editable' },
  { kind: 'topology', name: 'heads.*.rates.*.long_context_cache_write', disposition: 'editable' },
  { kind: 'topology', name: 'heads.*.rates.*.long_context_input', disposition: 'editable' },
  { kind: 'topology', name: 'heads.*.rates.*.long_context_output', disposition: 'editable' },
  { kind: 'topology', name: 'heads.*.rates.*.long_context_over_input_tokens', disposition: 'editable' },
  { kind: 'topology', name: 'heads.*.rates.*.output', disposition: 'editable' },
  { kind: 'topology', name: 'heads.*.system_prompt', disposition: 'editable' },
  { kind: 'topology', name: 'heads.*.system_prompt_file', disposition: 'editable' },
  { kind: 'topology', name: 'heads.*.system_prompt_mode', disposition: 'editable' },
  { kind: 'topology', name: 'projects.*.heads.*.system_prompt', disposition: 'editable' },
  { kind: 'topology', name: 'projects.*.heads.*.system_prompt_file', disposition: 'editable' },
  { kind: 'topology', name: 'projects.*.heads.*.system_prompt_mode', disposition: 'editable' },
  { kind: 'topology', name: 'projects.*.system_prompt', disposition: 'editable' },
  { kind: 'topology', name: 'projects.*.system_prompt_file', disposition: 'editable' },
  { kind: 'topology', name: 'projects.*.system_prompt_mode', disposition: 'editable' },
  { kind: 'topology', name: 'providers.*.auth.env', disposition: 'editable' },
  { kind: 'topology', name: 'providers.*.auth.file', disposition: 'editable' },
  { kind: 'topology', name: 'providers.*.auth.kind', disposition: 'editable' },
  { kind: 'topology', name: 'providers.*.base_url', disposition: 'editable' },
  { kind: 'topology', name: 'providers.*.default_context_window', disposition: 'editable' },
  { kind: 'topology', name: 'providers.*.dialect', disposition: 'editable' },
  { kind: 'topology', name: 'providers.*.discovery.exclude', disposition: 'editable' },
  { kind: 'topology', name: 'providers.*.discovery.include', disposition: 'editable' },
  { kind: 'topology', name: 'providers.*.extra_headers.*', disposition: 'editable' },
  { kind: 'topology', name: 'providers.*.extra_windows[].context_window', disposition: 'editable' },
  { kind: 'topology', name: 'providers.*.extra_windows[].id', disposition: 'editable' },
  { kind: 'topology', name: 'providers.*.extra_windows[].max_context_window', disposition: 'editable' },
  { kind: 'topology', name: 'providers.*.local', disposition: 'editable' },
  { kind: 'topology', name: 'providers.*.models[].client_model', disposition: 'editable' },
  { kind: 'topology', name: 'providers.*.models[].compaction_reserve_tokens', disposition: 'editable' },
  { kind: 'topology', name: 'providers.*.models[].context_window', disposition: 'editable' },
  { kind: 'topology', name: 'providers.*.models[].description', disposition: 'editable' },
  { kind: 'topology', name: 'providers.*.models[].id', disposition: 'editable' },
  { kind: 'topology', name: 'providers.*.models[].label', disposition: 'editable' },
  { kind: 'topology', name: 'providers.*.models[].rates.cache_read', disposition: 'editable' },
  { kind: 'topology', name: 'providers.*.models[].rates.cache_write', disposition: 'editable' },
  { kind: 'topology', name: 'providers.*.models[].rates.input', disposition: 'editable' },
  { kind: 'topology', name: 'providers.*.models[].rates.long_context_cache_read', disposition: 'editable' },
  { kind: 'topology', name: 'providers.*.models[].rates.long_context_cache_write', disposition: 'editable' },
  { kind: 'topology', name: 'providers.*.models[].rates.long_context_input', disposition: 'editable' },
  { kind: 'topology', name: 'providers.*.models[].rates.long_context_output', disposition: 'editable' },
  { kind: 'topology', name: 'providers.*.models[].rates.long_context_over_input_tokens', disposition: 'editable' },
  { kind: 'topology', name: 'providers.*.models[].rates.output', disposition: 'editable' },
  { kind: 'topology', name: 'providers.*.models_url', disposition: 'editable' },
  { kind: 'topology', name: 'providers.*.quirks.account_id_header', disposition: 'editable' },
  { kind: 'topology', name: 'providers.*.quirks.block_allowlist', disposition: 'editable' },
  { kind: 'topology', name: 'providers.*.quirks.cache_key', disposition: 'editable' },
  { kind: 'topology', name: 'providers.*.quirks.chat_effort_vocabulary.default', disposition: 'editable' },
  { kind: 'topology', name: 'providers.*.quirks.chat_effort_vocabulary.levels.*', disposition: 'editable' },
  { kind: 'topology', name: 'providers.*.quirks.code_mode', disposition: 'editable' },
  { kind: 'topology', name: 'providers.*.quirks.code_mode_heap', disposition: 'editable' },
  { kind: 'topology', name: 'providers.*.quirks.code_mode_models', disposition: 'editable' },
  { kind: 'topology', name: 'providers.*.quirks.code_mode_timeout_ms', disposition: 'editable' },
  { kind: 'topology', name: 'providers.*.quirks.code_mode_workers', disposition: 'editable' },
  { kind: 'topology', name: 'providers.*.quirks.compact_effort', disposition: 'read-only', reason: 'retired, the daemon refuses it' },
  { kind: 'topology', name: 'providers.*.quirks.effort_ceiling', disposition: 'editable' },
  { kind: 'topology', name: 'providers.*.quirks.map_thinking_adaptive', disposition: 'editable' },
  { kind: 'topology', name: 'providers.*.quirks.mfjs', disposition: 'editable' },
  { kind: 'topology', name: 'providers.*.quirks.parallel_tool_calls', disposition: 'editable' },
  { kind: 'topology', name: 'providers.*.quirks.reanchor_prefill', disposition: 'editable' },
  { kind: 'topology', name: 'providers.*.quirks.reasoning_cache', disposition: 'editable' },
  { kind: 'topology', name: 'providers.*.quirks.reasoning_effort', disposition: 'editable' },
  { kind: 'topology', name: 'providers.*.quirks.slot_affinity', disposition: 'editable' },
  { kind: 'topology', name: 'providers.*.quirks.store', disposition: 'editable' },
  { kind: 'topology', name: 'providers.*.quirks.stream_usage', disposition: 'editable' },
  { kind: 'topology', name: 'providers.*.quirks.strip_cache_control', disposition: 'editable' },
  { kind: 'topology', name: 'providers.*.quirks.strip_sampling_params', disposition: 'editable' },
  { kind: 'topology', name: 'providers.*.quirks.summary_delivery', disposition: 'editable' },
  { kind: 'topology', name: 'providers.*.quirks.summary_field', disposition: 'editable' },
  { kind: 'topology', name: 'providers.*.quirks.synthesize_signatures', disposition: 'editable' },
  { kind: 'topology', name: 'providers.*.quirks.tool_choice', disposition: 'editable' },
  { kind: 'topology', name: 'providers.*.quirks.tool_name_cap', disposition: 'editable' },
  { kind: 'topology', name: 'providers.*.quirks.tool_surface.defer', disposition: 'editable' },
  { kind: 'topology', name: 'providers.*.quirks.tool_surface.defer_prefixes', disposition: 'editable' },
  { kind: 'topology', name: 'providers.*.quirks.tool_surface.eager', disposition: 'editable' },
  { kind: 'topology', name: 'providers.*.quirks.tool_surface.enabled', disposition: 'editable' },
  { kind: 'topology', name: 'providers.*.quirks.tool_surface.min_deferred', disposition: 'editable' },
  { kind: 'topology', name: 'providers.*.quirks.tool_surface.search_limit', disposition: 'editable' },
  { kind: 'topology', name: 'providers.*.quirks.tool_surface.search_rounds', disposition: 'editable' },
  { kind: 'topology', name: 'providers.*.quirks.websocket', disposition: 'editable' },
  { kind: 'topology', name: 'providers.*.quirks.zstd_request_body', disposition: 'editable' },
  { kind: 'topology', name: 'providers.*.window_rules[].context_window', disposition: 'editable' },
  { kind: 'topology', name: 'providers.*.window_rules[].prefix', disposition: 'editable' },
];

export const job: PageJob = {
  question: 'How is splice set up, and is it healthy?',
  leaves: 'Every setting and the configuration file, what needs a restart, the version and health of the install, and what is kept on this computer.',
  actions: [
    { name: 'Change a setting' },
    { name: 'Edit the configuration file' },
    { name: 'Set a plan\'s instructions' },
    { name: 'Wrap or unwrap the claude command' },
    { name: 'Share tools between plans' },
    { name: 'Store or remove an API key' },
    { name: 'Fix a problem the health check found' },
    { name: 'Upgrade or roll back splice' },
    { name: 'Restart splice' },
    { name: 'Try a plan with one prompt' },
    { name: 'Clear what splice keeps' },
  ],
};
