// What a session's page says. Copy lives in modules like this one, never inline in a component.
export const P = {
  sessions: 'Sessions',
  conversation: 'Conversation',
  filterLabel: 'Show',
  messages: 'Messages',
  toolsOnly: 'Tools only',
  handoffsOnly: 'Hand-offs',
  you: 'You',
  assistant: 'Assistant',
  system: 'Claude Code note',
  handoffFrom: 'Hand-off from',
  handoffTo: 'Hand-off to',
  handoffMissing: 'What was handed over is no longer in the sender’s transcript.',
  running: 'running',
  noOutput: 'no output',
  ranTool: 'Input',
  outputCut: 'Only the start of this output is shown.',
  inputCut: 'Only the start of this input was kept.',
  everywhere: 'Every occurrence in the file was replaced.',
  readLines: (from: number, to: number): string => (from === to ? `Line ${from}` : `Lines ${from} to ${to}`),
  showAll: (lines: number): string => (lines > 1 ? `Show all ${lines.toLocaleString('en-US')} lines` : 'Show all of it'),
  showFewer: 'Show less',
  loadEarlier: 'Show earlier messages',
  loading: 'Reading the conversation…',
  noMessages: 'Nothing has been said yet.',
  transcriptOff: 'Reading transcripts is switched off:',
  transcriptMissing: 'This session has no transcript on disk.',
  showPath: 'Show the path',
  lookedIn: 'The daemon looked in:',
  notFound: 'This session is not open, and it is not in the saved history.',
  team: 'The team',
  workingWith: 'Working with',
  alone: 'Working alone. Hand-offs to and from other sessions show here.',
  lead: 'Lead',
  received: 'received',
  sent: 'sent',
  noteLabel: 'Send a note to this session',
  noteHint: 'Write a note for this session…',
  noteWhat: 'It reaches the session as a message from another session, not as you typing. It cannot answer a permission prompt or run a command.',
  noteSend: 'Send the note',
  noteSending: 'Sending…',
  noteSent: 'Sent. splice cannot tell whether the session has read it yet.',
  noteTooLong: (limit: number): string => `A note is at most ${limit.toLocaleString('en-US')} characters.`,
  noteNotRunning: 'This session is not running, so it cannot take a note.',
  untitled: 'Untitled session',
  elapsed: 'for',
  back: 'Back to Sessions',
  showEdit: '+',
  removed: '−',
} as const;
