// What a session's page says. Copy lives in modules like this one, never inline in a component.
export const P = {
  sessions: 'Sessions',
  conversation: 'Conversation',
  filterLabel: 'Show',
  messages: 'Messages',
  toolsOnly: 'Tools only',
  handoffsOnly: 'Hand-offs',
  you: 'You',
  assistant: 'Assistant',
  handoffFrom: 'Hand-off from',
  handoffTo: 'Hand-off to',
  handoffMissing: 'What was handed over is no longer in the sender’s transcript.',
  running: 'running',
  noOutput: 'no output',
  ranTool: 'Input',
  outputCut: 'Only the start of this output is shown.',
  loadEarlier: 'Show earlier messages',
  loading: 'Reading the conversation…',
  noMessages: 'Nothing has been said yet.',
  transcriptOff: 'Reading transcripts is switched off:',
  transcriptMissing: 'This session has no transcript on disk. The daemon looked in:',
  notFound: 'This session is not open, and it is not in the saved history.',
  team: 'The team',
  workingWith: 'Working with',
  alone: 'Working alone. Hand-offs to and from other sessions show here.',
  lead: 'Lead',
  received: 'received',
  sent: 'sent',
  composerHint: 'Message the session, or reply to the hand-off…',
  composerPending: 'Pending: splice cannot send to a session yet',
  send: 'Send',
  untitled: 'Untitled session',
  elapsed: 'for',
  back: 'Back to Sessions',
  showEdit: '+',
  removed: '−',
} as const;
