// What the Playground says. Copy lives in modules like this one, never inline in a component.
export const G = {
  title: 'Playground',
  lede: 'One prompt to several models, with their answers side by side. Nothing is recorded.',
  prompt: 'Prompt',
  placeholder: 'Ask every model the same thing',
  send: 'Send',
  sending: 'Asking…',
  sendHint: 'Ctrl or ⌘ and Enter sends',
  clear: 'Clear',
  add: 'Add a model',
  lanes: 'Answers',
  command: 'Command',
  model: 'Model',
  pick: 'Choose a command',
  remove: (model: string): string => `Remove ${model}`,
  waiting: 'Waiting for a prompt.',
  asking: 'Asking…',
  answered: (status: number, seconds: string): string => `Answered with ${status} in ${seconds} s`,
  status: (status: number, seconds: string): string => `Status ${status} after ${seconds} s`,
  refused: (who: string, said: string): string => `${who} refused the request: ${said}`,
  refusedBare: (who: string, status: number): string => `${who} refused the request with status ${status}.`,
  stopped: (who: string, said: string): string => `${who} stopped with an error: ${said}`,
  tokens: (input: string, output: string): string => `${input} tokens in, ${output} out`,
  noText: 'The reply carries no text. Its body is below.',
  failed: 'That did not run:',
  exchange: 'The request and the reply',
  sent: 'What splice sent',
  reply: 'What came back',
  forwarded: (names: readonly string[]): string => (names.length === 1
    ? `${names[0] ?? ''} signs in with Claude Code's own login, which the Playground does not have, so it is not offered here.`
    : `${names.slice(0, -1).join(', ')} and ${names.at(-1) ?? ''} sign in with Claude Code's own login, which the Playground does not have, so they are not offered here.`),
  pinnedModel: (id: string): string => `The pinned model, ${id}`,
  anyModel: 'Command default',
  none: 'No command can be tried yet.',
  noneWhy: 'Add a command on Models, then come back.',
} as const;
