// Every word this page prints. S: labels, three words or fewer, sentence case. H: help, one
// sentence of twelve words or fewer, shown on hover or focus. U: a unit beside a figure.
export const S = {
  title: 'Fleet',
  about: 'About the fleet',
  byHead: 'By head',
  byProvider: 'By provider',
  attentionFirst: 'Attention first',
  heads: 'Heads',
  head: 'Head',
  provider: 'Provider',
  state: 'State',
  model: 'Model',
  dialect: 'Dialect',
  account: 'Account',
  inflight: 'In flight',
  window: 'Window',
  firstByte: 'First byte',
  lastTurn: 'Last turn',
  port: 'Port',
  version: 'Version',
  refreshError: 'Refresh error',
  nearestLimit: 'Nearest limit',
  aboutFirstByte: 'About first byte',
  addBackend: 'Add backend',
  detail: 'Head detail',
  openHead: 'Open head',
  close: 'Close',
  lifecycle: 'Lifecycle',
  start: 'Start',
  stop: 'Stop',
  restart: 'Restart',
  stopNow: 'Stop now',
  restartNow: 'Restart now',
  sent: 'Sent',
  /** The opened head's own values, the ones it sets over the global settings. */
  knobs: 'Own settings',
  pool: 'Account pool',
  next: 'Next',
  openLog: 'Open log',
  signIn: 'Sign in',
  none: 'None',
  /** The last turn of a head with one running now: the word the team timeline gives a live turn. */
  running: 'Running',
  noHeads: 'No heads yet',
  fieldsUnavailable: 'Model list unavailable',
  poolsUnavailable: 'Pools unavailable',
  noAccounts: 'No accounts',
  oneLogin: 'One login',
  noPool: 'No pool',
  noneAvailable: 'None available',
  /** A head's state as its badge prints it: the entity's cause, in the page's voice. */
  stateName: {
    ok: 'OK',
    down: 'Down',
    unhealthy: 'Failing',
    'version mismatch': 'Mismatch',
    'signed out': 'Signed out',
    'key missing': 'No key',
    'login expired': 'Expired',
    'account excluded': 'Excluded',
    'queue full': 'Queue full',
    'restart needed': 'Restart needed',
  },
  /** The four buckets the fleet's split bar counts heads into. */
  healthName: {
    ok: 'OK',
    attention: 'Attention',
    failing: 'Failing',
    down: 'Down',
  },
} as const;

export const H = {
  about: 'Every head, its health, and the account each will use next.',
  firstByte: "Time to first byte over the fleet's recent turns.",
  noHeads: 'Run splice setup, then splice add for each further provider.',
  fields: 'This splice version does not serve the topology or model list.',
  pools: 'This splice version does not serve accounts.',
  oneLogin: 'A Claude head uses the Claude Code login it started with.',
  noAccounts: 'Sign one in on the accounts page.',
  apiKey: 'An API key head sends every request with its one key.',
  local: 'This head needs no login.',
  noneAvailable: 'Every account is signed out, excluded or at its limit.',
  down: 'This head is not running; start it below.',
  unhealthy: 'It runs but fails its health check; the log says why.',
  mismatch: 'It runs a different splice version than the daemon; restart it.',
  signedOut: 'No login is saved for this head.',
  keyMissing: 'No API key; set one and the next request uses it.',
  keyMissingBare: 'No API key; set one with splice key set.',
  loginExpired: 'The login could not be refreshed; sign in again.',
  accountExcluded: 'The next account is excluded; the pool below says why.',
  queueFull: 'Every slot is busy and the queue is at its limit.',
  restartNeeded: 'The config changed since this head started; restart it.',
} as const;
