export const A = {
  title: 'Accounts',
  lede: 'Your provider logins, their limits, and the order splice uses them.',
  reading: 'Reading provider accounts…',
  reload: 'Refresh accounts',
  add: 'Sign in to another account',
  signIn: 'Sign in',
  renew: 'Sign in again',
  refresh: 'Refresh login',
  refreshing: 'Refreshing…',
  signedIn: 'Signed in',
  notSignedIn: 'Not signed in',
  refused: 'Credential refused',
  excluded: 'Temporarily excluded',
  unknownLogin: 'Login not reported yet',
  primary: 'Primary account',
  next: 'Next account',
  serving: 'Last selected',
  limitReached: 'Limit reached',
  heldUntil: 'Held until',
  ct: 'CT',
  pinRule: 'A manual pin overrides this order while its account is available.',
  nextBecause: 'Splice tries the first available account in this order, skipping accounts at their limit.',
  pinned: 'Pinned',
  fiveHours: '5 hours',
  weekly: 'Weekly',
  shortWindow: 'Short window',
  longWindow: 'Long window',
  unreported: 'Not reported',
  oldReading: 'Previous window',
  resets: 'Resets',
  reset: 'Reset',
  used: (pct: number) => `${Math.round(pct)}% used`,
  days: (days: number) => `${days} days`,
  hours: (hours: number) => `${hours} hours`,
  modelWindow: (name: string, model: string) => `${name} · ${model}`,
  noAccounts: 'No saved accounts',
  noAccountsWhy: 'Sign in to add an account for this provider.',
  claude: 'Claude',
  claudeNative: 'claude',
  claudeSplice: 'claude-splice',
  nativeWhy: 'The login used by Claude Code in ~/.claude.',
  spliceWhy: 'The separate login used by claude-splice in its own configuration folder.',
  failover: 'When an account reaches its limit',
  orderWhy: 'Drag accounts into the order splice should try them. A turn already running keeps its account.',
  orderReading: 'Reading failover order…',
  orderSaving: 'Saving failover order…',
  orderSaved: 'Failover order saved',
  orderUnavailable: 'Account ordering is unavailable for this head.',
  orderSingle: 'This head uses one login. There is no account order to change.',
  moveUp: (name: string) => `Move ${name} earlier`,
  moveDown: (name: string) => `Move ${name} later`,
  drag: (name: string) => `Drag ${name} to change failover order`,
  spent: 'Budget used',
  budgetScope: 'Shared by all accounts on this head.',
  budgetMissing: 'Budget information is not available in this daemon yet.',
  invalidCap: 'Enter a budget greater than zero.',
  left: 'Left in budget',
  cap: 'Daily budget',
  headBudget: (head: string) => `${head} daily budget`,
  noCap: 'No budget cap',
  editCap: 'Edit cap',
  save: 'Save',
  cancel: 'Cancel',
  budgetUnread: 'Budget not reported',
  saving: 'Saving…',
} as const;
