import { localZonedInstantText } from '../../lib/heads';

const heldAccounts = 'If every selectable account is held, splice tries the one whose reset is nearest and reports its limit.';

export const A = {
  title: 'Accounts',
  lede: 'Your provider logins, their limits, and the order splice uses them.',
  reading: 'Reading provider accounts…',
  reload: 'Refresh accounts',
  add: 'Sign in to another account',
  signIn: 'Sign in',
  renew: 'Sign in again',
  refresh: 'Refresh sign-in',
  refreshing: 'Refreshing…',
  signedIn: 'Signed in',
  notSignedIn: 'Not signed in',
  refused: 'Credential refused',
  excluded: 'Temporarily excluded',
  unknownLogin: 'Login not reported',
  unknownLoginWhy: 'Refresh accounts to check this login, or sign in to add it.',
  primary: 'Primary account',
  keyReady: 'API key configured',
  keyMissing: 'API key missing',
  keyWhy: 'This command uses an API key, not a browser login. Change the key in its provider configuration.',
  localWhy: 'This command uses a runtime on this computer. There is no provider sign-in to change.',
  next: 'Next account',
  serving: 'Last selected',
  limitReached: 'Limit reached',
  heldUntil: 'Held until',
  instant: localZonedInstantText,
  pinRule: 'A manual pin overrides this order while its account is available.',
  nextBecause: 'Splice tries the first available account in this order, skipping accounts at their limit.',
  pinned: 'Pinned',
  fiveHours: '5 hours',
  weekly: 'Weekly',
  shortWindow: 'Short window',
  longWindow: 'Long window',
  unreported: 'Not reported',
  readingOld: 'Usage reading is out of date',
  resets: 'Resets',
  reset: 'Window reset',
  used: (pct: number) => `${Math.round(pct)}% used`,
  days: (days: number) => `${days} days`,
  hours: (hours: number) => `${hours} hours`,
  modelWindow: (name: string, model: string) => `${name} · ${model}`,
  noAccounts: 'No saved accounts',
  noAccountsWhy: 'Sign in to add an account for this provider.',
  claude: 'Claude',
  claudeNative: 'claude',
  claudeSplice: 'claude-splice',
  nativeWhy: 'The login used by Claude Code in ~/.claude.',
  spliceWhy: 'The separate login used by claude-splice in its own configuration folder.',
  failover: 'When an account reaches its limit',
  orderWhy: 'Drag accounts into the order splice should try them. A turn already running keeps its account.',
  orderReading: 'Reading failover order…',
  orderSaving: 'Saving failover order…',
  orderSaved: 'Failover order saved',
  orderDefault: `No order is saved. Splice first tries an available pinned account. Each session keeps its account while it remains available, before choosing the account with quota whose weekly reset comes soonest. The five-hour reset breaks ties. Unknown quota comes last. Your saved order overrides this default after any available manual pin. ${heldAccounts}`,
  orderYours: `You set this order. Splice starts after any available manual pin by trying saved accounts in order. It then tries unlisted accounts as fallbacks: the primary account, the session’s previous account, and the account with quota whose weekly reset comes soonest. The five-hour reset breaks ties. Unknown quota comes last. It stays until you change it or go back to the default. ${heldAccounts}`,
  orderReset: 'Use the default order',
  orderUnavailable: 'Account ordering is unavailable for this command.',
  orderSingle: 'This command uses one login. There is no account order to change.',
  orderSingleAccount: 'This command uses one account. There is no account order to change.',
  moveUp: (name: string) => `Move ${name} earlier`,
  moveDown: (name: string) => `Move ${name} later`,
  drag: (name: string) => `Drag ${name} to change failover order`,
  spent: 'Budget used',
  budgetScope: 'Shared by all accounts on this command.',
  noCapWhy: 'No daily cap is set. Set a daily cap to limit spending.',
  setCap: 'Set daily cap',
  spendUnknown: 'Spending is not reported. A remaining balance is available after priced requests.',
  budgetMissing: 'Budget information is not available in this daemon yet.',
  invalidCap: 'Enter a budget greater than zero.',
  left: 'Left in budget',
  cap: 'Daily budget',
  headBudget: (head: string) => `${head} daily budget`,
  noCap: 'No budget cap',
  editCap: 'Edit cap',
  save: 'Save',
  cancel: 'Cancel',
  budgetUnread: 'Budget not reported',
  saving: 'Saving…',
} as const;
