// NEW: V4-117 (error taxonomy, 2026-09-18) — the drift leg for the operator-facing matrix table.
//
// THE TABLE IS GENERATED FROM THE CODE, NOT MAINTAINED ALONGSIDE IT. AGENTS.md carries one
// marker-delimited block, RetryMatrix.table() renders the same thing from the real matrix, and this
// test fails byte-for-byte if the two ever differ. A hand-maintained copy would be a SECOND author
// for facts the matrix already owns, and the two would disagree in silence — the failure this row
// exists to remove, one level up.
//
// REGENERATING IT IS A COPY, NOT A RE-DERIVATION: every run writes the rendered table to
// build/retry-matrix-rendered.md, so when this test reddens the fix is to paste that file's
// contents between the markers rather than to work out what the table should say.
//
// No package declaration, matching every sibling test in this directory (see
// RetryMatrixCoverageTest for why that is correct rather than an omission).
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test
import splice.spi.RetryMatrix
import java.io.File

class RetryMatrixTableTest {

    @Test
    fun `the committed table is exactly what the matrix renders`() {
        val rendered = RetryMatrix.table()
        // Gradle runs a test with the module directory as the working directory, so the repo root
        // is two levels up and the artifact lands in this module's own build dir.
        val artifact = File("build/retry-matrix-rendered.md")
        artifact.parentFile?.mkdirs()
        artifact.writeText(rendered + "\n")

        val agents = File("../../AGENTS.md")
        assertTrue(agents.isFile, "AGENTS.md not found at ${agents.absolutePath}")

        val committed = blockBetweenMarkers(agents.readText())
        assertEquals(
            rendered,
            committed,
            "the AGENTS.md retry-matrix block has drifted from the code — paste " +
                "${artifact.absolutePath} between the markers",
        )
    }

    /** The text strictly between the BEGIN and END markers, without either marker or its newline. */
    private fun blockBetweenMarkers(text: String): String {
        val begin = text.indexOf(BEGIN_MARKER)
        assertTrue(begin >= 0, "AGENTS.md has no $BEGIN_MARKER")
        val from = text.indexOf('\n', begin) + 1
        val end = text.indexOf(END_MARKER)
        assertTrue(end > from, "AGENTS.md has no $END_MARKER after the begin marker")
        return text.substring(from, end).trimEnd('\n')
    }
}

// Private top-level consts rather than a companion object: the campaign wall forbids companions, and
// these are two strings with no behaviour.
private const val BEGIN_MARKER = "<!-- BEGIN retry-matrix (generated by RetryMatrix.table) -->"
private const val END_MARKER = "<!-- END retry-matrix -->"
