import { countWord } from '../../lib/format';

export const T = {
  title: 'Teams',
  lede: 'The sessions working on each project, together.',
  reading: 'Reading the project teams…',
  members: 'Sessions',
  work: 'Latest activity',
  modelUnknown: 'Model not reported',
  modelReading: 'Reading the model…',
  lastModel: (name: string) => `Last model: ${name}`,
  folderGrouping: 'Grouped by the reported working folder; repository details were not read.',
  handoffs: 'Messages and handoffs',
  handoffsWhy: 'Recent messages between these sessions. Open a message to read what was handed over.',
  readingHandoffs: 'Reading the handoffs…',
  noHandoffs: 'No handoffs recorded between these sessions.',
  allHandoffs: 'Show more handoffs',
  readingMessage: 'Reading the message…',
  missingMessage: 'The message text is no longer available.',
  notReported: 'Current work is not reported.',
  staleWhy: 'The session is still running, but its last status update is old.',
  project: 'Project settings',
  unresolved: 'Project not reported',
  unresolvedWhy: 'These sessions report neither a repository nor a working folder. Their project is unknown.',
  empty: 'No sessions are open.',
  emptyWhy: 'Sessions sharing a repository appear together here. Saved teams remain available below.',
  saved: 'Saved teams',
  savedWhy: 'Goals, assigned roles and standing instructions. Project groups above need no saved team.',
  savedReading: 'Reading the saved teams…',
  savedNone: 'No saved teams.',
  savedGoal: 'No goal written.',
  to: 'to',
  usage: 'Requests in the last 24 hours',
  usageReading: 'Reading project usage…',
  usageUnavailable: 'This splice does not report request usage yet.',
  usageNone: 'No requests were recorded for these sessions in this window.',
  usagePartial: 'Only the retained, session-attributed requests are included. Some readings are missing.',
  usageTokens: 'Input / output tokens',
  usageCost: 'Estimated API cost',
  usageUnknown: 'Not reported',
  atLeast: (value: string) => `At least ${value}`,
  seats: (n: number) => `${countWord(n)} ${n === 1 ? 'session' : 'sessions'}`,
  working: (n: number) => `${n} working`,
  old: (n: number) => `${n} ${n === 1 ? 'status' : 'statuses'} old`,
} as const;
