// What the Sessions page says. Copy lives in modules like this one, never inline in a component.
import { SW } from '../../lib/words-sessions';

export const P = {
  title: 'Sessions',
  groupBy: 'Group by',
  byState: 'State',
  byRepo: 'Repo',
  byCommand: 'Command',
  byTeam: 'Team',
  search: 'Find a session',
  needs: 'Needs you',
  needsWhy: 'A person has to act; they stay on top until they do.',
  working: 'Working',
  workingWhy: 'Drag the handle or use Move to reorder. Your order stays between reads.',
  drag: (name: string): string => `Drag ${name} to reorder`,
  moveEarlier: (name: string): string => `Move ${name} earlier`,
  moveLater: (name: string): string => `Move ${name} later`,
  earlierMove: 'Move earlier',
  laterMove: 'Move later',
  idle: 'Idle',
  idleWhy: SW.idle,
  gone: 'Ended',
  goneWhy: 'This registration is not available on this daemon.',
  earlier: 'Earlier sessions',
  earlierWhy: 'Found by name or repository in the saved history.',
  more: 'Show more',
  searching: 'Searching the history…',
  historyOff: 'History search is off:',
  historyNone: 'No earlier session matches.',
  unattributed: 'Not filed',
  unknownHead: 'Not started through splice',
  empty: 'No sessions are open.',
  emptyWhy: 'A Claude Code session started through one of your commands shows here.',
  reading: 'Reading the sessions…',
  lastFrom: 'last message from',
  lastTo: 'last message to',
  messaged: (peers: number): string => `messaged ${peers} sessions`,
  needsAnswer: 'Waiting for your answer',
  login: (name: string): string => `Login: ${name}`,
  loginUnknown: 'Login not reported',
  loginNoId: 'A login cannot be attributed until the session has an id.',
  loginUnattributed: 'No known login is attributed to this session.',
  loginHistoryLimited: 'The request history is incomplete, so this session’s login is unknown.',
} as const;
