// What the Sessions page says. Copy lives in modules like this one, never inline in a component.
import { SW } from '../../lib/words-sessions';

export const P = {
  title: 'Sessions',
  groupBy: 'Group by',
  byState: 'State',
  byRepo: 'Repo',
  byCommand: 'Command',
  byTeam: 'Team',
  search: 'Find a session',
  needs: 'Needs you',
  needsWhy: 'A person has to act; they stay on top until they do.',
  working: 'Working',
  workingWhy: 'Drag to reorder; the order is yours.',
  idle: 'Idle',
  idleWhy: SW.idle,
  gone: 'Ended',
  goneWhy: 'The process exited.',
  earlier: 'Earlier sessions',
  earlierWhy: 'Found by name or repository in the saved history.',
  more: 'Show more',
  searching: 'Searching the history…',
  historyOff: 'History search is off:',
  historyNone: 'No earlier session matches.',
  unattributed: 'Not filed',
  unknownHead: 'Not started through splice',
  empty: 'No sessions are open.',
  emptyWhy: 'A Claude Code session started through one of your commands shows here.',
  reading: 'Reading the sessions…',
  lastFrom: 'last message from',
  lastTo: 'last message to',
  messaged: (peers: number): string => `messaged ${peers} sessions`,
  needsAnswer: 'Waiting for your answer',
  login: (name: string): string => `Login: ${name}`,
  loginUnknown: 'Login not reported',
} as const;
