// Every word this widget prints. S: labels, three words or fewer, sentence case. H: help and the
// line an answer reads back, one sentence of twelve words or fewer.
export const S = {
  title: 'Connect a plan',
  profile: 'Provider',
  name: 'Plan name',
  baseUrl: 'Provider address',
  command: 'Command',
  models: 'Models',
  modelId: 'Model id',
  window: 'Context window',
  addModel: 'Add model',
  open: 'Continue',
  head: 'Plan',
  signsIn: 'Signs in',
  credential: 'Credential',
  signIn: 'Sign in',
  checks: 'Checks',
  runChecks: 'Run checks',
  liveCheck: 'Live check',
  save: 'Save provider',
  saveArmed: 'Save and restart',
  discard: 'Discard',
  written: 'Written to',
  wrapper: 'Wrapper',
  restart: 'Restart',
  linked: 'Linked',
  present: 'Present',
  missing: 'Missing',
  noKey: 'No key needed',
  passed: 'Passed',
  failed: 'Failed',
  aboutChecks: 'About the checks',
  aboutSignIn: 'About sign-in',
  aboutProfile: 'About this profile',
  connected: (plan: string): string => `${plan} connected`,
  savedPlan: (plan: string): string => `${plan} saved`,
  tryIt: 'Try it',
  retryConnect: 'Retry connection',
  modelUsed: 'Model used',
  reply: 'Reply',
} as const;

/** How a head proves who it is, as a fact's value. */
export const SIGN_IN_BY: Readonly<Record<string, string>> = {
  login: 'Browser login',
  key: 'API key',
  none: 'Claude login',
};

export const H = {
  forwarded: 'Your Claude login is forwarded at launch; nothing to sign in.',
  localNoKey: 'No key is needed for this local runtime.',
  key: (name: string): string => `Store the key it reads from ${name}; the checks read it next.`,
  login: 'Sign in in the browser; this form follows the login.',
  checks: 'Splice checks this plan before saving it.',
  live: 'A live check sends one short turn through the new plan.',
  draining: 'Splice is restarting; the new plan appears once it is back.',
  launch: 'Type this command in your terminal after the restart.',
  waiting: (count: number): string => `The restart waits for ${count} compaction(s) to finish.`,
  loading: 'Reading the profiles splice can add.',
  unavailable: 'This plan is unavailable in this splice build.',
  noReply: 'The provider returned no readable reply.',
  noModel: 'The provider returned no model name.',
  providerStatus: (status: number): string => `The provider answered HTTP ${status}.`,
  planName: (profile: string): string => ({ codex: 'ChatGPT', grok: 'Grok', kimi: 'Kimi', muse: 'Muse', openrouter: 'OpenRouter', local: 'local' } as Record<string, string>)[profile] ?? profile,
  selectedPlan: (profile: string): string => `Connect your ${H.planName(profile)} plan.`,
  runCommand: (command: string): string => `Run ${command}.`,
  finishConnection: 'Saving your signed-in plan and restarting splice.',
  restartManually: 'Run splice restart, then return to try the plan.',
  tryPrompt: 'Say hello and name your model.',
  tryCost: 'This short real provider test used a tiny bit of your plan.',
} as const;
