// What the shell says. Copy lives in modules like this one, never inline in a component.
export const C = {
  brand: 'splice',
  unlock: 'Unlock',
  keyLabel: 'Management key',
  unlockAsk: 'Paste the management key to open the console.',
  unlockRejected: 'That key was not accepted. Paste it again.',
  unlockHint: 'It is the file mgmt-key in splice’s state folder. splice dashboard opens this page with it.',
  accounts: 'Accounts',
  requests: 'Requests',
  teams: 'Teams',
  models: 'Models',
  playground: 'Playground',
  sessions: 'Sessions',
  usage: 'Usage',
  settings: 'Settings',
  running: 'Daemon running',
  checking: 'Checking daemon',
  notAnswering: 'Not answering',
  thisComputer: 'this computer',
  day: 'Day',
  night: 'Night',
  pages: 'Pages',
  theme: 'Theme',
  pending: 'This page is being rebuilt.',
  stale: 'The served page changed after this tab opened, so this page is out of date.',
  reload: 'Reload the page',
} as const;

export const NAV = [
  ['accounts', C.accounts],
  ['requests', C.requests],
  ['sessions', C.sessions],
  ['teams', C.teams],
  ['usage', C.usage],
  ['models', C.models],
  ['playground', C.playground],
  ['settings', C.settings],
] as const;
