import { fmtInt, fmtUsd } from '../../lib/format';

export const B = {
  title: 'Spend and tokens',
  why: 'Recorded requests, grouped by what they actually used. A bar opens the matching Requests.',
  group: 'Group usage by',
  model: 'Model',
  account: 'Account',
  day: 'Day',
  reading: 'Reading the request usage…',
  none: 'No requests in this window.',
  unavailable: 'This splice does not report full-window usage yet.',
  partial: 'This breakdown is incomplete.',
  unreportedModel: 'Model not reported',
  unreportedAccount: 'Account not reported',
  unpriced: (n: number) => `${fmtInt(n)} ${n === 1 ? 'request has' : 'requests have'} no recorded price.`,
  inputMissing: (n: number) => `${fmtInt(n)} ${n === 1 ? 'request has' : 'requests have'} no input token count.`,
  outputMissing: (n: number) => `${fmtInt(n)} ${n === 1 ? 'request has' : 'requests have'} no output token count.`,
  accountWhy: 'Each request names the account it used. Requests without an account stay separate.',
  dayWhy: 'Days use your local time zone.',
  amount: 'API cost, estimated',
  input: 'Input tokens',
  output: 'Output tokens',
  requests: 'Requests',
  requestCount: (n: number) => `${fmtInt(n)} ${n === 1 ? 'request' : 'requests'}`,
  inspect: (label: string) => `Open Requests for ${label}`,
  atLeast: (value: string) => `At least ${value}`,
  table: 'Show the values as a table',
  plot: 'Show spend bars',
  unknown: 'Not reported',
  near: (remaining: number) => `Budget running low. ${fmtUsd(remaining)} remains at the recorded spend.`,
  reached: 'The recorded spend has reached the daily budget.',
  spentUnknown: 'Spending is not reported. The remaining budget is unknown.',
  warningPartial: 'Some requests have no price, so actual spending can be higher.',
  chartLabel: 'Recorded API cost',
  chooseCommand: 'Choose a command',
  commandScroll: 'Scroll the command menu to see every command.',
  discardWhy: 'Discard this unsaved budget?',
  discard: 'Discard changes',
  keepEditing: 'Keep editing',
  budgetUnpriced: 'This command has no reported per-token prices. A dollar budget cannot measure its spending until prices are declared.',
  budgetPriced: 'The catalog declares token prices for this command. Only requests with a price count toward its dollar budget.',
  pricing: 'Prices and missing spending',
  pricingWhy: 'Dollar estimates need declared token prices and recorded token counts. They are not subscription bills or the cost of running a local model.',
  priceCountersWhy: 'Declared prices do not supply missing token counts.',
  pricesFor: (name: string) => `Prices for ${name}`,
  missingPrices: (names: string) => `No price is declared for: ${names}.`,
  recordedMissing: (n: number) => `${fmtInt(n)} ${n === 1 ? 'request has' : 'requests have'} no dollar estimate at the declared prices.`,
  subscription: (plan: string) => `This command runs on its ${plan} plan. Declared token prices estimate equivalent API cost, not your subscription bill.`,
  noUsedModels: 'No model usage is reported for this command in this window. Price guidance appears for the models your requests used.',
  priceCatalogMissing: 'The model catalog has not reported prices for this command.',
  pricesDeclared: 'Its current models have declared prices.',
  priceHow: 'To set an estimate, back up the configuration file, then declare your actual prices under this command’s rates table. Values are USD per million tokens. Replace each placeholder with a number, then restart splice to apply it.',
  priceExample: 'Price declaration with placeholders',
  priceConfig: 'Find the configuration file',
  pricesReading: 'Reading the model prices…',
  pricesUnavailable: 'This splice does not report model prices yet.',
} as const;
