#!/usr/bin/env bun
/** Kotlin AST rules - runs ast-grep on Edit/Write targets.
 *
 *  Only triggers for .kt files.
 *  Generated by torad-toolkit, version 1.0.0
 *
 *  DISABLED BY NAME: the leading underscore makes runner.ts skip this module, exactly as the
 *  `_`-prefix rule did in Python. That is why its interface is the OLD one — `run` returns a
 *  Claude-Code-shaped `{continue, message}` object rather than a HookResult — and why the runner's
 *  result type check never sees it. It is kept compiled so the file is not a Python leftover, not
 *  because anything dispatches it.
 */
import { spawnSync } from "node:child_process";
import { existsSync, readFileSync, statSync } from "node:fs";
import { dirname, join, resolve as pathResolve } from "node:path";

type HookEvent = Record<string, unknown>;

export function applies(data: HookEvent): boolean {
  const tool = String(data.tool_name ?? "");
  if (tool !== "Edit" && tool !== "Write") return false;

  const toolInput = (data.tool_input ?? {}) as Record<string, unknown>;
  return String(toolInput.file_path ?? "").endsWith(".kt");
}

export function run(data: HookEvent): Record<string, unknown> {
  const toolInput = (data.tool_input ?? {}) as Record<string, unknown>;
  const filePath = String(toolInput.file_path ?? "");

  // Find project root (where .rules/kotlin exists)
  let root = dirname(pathResolve(filePath));
  let found: string | null = null;
  for (;;) {
    const candidate = join(root, ".rules/kotlin/ast-grep/sgconfig.yml");
    if (existsSync(candidate) && statSync(candidate).isFile()) {
      found = candidate;
      break;
    }
    const parent = dirname(root);
    if (parent === root) break;
    root = parent;
  }
  if (found === null) return { continue: true }; // No rules found

  const proc = spawnSync("ast-grep", ["scan", "--config", found, filePath, "--json"], {
    encoding: "utf8",
    timeout: 10000,
    maxBuffer: 256 * 1024 * 1024,
  });
  // Python caught TimeoutExpired and FileNotFoundError separately only to print different
  // sentences to stderr; both returned the same value, so one branch carries both messages.
  if (proc.error) {
    const code = (proc.error as NodeJS.ErrnoException).code;
    if (code === "ETIMEDOUT") {
      process.stderr.write("[kotlin_rules] ast-grep timed out\n");
    } else if (code === "ENOENT") {
      process.stderr.write("[kotlin_rules] ast-grep not installed - rules not enforced\n");
    } else {
      process.stderr.write(`[kotlin_rules] error: ${proc.error}\n`);
    }
    return { continue: true };
  }

  if (proc.status === 0) return { continue: true };

  let violations: Record<string, unknown>[] = [];
  try {
    const parsed = JSON.parse(proc.stdout || "[]") as unknown;
    if (Array.isArray(parsed)) violations = parsed as Record<string, unknown>[];
  } catch {
    violations = [];
  }

  if (violations.length === 0) return { continue: true };

  const messages: string[] = [];
  for (const v of violations.slice(0, 5)) {
    const rule = v.ruleId ?? "unknown";
    const range = (v.range ?? {}) as { start?: { line?: unknown } };
    messages.push(`  - ${rule} at line ${range.start?.line ?? "?"}`);
  }

  return {
    continue: true,
    message: `ast-grep found ${violations.length} issue(s):\n` + messages.join("\n"),
  };
}

// The standalone entry the generated module shipped with. Bun only runs this when the file is
// executed directly rather than imported, which is the port of `if __name__ == "__main__"`.
if (import.meta.main) {
  try {
    const data = JSON.parse(readFileSync(0, "utf8") || "") as HookEvent;
    if (applies(data)) {
      process.stdout.write(JSON.stringify(run(data)));
    } else {
      process.stdout.write(JSON.stringify({ continue: true }));
    }
  } catch (exc) {
    process.stderr.write(`[kotlin_rules] fatal: ${exc}\n`);
    process.stdout.write(JSON.stringify({ continue: true }));
  }
}
