#!/usr/bin/env python3
"""Kotlin AST rules - runs ast-grep on Edit/Write targets.

Only triggers for .kt files.
Generated by torad-toolkit, version 1.0.0
"""
import json
import subprocess
import sys
from pathlib import Path


def applies(data: dict) -> bool:
    """Only run for Edit/Write on Kotlin files."""
    tool = data.get("tool_name", "")
    if tool not in ("Edit", "Write"):
        return False

    file_path = data.get("tool_input", {}).get("file_path", "")
    return file_path.endswith(".kt")


def run(data: dict) -> dict:
    """Run ast-grep rules on the target file."""
    file_path = data.get("tool_input", {}).get("file_path", "")

    # Find project root (where .rules/kotlin exists)
    path = Path(file_path).resolve()
    root = path.parent
    while root != root.parent:
        if (root / ".rules" / "kotlin" / "ast-grep" / "sgconfig.yml").exists():
            break
        root = root.parent
    else:
        return {"continue": True}  # No rules found

    sgconfig = root / ".rules" / "kotlin" / "ast-grep" / "sgconfig.yml"

    try:
        result = subprocess.run(
            ["ast-grep", "scan", "--config", str(sgconfig), str(file_path), "--json"],
            capture_output=True,
            text=True,
            timeout=10,
        )

        if result.returncode == 0:
            return {"continue": True}

        # Parse violations
        try:
            violations = json.loads(result.stdout) if result.stdout else []
        except json.JSONDecodeError:
            violations = []

        if not violations:
            return {"continue": True}

        # Format violations for Claude
        messages = []
        for v in violations[:5]:  # Limit to 5
            rule = v.get("ruleId", "unknown")
            line = v.get("range", {}).get("start", {}).get("line", "?")
            messages.append(f"  - {rule} at line {line}")

        return {
            "continue": True,
            "message": f"ast-grep found {len(violations)} issue(s):\n" + "\n".join(messages),
        }

    except subprocess.TimeoutExpired:
        print("[kotlin_rules] ast-grep timed out", file=sys.stderr)
        return {"continue": True}
    except FileNotFoundError:
        print("[kotlin_rules] ast-grep not installed - rules not enforced", file=sys.stderr)
        return {"continue": True}
    except Exception as e:
        print(f"[kotlin_rules] error: {e}", file=sys.stderr)
        return {"continue": True}


if __name__ == "__main__":
    try:
        data = json.loads(sys.stdin.read())
        if applies(data):
            result = run(data)
            print(json.dumps(result))
        else:
            print(json.dumps({"continue": True}))
    except Exception as e:
        print(f"[kotlin_rules] fatal: {e}", file=sys.stderr)
        print(json.dumps({"continue": True}))
