// Every label this page prints. Lowercase, three words or fewer, no em-dash (CONTRACTS.md
// section 4, enforced by the label wall).
export const S = {
  title: 'models',
  byHead: 'by head',
  byProvider: 'by provider',
  catalog: 'catalog',
  tiers: 'tiers',
  model: 'model',
  slot: 'slot',
  contextWindow: 'context window',
  windowSource: 'window source',
  rates: 'rates',
  rateInput: 'input',
  rateRead: 'cache read',
  rateWrite: 'cache write',
  rateOutput: 'output',
  pinned: 'pinned',
  pinnedYes: 'pinned',
  pinnedNo: 'not pinned',
  undeclared: 'not declared',
  noRates: 'no rates',
  extraWindows: 'extra windows',
  windowRules: 'window rules',
  defaultWindow: 'default window',
  headWindow: 'head window',
  sample: 'sample data',
  openModel: 'open model',
} as const;
