// What Fleet says. Copy lives in modules like this one, never inline in a component.
export const F = {
  title: 'Fleet',
  add: 'Add a plan',
  reading: 'Reading the fleet…',
  empty: 'No plans yet.',
  emptyWhy: 'Sign in with a subscription, paste an API key, or point at your own GPU.',
  bringAnother: 'Bring another plan',
  bringWhy: 'Sign in with a subscription, paste an API key, or point at your own GPU.',
  switchAccount: 'Switch account',
  signIn: 'Sign in',
  signInAgain: 'Sign in again',
  start: 'Start',
  starting: 'Starting…',
  restart: 'Restart',
  restarting: 'Restarting…',
  copyStart: 'Copy start command',
  copied: 'Copied',
  dragHandle: 'Drag to reorder',
  noWindow: 'This plan reports no usage window.',
  failed: 'That did not work:',
} as const;

export const D = {
  back: 'Fleet',
  windows: 'Windows',
  windowsTab: 'Plan windows',
  noWindows: 'This plan reports no window.',
  accounts: 'Accounts',
  noAccounts: 'This head has no account pool: it uses one login or a key.',
  selected: 'In use',
  pinned: 'Pinned',
  next: 'Next',
  primary: 'Primary',
  resetPassed: 'Reset, not re-read',
  switch: 'Switch to this one',
  unpin: 'Unpin',
  relabel: 'Rename',
  remove: 'Remove',
  removeAsk: 'Remove this account?',
  removeWhy: 'Its login is deleted from this computer; you can sign in again later.',
  relabelAsk: 'Rename this account',
  newName: 'New name',
  save: 'Save',
  cancel: 'Cancel',
  addAccount: 'Add account',
  refresh: 'Refresh sign-in',
  refreshing: 'Refreshing…',
  refreshed: 'Signed in again with the saved login.',
  refreshRefused: 'It did not refresh.',
  unsupported: 'This splice version cannot do that.',
  notFound: 'No head has that name.',
  readingHead: 'Reading the plan…',
  tabsLabel: 'Show',
  models: 'Models',
  log: 'Log',
} as const;

export const HT = {
  tabs: 'Show',
  modelsUnserved: 'This version of splice does not serve the model catalog.',
  noCatalog: 'The daemon lists no models for this plan.',
  tiers: 'What Claude Code gets',
  tiersWhy: 'Claude Code asks for a tier by name; each row is the model that answers it.',
  slot: { opus: 'Opus tier', sonnet: 'Sonnet tier', haiku: 'Haiku tier', fable: 'Fable tier' } as const,
  notDeclared: 'Not declared: this plan answers it with its default.',
  everyModel: 'Every model',
  pinned: 'Pinned',
  unresolved: 'Not in the catalog',
  window: (tokens: string, source: string): string => `${tokens} tokens · ${source}`,
  noWindow: 'No window known',
  compare: 'Compare with the provider',
  comparing: 'Asking the provider…',
  compared: 'What the provider publishes',
  unpublished: 'This provider publishes no list to compare with.',
  unreadable: 'The provider’s list could not be read:',
  agrees: 'Every declared model is served.',
  differs: 'Some declared models need a decision.',
  windowsDiffer: (declared: string, upstream: string): string => `declared ${declared}, provider ${upstream}`,
  addModels: 'Add models',
  addModelsWhy: 'Models the catalogue offers that this plan does not reach yet.',
  addModelsNone: 'Every catalogue model is on this plan already.',
  addModelsPick: (id: string): string => `Add ${id}`,
  addModelsGo: (count: number): string => (count === 1 ? 'Add 1 model and restart' : `Add ${count} models and restart`),
  addModelsAdding: 'Adding…',
  addModelsAdded: (ids: string): string => `Added ${ids}.`,
  addModelsWritten: (path: string): string => `Written to ${path}.`,
  addModelsFailed: 'That did not add:',
  logFollowing: 'Following',
  lines: 'Lines',
  level: 'Level',
  levelAll: 'All',
  levelError: 'Errors',
  levelWarn: 'Warnings',
  filter: 'Filter the log',
  logEmpty: 'This head has written nothing yet.',
  logRestarted: 'The log restarted, so this is its newest window.',
  copyLog: 'Copy what is shown',
  copiedLog: 'Copied',
  logWhere: 'Read from',
} as const;
