// What Fleet says. Copy lives in modules like this one, never inline in a component.
export const F = {
  title: 'Fleet',
  add: 'Add a command',
  reading: 'Reading the fleet…',
  empty: 'No commands yet.',
  emptyWhy: 'Sign in with a subscription, paste an API key, or point at your own GPU.',
  bringAnother: 'Bring another command',
  bringWhy: 'Sign in with a subscription, paste an API key, or point at your own GPU.',
  switchAccount: 'Switch account',
  signIn: 'Sign in',
  signInAgain: 'Sign in again',
  start: 'Start',
  starting: 'Starting…',
  restart: 'Restart',
  restarting: 'Restarting…',
  copyStart: 'Copy start command',
  copied: 'Copied',
  dragHandle: 'Drag to reorder',
  failed: 'That did not work:',
} as const;

export const D = {
  back: 'Fleet',
  windows: 'Windows',
  windowsTab: 'Plan windows',
  noWindows: 'This command reports no window.',
  accounts: 'Accounts',
  noAccounts: 'This command has no account pool: it uses one login or a key.',
  selected: 'In use',
  pinned: 'Pinned',
  next: 'Next',
  nextBecause: (rule: string): string => `Next because it is ${rule}.`,
  nextRule: { pinned: 'the pinned account', primary: 'the primary account', 'last used': 'the one this session last used', 'most weekly room': 'the one with the most weekly room' } as const,
  selectorOrder: (order: string): string => `The next account is taken in this order: ${order}.`,
  primary: 'Primary',
  /** A window by the length the provider reported, as a person says it: `week`, `5-hour window`, else its length and `window`. */
  windowWord: (seconds: number, length: string): string => (seconds === 604800 ? 'week' : seconds === 18000 ? '5-hour window' : `${length} window`),
  thisAccount: 'This account',
  steppedPast: (name: string, window: string, serving: string): string => `${name}’s ${window} is used; turns go to ${serving}`,
  resetPassed: 'Reset, not re-read',
  switch: 'Switch to this one',
  unpin: 'Unpin',
  relabel: 'Rename',
  remove: 'Remove',
  removeAsk: 'Remove this account?',
  removeWhy: 'Its login is deleted from this computer; you can sign in again later.',
  relabelAsk: 'Rename this account',
  newName: 'New name',
  save: 'Save',
  cancel: 'Cancel',
  addAccount: 'Add account',
  refresh: 'Refresh sign-in',
  refreshing: 'Refreshing…',
  refreshed: 'Signed in again with the saved login.',
  refreshRefused: 'It did not refresh.',
  noCredential: 'Its login file is gone. Sign in again to use it.',
  unsupported: 'This splice version cannot do that.',
  notFound: 'No command has that name.',
  readingHead: 'Reading the command…',
  tabsLabel: 'Show',
  models: 'Models',
  log: 'Log',
} as const;

export const HT = {
  tabs: 'Show',
  modelsUnserved: 'This version of splice does not serve the model catalog.',
  noCatalog: 'The daemon lists no models for this command.',
  tiers: 'What Claude Code gets',
  tiersWhy: 'Claude Code asks for a tier by name; each row is the model that answers it.',
  slot: { opus: 'Opus tier', sonnet: 'Sonnet tier', haiku: 'Haiku tier', fable: 'Fable tier' } as const,
  notDeclared: 'Not declared: this command answers it with its default.',
  everyModel: 'Every model',
  pinned: 'Pinned',
  unresolved: 'Not in the catalog',
  window: (tokens: string, source: string): string => `${tokens} tokens · ${source}`,
  noWindow: 'No window known',
  declared: 'Windows this command declares',
  declaredWhy: 'Set in splice.toml, apart from the catalogue’s own window for each model.',
  planWindow: 'Plan window',
  providerWindow: 'Provider default',
  extraWindows: 'Extra windows',
  windowRules: 'Window rules',
  notSet: 'Not set',
  compare: 'Compare with the provider',
  comparing: 'Asking the provider…',
  compared: 'What the provider publishes',
  unpublished: 'This provider publishes no list to compare with.',
  unreadable: 'The provider’s list could not be read:',
  agrees: 'Every declared model is served.',
  differs: 'Some declared models need a decision.',
  windowsDiffer: (declared: string, upstream: string): string => `declared ${declared}, provider ${upstream}`,
  addModels: 'Add models',
  addModelsWhy: 'Models the catalogue offers that this command does not reach yet.',
  addModelsNone: 'Every catalogue model is on this command already.',
  addModelsPick: (id: string): string => `Add ${id}`,
  addModelsGo: (count: number): string => (count === 1 ? 'Add 1 model and restart' : `Add ${count} models and restart`),
  addModelsAdding: 'Adding…',
  addModelsAdded: (ids: string): string => `Added ${ids}.`,
  addModelsWritten: (path: string): string => `Written to ${path}.`,
  addModelsFailed: 'That did not add:',
  logFollowing: 'Following',
  lines: 'Lines',
  level: 'Level',
  levelAll: 'All',
  levelError: 'Errors',
  levelWarn: 'Warnings',
  filter: 'Filter the log',
  logEmpty: 'This command has written nothing yet.',
  logRestarted: 'The log restarted, so this is its newest window.',
  copyLog: 'Copy what is shown',
  copiedLog: 'Copied',
  logWhere: 'Read from',
} as const;
