// What Fleet says. Copy lives in modules like this one, never inline in a component.
export const F = {
  title: 'Fleet',
  add: 'Add a plan',
  reading: 'Reading the fleet…',
  empty: 'No plans yet.',
  emptyWhy: 'Sign in with a subscription, paste an API key, or point at your own GPU.',
  bringAnother: 'Bring another plan',
  bringWhy: 'Sign in with a subscription, paste an API key, or point at your own GPU.',
  switchAccount: 'Switch account',
  signIn: 'Sign in',
  signInAgain: 'Sign in again',
  start: 'Start',
  starting: 'Starting…',
  restart: 'Restart',
  restarting: 'Restarting…',
  copyStart: 'Copy start command',
  copied: 'Copied',
  dragHandle: 'Drag to reorder',
  failed: 'That did not work:',
} as const;

export const D = {
  back: 'Fleet',
  windows: 'Windows',
  windowsTab: 'Plan windows',
  noWindows: 'This plan reports no window.',
  accounts: 'Accounts',
  noAccounts: 'This head has no account pool: it uses one login or a key.',
  selected: 'In use',
  pinned: 'Pinned',
  next: 'Next',
  primary: 'Primary',
  resetPassed: 'Reset, not re-read',
  switch: 'Switch to this one',
  unpin: 'Unpin',
  relabel: 'Rename',
  remove: 'Remove',
  removeAsk: 'Remove this account?',
  removeWhy: 'Its login is deleted from this computer; you can sign in again later.',
  relabelAsk: 'Rename this account',
  newName: 'New name',
  save: 'Save',
  cancel: 'Cancel',
  addAccount: 'Add account',
  unsupported: 'This splice version cannot do that.',
  notFound: 'No head has that name.',
  readingHead: 'Reading the plan…',
  tabsLabel: 'Show',
  models: 'Models',
  log: 'Log',
} as const;
