// Every label this page prints. Lowercase, three words or fewer, no em-dash (CONTRACTS.md
// section 4, enforced by the label wall). Sentences live in the component.
export const S = {
  title: 'usage',
  byHead: 'by head',
  byModel: 'by model',
  window: 'window',
  heads: 'heads',
  models: 'models',
  burn: 'burn',
  tokens: 'tokens',
  turns: 'turns',
  inTokens: 'in tokens',
  cached: 'cached',
  cacheWrite: 'cache write',
  outTokens: 'out tokens',
  amplification: 'in per out',
  perTurn: 'in per turn',
  wireDelta: 'wire delta',
  ceiling: 'ceiling',
  spent: 'spent',
  exhaustion: 'exhaustion',
  limited: 'rate limited',
  sample: 'sample data',
  detail: 'head detail',
  openHead: 'open head',
  slot: 'slot',
  contextWindow: 'context window',
  sourceLabel: 'window source',
  inputRate: 'input rate',
  cacheReadRate: 'cache read rate',
  cacheWriteRate: 'cache write rate',
  outputRate: 'output rate',
  pinned: 'pinned',
} as const;
