import { describe, expect, test } from 'vitest';
import { callTarget, foldTranscript, interleave, outputSize, toolLabel, toolPath, toolTarget, withoutEchoed } from '../src/lib/conversation';
import type { SessionEdge, TranscriptMessage } from '../src/types/sessions';

const say = (index: number, role: TranscriptMessage['role'], text: string, ts?: number): TranscriptMessage => ({ index, role, text, ...(ts === undefined ? {} : { ts }) });
const call = (index: number, tool: string, input: unknown, ts?: number): TranscriptMessage => ({ ...say(index, 'assistant', JSON.stringify(input), ts), tool, result: false });
const result = (index: number, tool: string, text: string): TranscriptMessage => ({ ...say(index, 'tool', text), tool, result: true });

describe('folding a transcript', () => {
  test('a call and its result become one item; the last unanswered call is still running', () => {
    const items = foldTranscript([say(0, 'user', 'go'), call(1, 'Bash', { command: 'ls' }), result(2, 'Bash', 'a\nb'), call(3, 'Bash', { command: 'sleep 9' })]);
    expect(items.map((item) => item.kind)).toEqual(['say', 'tool', 'tool']);
    expect(items[1]).toMatchObject({ tool: 'Bash', output: 'a\nb', last: false });
    expect(items[2]).toMatchObject({ output: null, last: true });
  });
  test('a result joins the newest open call of its own tool, not another tool\'s', () => {
    const items = foldTranscript([call(0, 'Read', { file_path: 'a' }), call(1, 'Bash', { command: 'x' }), result(2, 'Read', 'file body')]);
    expect(items[0]).toMatchObject({ tool: 'Read', output: 'file body' });
    expect(items[1]).toMatchObject({ tool: 'Bash', output: null });
  });
  test('parallel calls of one tool keep their own results when those results arrive in either order', () => {
    for (const results of [[0, 1], [1, 0]]) {
      const items = foldTranscript([
        { ...call(0, 'Read', { file_path: '/synthetic/first' }), tool_use_id: 'first' },
        { ...call(1, 'Read', { file_path: '/synthetic/second' }), tool_use_id: 'second' },
        ...results.map((id, index) => ({ ...result(index + 2, 'Read', id === 0 ? 'first body' : 'second body'), tool_use_id: id === 0 ? 'first' : 'second' })),
      ]);
      expect(items).toHaveLength(2);
      expect(items[0]).toMatchObject({ input: { file_path: '/synthetic/first' }, output: 'first body' });
      expect(items[1]).toMatchObject({ input: { file_path: '/synthetic/second' }, output: 'second body' });
    }
  });
  test('identity wins over a missing or different display name', () => {
    const items = foldTranscript([
      { ...call(0, 'Read', { file_path: '/synthetic/first' }), tool_use_id: 'first' },
      { ...say(1, 'tool', 'first body'), result: true, tool_use_id: 'first' },
    ]);
    expect(items).toHaveLength(1);
    expect(items[0]).toMatchObject({ tool: 'Read', output: 'first body' });
  });
  test('an identified orphan never answers another same-name call and an unnamed orphan stays readable', () => {
    const items = foldTranscript([
      { ...call(0, 'Read', { file_path: '/synthetic/current' }), tool_use_id: 'current' },
      { ...result(1, 'Read', 'earlier body'), tool_use_id: 'earlier' },
      { ...say(2, 'tool', 'unnamed body'), result: true, tool_use_id: 'unseen' },
    ]);
    expect(items).toHaveLength(3);
    expect(items[0]).toMatchObject({ output: null });
    expect(items[1]).toMatchObject({ output: 'earlier body', input: null });
    expect(items[2]).toMatchObject({ output: 'unnamed body', input: null });
  });
  test('legacy results join only an unambiguous legacy call, never an identified call', () => {
    const items = foldTranscript([
      { ...call(0, 'Read', { file_path: '/synthetic/identified' }), tool_use_id: 'known' },
      call(1, 'Read', { file_path: '/synthetic/legacy' }),
      result(2, 'Read', 'legacy body'),
    ]);
    expect(items[0]).toMatchObject({ output: null });
    expect(items[1]).toMatchObject({ output: 'legacy body' });
    const ambiguous = foldTranscript([call(0, 'Read', {}), call(1, 'Read', {}), result(2, 'Read', 'unattributed')]);
    expect(ambiguous).toHaveLength(3);
    expect(ambiguous.slice(0, 2)).toMatchObject([{ output: null }, { output: null }]);
  });
  test('a result whose call was on an earlier page is kept as an item, not dropped', () => {
    const items = foldTranscript([result(9, 'Bash', 'late')]);
    expect(items).toHaveLength(1);
    expect(items[0]).toMatchObject({ kind: 'tool', output: 'late', input: null });
  });
  test('input that is not JSON stays as text', () => {
    const [item] = foldTranscript([{ ...say(0, 'assistant', 'plain words'), tool: 'X', result: false }]);
    expect(item).toMatchObject({ input: 'plain words', inputText: 'plain words' });
  });
  test('a slash command and its output are one quiet line, and the caveat about local commands is dropped', () => {
    const items = foldTranscript([
      say(0, 'user', '<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages.</local-command-caveat>'),
      say(1, 'user', '<command-name>/clear</command-name>\n<command-message>clear</command-message>\n<command-args></command-args>'),
      say(2, 'user', '<local-command-stdout>Compacted</local-command-stdout>'),
      say(3, 'user', 'thanks'),
    ]);
    expect(items).toHaveLength(2);
    expect(items[0]).toMatchObject({ kind: 'note', line: 'Ran /clear', detail: 'Compacted' });
    expect(items[1]).toMatchObject({ kind: 'say', text: 'thanks' });
  });
  test('a command that printed nothing is only the command, and output with no command before it shows as output', () => {
    const items = foldTranscript([say(0, 'user', '<command-name>/clear</command-name><command-args></command-args>'), say(1, 'user', '<local-command-stdout></local-command-stdout>'), say(2, 'user', 'hi'), say(3, 'system', '<local-command-stdout>ok</local-command-stdout>')]);
    expect(items).toMatchObject([{ kind: 'note', line: 'Ran /clear', detail: null }, { kind: 'say' }, { kind: 'note', line: 'Output · ok' }]);
  });
  test('a background task notice is a named event, never its tags', () => {
    const [item] = foldTranscript([say(0, 'user', '<task-notification><task-id>b8l</task-id><summary>new commits on feat/v0.4.0</summary></task-notification>')]);
    expect(item).toMatchObject({ kind: 'note', line: 'Background task · new commits on feat/v0.4.0' });
  });
});

describe('what a call did', () => {
  test('names its target by tool', () => {
    expect(toolTarget('Bash', { command: 'npm test\nmore' })).toBe('npm test');
    expect(toolTarget('Bash', { command: 'git status --short', description: 'Show working tree status' })).toBe('Show working tree status');
    expect(toolTarget('Edit', { file_path: 'src/a.ts', old_string: 'x', new_string: 'y' })).toBe('a.ts');
    expect(toolTarget('Read', { file_path: '/home/marcos/dev/splice/console-next/src/lib/fleet.ts' })).toBe('fleet.ts');
    expect(toolPath('Read', { file_path: '/home/marcos/dev/splice/fleet.ts' })).toBe('/home/marcos/dev/splice/fleet.ts');
    expect(toolPath('Bash', { command: 'ls' })).toBeNull();
    expect(toolTarget('Grep', { pattern: 'foo' })).toBe('foo');
    expect(toolTarget('SendMessage', { to: 'builder' })).toBe('to builder');
    expect(toolTarget('SendMessage', { to: 'uds:/run/user/1000/cc-socks/1587057.sock' })).toBe('to another session');
    expect(toolTarget('Weird', { name: 'n' })).toBe('n');
    expect(toolTarget('Skill', { skill: 'campaign' })).toBe('campaign');
    expect(toolTarget('SendUserFile', { files: ['a.png', 'b.png'] })).toBe('a.png');
    expect(toolTarget('AskUserQuestion', { questions: [{ question: 'Which one?' }] })).toBe('Which one?');
  });
  test('nothing obvious, or input that is text, names nothing', () => {
    expect(toolTarget('ListAgents', {})).toBeNull();
    expect(toolTarget('Bash', 'raw')).toBeNull();
    expect(toolTarget('Bash', { command: '   ' })).toBeNull();
  });
  test('a result\'s size, and none before it comes', () => {
    expect(outputSize('a\nb\nc')).toEqual({ lines: 3, chars: 5 });
    expect(outputSize('')).toEqual({ lines: 0, chars: 0 });
    expect(outputSize(null)).toBeNull();
  });
});

describe('hand-offs among the messages', () => {
  const edge = (at: number) => ({ from: 'p', to: 'uds:/me', at, direction: 'in' as const });
  test('each lands by its time; one before the first message comes first, one after the last comes last', () => {
    const items = foldTranscript([say(0, 'user', 'a', 100), say(1, 'assistant', 'b', 200)]);
    const timeline = interleave(items, [edge(50), edge(150), edge(999)]);
    expect(timeline.map((entry) => (entry.kind === 'handoff' ? `h${entry.at}` : `m${entry.at}`))).toEqual(['h50', 'm100', 'h150', 'm200', 'h999']);
  });
  test('messages with no time keep their order and never pull a hand-off out of place', () => {
    const items = foldTranscript([say(0, 'user', 'a'), say(1, 'assistant', 'b')]);
    expect(interleave(items, [edge(10)]).map((entry) => entry.kind)).toEqual(['item', 'item', 'handoff']);
  });
});

describe('a tool row says what the tool did', () => {
  test('a command with a description shows the description', () => {
    expect(toolTarget('Bash', { command: 'echo "=== repo root ===" && pwd', description: 'Show where the repo is' })).toBe('Show where the repo is');
  });
  test('an MCP tool id reads as its server and tool', () => {
    expect(toolLabel('mcp__ast-grep__find_code_by_rule')).toBe('ast-grep · find code by rule');
    expect(toolLabel('mcp__eli-brain__query_brain')).toBe('eli-brain · query brain');
    expect(toolLabel('mcp__plugin_figma_figma__authenticate')).toBe('figma · authenticate');
    expect(toolLabel('mcp__claude_ai_Claude_Docs__read')).toBe('claude ai Claude Docs · read');
    expect(toolLabel('Bash')).toBe('Bash');
  });
});

describe('what a call in a turn\'s conversation did', () => {
  test('a whole input reads as the tool\'s own target', () => {
    expect(callTarget('Bash', '{"command":"git log","description":"Show the log"}')).toBe('Show the log');
    expect(callTarget('Read', '{"file_path":"/x/src/a.ts"}')).toBe('a.ts');
  });
  test('a cut-off input still gives its description, else the first line of its command', () => {
    expect(callTarget('Bash', '{"command":"cd /x && ls \\"a b\\"","description":"List the folder')).toBe('List the folder');
    expect(callTarget('Bash', '{"command":"echo one\\necho two')).toBe('echo one');
    expect(callTarget('Skill', '{not json')).toBeNull();
  });
});

describe('a message another session sent', () => {
  const wrapped = (from: string, body: string) => `<cross-session-message from="uds:/run/user/1000/cc-socks/1.sock" from-name="${from}" from-mode="bypass">${body}</cross-session-message>`;
  test('reads as a message from its sender, with no wrapper and no socket path', () => {
    const items = foldTranscript([{ index: 0, role: 'user', ts: 5, text: wrapped('splice-lead', 'Two things.\nNow.') }]);
    expect(items).toEqual([{ kind: 'peer', index: 0, ts: 5, from: 'splice-lead', text: 'Two things.\nNow.' }]);
    expect(foldTranscript([{ index: 0, role: 'user', text: '<cross-session-message from="uds:/x.sock">hi</cross-session-message>' }])[0]).toMatchObject({ kind: 'peer', from: 'another session' });
  });
  test('an in hand-off its receiver\'s own transcript already shows is not shown twice; an unrelated one stays', () => {
    const items = foldTranscript([{ index: 0, role: 'user', ts: 100_000, text: wrapped('splice-lead', 'hello') }]);
    const edge = (over: Partial<SessionEdge>): SessionEdge => ({ from: 'a', to: 'b', at: 100_500, direction: 'in', ...over });
    const name = (edge: SessionEdge): string | null => (edge.from === 'a' ? 'splice-lead' : edge.from === 'z' ? null : 'someone else');
    expect(withoutEchoed([edge({})], items, name)).toEqual([]);
    expect(withoutEchoed([edge({ from: 'z' })], items, name)).toEqual([]);
    expect(withoutEchoed([edge({ from: 'q' })], items, name)).toHaveLength(1);
    expect(withoutEchoed([edge({ at: 900_000 })], items, name)).toHaveLength(1);
    expect(withoutEchoed([edge({ direction: 'out' })], items, name)).toHaveLength(1);
  });
});
