// One cleaner reads every message a page prints: each kind of wrapper the client writes has a case here.
import { describe, expect, test } from 'vitest';
import { cleanMessage, plainLine, readable } from '../src/lib/message';

describe('a message read for people', () => {
  test('plain words are unchanged', () => {
    expect(cleanMessage('Run the tests.')).toEqual({ kind: 'say', text: 'Run the tests.' });
    expect(cleanMessage('<b>bold</b> text')).toEqual({ kind: 'say', text: '<b>bold</b> text' });
  });
  test('the caveat about local commands never shows', () => {
    expect(cleanMessage('<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond.</local-command-caveat>')).toEqual({ kind: 'hidden' });
  });
  test('a slash command is one quiet line, with its arguments', () => {
    expect(cleanMessage('<command-name>/clear</command-name>\n<command-message>clear</command-message>\n<command-args></command-args>')).toMatchObject({ kind: 'event', line: 'Ran /clear' });
    expect(cleanMessage('<command-message>model</command-message>\n<command-name>/model</command-name>\n<command-args>opus</command-args>')).toMatchObject({ line: 'Ran /model opus' });
    expect(cleanMessage('<command-name>compact</command-name>')).toMatchObject({ line: 'Ran /compact' });
  });
  test('command output is a quiet line, colour codes removed; empty output is nothing', () => {
    expect(cleanMessage('<local-command-stdout>\u001b[2mCompacted\u001b[22m</local-command-stdout>')).toMatchObject({ kind: 'event', line: 'Output · Compacted' });
    expect(cleanMessage('<local-command-stderr>no such file</local-command-stderr>')).toMatchObject({ line: 'Output · no such file' });
    expect(cleanMessage('<local-command-stdout></local-command-stdout>')).toEqual({ kind: 'hidden' });
  });
  test('a background task notice is a named event from its summary, never its tags', () => {
    const line = cleanMessage('<task-notification>\n<task-id>b8lnhf6bq</task-id>\n<summary>new commits on feat/v0.4.0</summary>\n<event>46ff76016 docs</event>\n</task-notification>');
    expect(line).toMatchObject({ kind: 'event', label: 'Background task', text: 'new commits on feat/v0.4.0', line: 'Background task · new commits on feat/v0.4.0' });
    expect(cleanMessage('<task-notification><task-id>1</task-id><result>done here</result></task-notification>')).toMatchObject({ line: 'Background task · done here' });
  });
  test.each([
    '<cross-session-message from="uds:/synthetic/peer.sock" from-name="synthetic-reviewer" from-mode="bypass">**Synthetic review**\n\n- Preserve the boundary.</cross-session-message>',
    '<cross-session-message from="uds:/synthetic/peer.sock" from-name="synthetic-reviewer" from-mode="bypass">**Synthetic review**\n\n- Preserve the boundary.</cross-session-message>\n\nThis came from another Claude session. Synthetic delivery metadata.',
    '<system-reminder><cross-session-message from="uds:/synthetic/peer.sock" from-name="synthetic-reviewer" from-mode="bypass">**Synthetic review**\n\n- Preserve the boundary.</cross-session-message></system-reminder>',
    '<system-reminder>Another Claude session sent a message while you were working:\n<cross-session-message from="uds:/synthetic/peer.sock" from-name="synthetic-reviewer" from-mode="bypass">**Synthetic review**\n\n- Preserve the boundary.</cross-session-message>\n\nThis came from another Claude session. Synthetic delivery metadata.</system-reminder>',
    '<system-reminder>Another Claude session sent a message:\n<cross-session-message from="uds:/synthetic/peer.sock" from-name="synthetic-reviewer" from-mode="bypass">**Synthetic review**\n\n- Preserve the boundary.</cross-session-message>\n\nThis came from another Claude session. Synthetic delivery metadata.</system-reminder>',
    'Another Claude session sent a message:\n<cross-session-message from="uds:/synthetic/peer.sock" from-name="synthetic-reviewer" from-mode="bypass">**Synthetic review**\n\n- Preserve the boundary.</cross-session-message>\n\nThis came from another Claude session. Synthetic delivery metadata.',
    'Another Claude session sent a message while you were working:\n<cross-session-message from="uds:/synthetic/peer.sock" from-name="synthetic-reviewer" from-mode="bypass">**Synthetic review**\n\n- Preserve the boundary.</cross-session-message>\n\nThis came from another Claude session. Synthetic delivery metadata.',
  ])('a delivered peer envelope reads as its sender and body: %s', raw => {
    expect(cleanMessage(raw)).toEqual({ kind: 'peer', from: 'synthetic-reviewer', text: '**Synthetic review**\n\n- Preserve the boundary.' });
    expect(plainLine(raw)).toBe('synthetic-reviewer: **Synthetic review**');
    expect(readable(raw)).toBe('synthetic-reviewer: **Synthetic review**\n\n- Preserve the boundary.');
  });
  test('quoted peer examples and unrelated words outside an envelope remain ordinary content', () => {
    const example = 'An example:\n\n```xml\n<cross-session-message from-name="synthetic-reviewer">Example.</cross-session-message>\n```';
    expect(cleanMessage(example)).toEqual({ kind: 'say', text: example });
    const mixed = '<cross-session-message from-name="synthetic-reviewer">Example.</cross-session-message>\nKeep these unrelated words.';
    expect(cleanMessage(mixed)).toEqual({ kind: 'say', text: mixed });
  });
  test('a system reminder standing alone is a named note of its first line', () => {
    expect(cleanMessage('<system-reminder>\nThe task tools have not been used recently.\nMore words.\n</system-reminder>')).toMatchObject({ kind: 'event', line: 'System note · The task tools have not been used recently.' });
    expect(cleanMessage('<system-reminder></system-reminder>')).toEqual({ kind: 'hidden' });
  });
  test('reminders and caveats appended to a real message are cut off it; a message that was only them is nothing', () => {
    expect(cleanMessage('Fix the build.\n<system-reminder>Codebase instructions...</system-reminder>')).toEqual({ kind: 'say', text: 'Fix the build.' });
    expect(cleanMessage('Fix it.<local-command-caveat>Caveat: x</local-command-caveat>')).toEqual({ kind: 'say', text: 'Fix it.' });
    expect(cleanMessage('Hello\n<system-reminder>a</system-reminder>\n<system-reminder>b</system-reminder>')).toEqual({ kind: 'say', text: 'Hello' });
  });
});

describe('a message as a line or as words', () => {
  test('plainLine is the first line, or the whole line of an event, or nothing', () => {
    expect(plainLine('first\nsecond')).toBe('first');
    expect(plainLine('<task-notification><summary>built</summary></task-notification>')).toBe('Background task · built');
    expect(plainLine('<local-command-caveat>x</local-command-caveat>')).toBeNull();
  });
  test('readable keeps every line of a real message and nothing of a wrapper', () => {
    expect(readable('a\nb')).toBe('a\nb');
    expect(readable('<command-name>/clear</command-name>')).toBe('Ran /clear');
    expect(readable('<local-command-caveat>x</local-command-caveat>')).toBeNull();
  });
});
