// Every store's label and one-line explanation on the retention page.
export const S = {
  title: 'What splice keeps',
  edges: 'Message edges',
  labels: 'Activity labels',
  trace: 'Request capture',
  wireTap: 'Wire tap',
  transcripts: 'Transcript view',
  about: 'About retained data',
  status: 'Stored now',
  switch: 'Stop keeping',
  enable: 'Keep new',
  deleteKept: "Delete what's kept",
  deleteCount: (days: number, entries: number): string => `Delete ${days} ${days === 1 ? 'day' : 'days'} and ${entries} ${entries === 1 ? 'entry' : 'entries'}`,
  keptCount: (days: number, entries: number): string => `${days} ${days === 1 ? 'day' : 'days'}, ${entries} ${entries === 1 ? 'entry' : 'entries'} kept.`,
  restart: 'Restart to apply',
  openSettings: 'Open settings',
  labelHeads: 'Activity heads',
  saveHeads: 'Save these heads',
  traceFor: (head: string): string => `Capture on ${head}`,
  traceCount: (records: number, bytes: number): string => `${records} ${records === 1 ? 'record' : 'records'}, ${bytes} bytes kept.`,
} as const;

export const H = {
  edges: 'Who messaged whom and when, but not the message body.',
  labels: 'File names, commands and search patterns from tool activity.',
  trace: 'Full requests and responses for heads whose capture is on.',
  wireTap: 'Recent upstream request bodies in memory; restarting clears them.',
  transcripts: "Claude Code's own conversation files; splice reads but never deletes them.",
  edgeWindow: 'Whole UTC days, as set by Message history.',
  labelWindow: 'Today and yesterday; old days age out on the next sweep.',
  traceWindow: 'Whole UTC days, as set by Trace history.',
  wireWindow: 'Only in memory until the next restart.',
  transcriptWindow: 'Claude Code owns the files and decides when they go.',
  edgePath: 'Splice state/activity/edges-YYYY-MM-DD.jsonl',
  labelPath: 'Splice state/activity/activity-YYYY-MM-DD.jsonl',
  tracePath: 'Splice state/trace/ under each head',
  wirePath: 'Head memory, never a disk file',
  transcriptPath: 'Claude Code config/projects/',
  edgeSwitch: 'Message edges, daemon-wide; changing it needs a restart.',
  labelSwitch: 'Activity heads, by head; changing it needs a restart.',
  labelChoice: 'Enter comma-separated head keys; * explicitly chooses every head.',
  traceSwitch: 'Full trace, by head; changing it needs a restart.',
  wireSwitch: 'Wire tap, by head; changing it needs a restart.',
  transcriptSwitch: 'Transcript view, global; the switch applies live.',
  about: 'What splice stores, where it lives, and how to stop it.',
  none: 'No kept days or entries remain in this store.',
  unknown: 'The store has not answered; no empty claim is made.',
  agesOut: (date: string): string => `The last kept day ages out on ${date}.`,
  pendingTrace: 'Captured requests remain unread until a head is selected.',
  noHeads: 'No configured heads have a trace directory.',
  pendingHead: 'Per-head switches live in Settings until this page can edit them.',
  restart: 'Run splice restart to apply a saved recording change.',
  deletedUnread: (reason: string): string => `Deleted stored days, but the new count could not be read: ${reason}`,
  failedUnread: (reason: string): string => `Delete failed, and the remaining count could not be read: ${reason}`,
} as const;
