// Every store's label and one-line explanation on the retention page.
export const S = {
  title: 'What splice keeps',
  edges: 'Message edges',
  labels: 'Activity labels',
  trace: 'Request capture',
  wireTap: 'Wire tap',
  transcripts: 'Transcript view',
  turnStats: 'Turn statistics',
  about: 'About retained data',
  status: 'Stored now',
  switch: 'Stop keeping',
  enable: 'Keep new',
  deleteKept: "Delete what's kept",
  deleteCount: (days: number, entries: number): string => `Delete ${days} ${days === 1 ? 'day' : 'days'} and ${entries} ${entries === 1 ? 'entry' : 'entries'}`,
  keptCount: (days: number, entries: number): string => `${days} ${days === 1 ? 'day' : 'days'}, ${entries} ${entries === 1 ? 'entry' : 'entries'} kept.`,
  restart: 'Restart to apply',
  openSettings: 'Open settings',
  labelHeads: 'Activity plans',
  saveHeads: 'Save these plans',
  archiveDays: 'Archive days',
  saveArchive: 'Save archive days',
  stopArchive: 'Stop archiving',
  traceFor: (head: string): string => `Capture on ${head}`,
  traceCount: (records: number, bytes: number): string => `${records} ${records === 1 ? 'record' : 'records'}, ${bytes} ${bytes === 1 ? 'byte' : 'bytes'} kept.`,
} as const;

export const H = {
  edges: 'Who messaged whom and when, but not the message body.',
  labels: 'File names, commands and search patterns from tool activity.',
  trace: 'Full requests and responses for plans with capture on.',
  wireTap: 'Recent upstream request bodies in memory; restarting clears them.',
  transcripts: "Claude Code's own conversation files; splice reads but never deletes them.",
  turnStats: 'Finished turns, models, session IDs, outcomes, timing, tokens and session costs.',
  edgeWindow: 'Whole UTC days, as set by Message history.',
  labelWindow: 'Today and yesterday; old days age out on the next sweep.',
  traceWindow: 'Whole UTC days, as set by Trace history.',
  wireWindow: 'Only in memory until the next restart.',
  turnWindow: 'Current turn files have no automatic expiry.',
  turnArchive: 'Old archives clear after the chosen days, at the next rotation.',
  transcriptWindow: 'Claude Code owns the files and decides when they go.',
  edgePath: 'Splice state/activity/edges-YYYY-MM-DD.jsonl',
  labelPath: 'Splice state/activity/activity-YYYY-MM-DD.jsonl',
  tracePath: 'Splice state/trace/ under each plan',
  wirePath: 'Plan memory, never a disk file',
  transcriptPath: 'Claude Code config/projects/',
  turnPath: 'Splice state/<head>-perf.jsonl, .1, <head>-session-totals.json, and perf-archive/',
  edgeSwitch: 'Message history applies across splice after a restart.',
  labelSwitch: 'Activity labels apply per plan after a restart.',
  labelChoice: 'Enter plan keys separated by commas; * chooses every plan.',
  traceSwitch: 'Full trace applies per plan after a restart.',
  wireSwitch: 'Wire tap applies per plan after a restart.',
  transcriptSwitch: 'Transcript view, global; the switch applies live.',
  turnSwitch: 'Zero stops archives, not current turn recording; restart to apply.',
  about: 'What splice stores, where it lives, and how to stop it.',
  none: 'No kept days or entries remain in this store.',
  unknown: 'The store has not answered; no empty claim is made.',
  agesOut: (date: string): string => `The last kept day ages out on ${date}.`,
  pendingTrace: 'Captured requests remain unread until a plan is selected.',
  noHeads: 'No connected plans have a trace directory.',
  turnDelete: 'Delete removes every recorded turn time, model and session.',
  turnAfter: 'The Turns timeline and per-turn costs restart with the next turn.',
  turnSessionCost: 'Open sessions start counting cost from zero after Delete.',
  turnStill: 'New turns keep recording even when archives are off.',
  pendingHead: 'Plan switches are in Settings until this page can edit them.',
  restart: 'Run splice restart to apply a saved recording change.',
  deletedUnread: (reason: string): string => `Deleted stored days, but the new count could not be read: ${reason}`,
  failedUnread: (reason: string): string => `Delete failed, and the remaining count could not be read: ${reason}`,
} as const;
